metal3-io/cluster-api-provider-metal3

- api/v1alpha2/metal3cluster_types.go
- api/v1alpha2/metal3machine_types.go
- api/v1alpha3/metal3cluster_types.go
- api/v1alpha3/metal3machine_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
This PR changes the shortname for metal3cluster and metal3machine to m3c and m3m respectively
> :bug: Change shortnames to m3c and m3m

- clusterctl-settings.json
This small PR updates clusterctl-settings.json with correct name of the provider i.e. metal3 and also corrects the version of release.
> :bug: Fix clusterctl-settings.json file

- clusterctl-settings.json
PR #11  changed the next-version to v0.3.0, it should not point to the release version , but something else. This PR fixes this issue.
> :bug: Fix Next version in clusterctl-settings.json

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- controllers/metal3machine_controller_integration_test.go
Follow up for BMO [PR 427 ](https://github.com/metal3-io/baremetal-operator/pull/427)
Required for the completion of BMO  [PR 340](https://github.com/metal3-io/baremetal-operator/pull/340)
In this PR, added StateAvialabel to  CAPBM  case statement
After this is merged, BMO  [PR 340](https://github.com/metal3-io/baremetal-operator/pull/340)  need to be merged and then clean up in CAPBM to remove StateReady 
Fixes [#315](https://github.com/metal3-io/baremetal-operator/issues/315)
> Add StateAvailable provision state

- Makefile
`deploy-bmo-cr` in Makefile deploys bmo CRDs and CRs from examples/_out, while it is not generated before `make generate-examples` or `make deploy`. This PR modifies the `deploy-bmo-cr` to deploy the bmo CRD and CR from examples directory.
> :bug: Modify deploy-bmo-cr in Makefile

- Makefile
Current way of deploying CAPM3 locally is `make run` which in turn calls `make install` and applies the CRDs only. This is no longer sufficient with webhooks picture.  So the current way of deploying CAPM3 has bugs. One solution is to remove `install` phony all-together from Makefile because this is not needed anymore. This PR removes it which fixes the bug.
> :bug: Remove make install from Makefile

- baremetal/metal3machine_manager.go
BMCSecret Label was being updated before the BMHost itself was updated. This order should be the reverse. This PR fixes this bug. For more details, please check the following issue.
Fixes #19
> :bug: Fix bug in the order of BMH association

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- baremetal/mocks/zz_generated.metal3machine_manager.go
- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_test.go
- controllers/suite_test.go
- go.mod
- go.sum
This PR adds the functionality to set/unset pause annotation in BMH through CAPM3 machine reconcilation. The test codes are also added.
> :sparkles: Set/Unset PauseAnnotation in BMH through CAPM3 machine + Tests

- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_test.go
- go.sum
Metal3ClusterToMetal3Machines function was wrongly returning Machine object instead of metal3Machine. This PR fixes this bug and the relevant tests. 
Fixes #40
> :bug: Fix Metal3ClusterToMetal3Machines function in metal3Machine Controller

- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_test.go
Metal3ClusterToMetal3Machines function was wrongly returning Machine object instead of metal3Machine. This PR fixes this bug and the relevant tests.
Fixes #40
> Fix Metal3ClusterToMetal3Machines function in metal3Machine Controller

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
This PR fixes the use of namespaces when referring to objects. It was inconsistent and sometimes wrong. It includes :
- Use ConfigRef namespace if available for userdata secret
- refer to userdata namespace instead of host namespace
**Which issue(s) this PR fixes** :
Fixes #29
> 🐛 Fix Namespace handling

- baremetal/metal3machine_manager.go
- controllers/metal3machine_controller.go
This PR fix comparison problem issued in [48](https://github.com/metal3-io/cluster-api-provider-metal3/issues/48) by compare only group and kind in metal3machine_controller and in metal3machine_manager
>  🐛 PR fixes issue #48

- baremetal/metal3machine_manager.go
- go.sum
> :bug: UpdateObject function should operate on a deepcopy of the object

- config/crd/kustomization.yaml
> :bug: Wrong contract labels for v1alpha4

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_test.go
Currently, CAPM3 can execute multiple update operations on the BMH. This is problematic because the update triggers a reconcile of the BMH while we still process the BMH, regularly ending in a conflict, triggering a requeue.
Fixes #33
> :bug: Multiple updates operation on the BMH #33

- baremetal/metal3machine_manager.go
- go.sum
check added if BMH is paused
Fixes: #64
> :bug: CAPM3 should not select a BMH that is paused

- api/v1alpha4/metal3machine_types.go
- api/v1alpha4/metal3machine_webhook_test.go
- api/v1alpha4/metal3machinetemplate_webhook_test.go
- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
- controllers/metal3data_controller.go
- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_integration_test.go
- controllers/metal3machine_controller_test.go
- controllers/suite_test.go
This PR does a bit of code refactoring
> 🏃 refactor code to replace bmm by m3m

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- baremetal/utils.go
- baremetal/utils_test.go
- config/ipam/kustomization.yaml
Using the updateObject function was triggering an infinite loop,
as the metal3machine were reconciled when BMH were updated and
the reconciliation was always updating the BMH
Fixes #79
> 🐛 Use patch helper to update BMH

- go.mod
- go.sum
This PR updates BMO to allow the use of root device hints https://github.com/metal3-io/baremetal-operator/pull/495
> 🐛 Update BMO dependency for root device hints

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- baremetal/mocks/zz_generated.metal3machine_manager.go
- baremetal/utils.go
- baremetal/utils_test.go
- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_integration_test.go
- controllers/metal3machine_controller_test.go
Instead of always creating it from BMH UID.
Currently, after pivoting, the BMH UID has changed so the
provider IDs do not match anymore since we always used the BMH UID.
Instead, use the providerID if set in the Metal3Machine already to
avoid this issue.
**Which issue(s) this PR fixes** :
Fixes #88
> 🐛 Use providerID when set on metal3machine

- Makefile
- hack/codegen.sh
generate-go script is taking lot of time in unit tests and everytime it generates the code which is not required for unit tests, so removing generate-go from unit.
Fixes #13
> 🏃 Remove code generation from unit test

- hack/codegen.sh
Add all config files in codegen scripts.
Fixes #13
> Add config support in codegen

- baremetal/metal3data_manager.go
If the gateway is not specified in the IPPool definition or in the
subnet, the metal3data controller was hitting a
nil pointer error
> 🐛 Fix NPE when gateway is absent from IPPool

- Makefile
- controllers/metal3datatemplate_controller.go
- controllers/metal3datatemplate_controller_test.go
- examples/generate.sh
And remove the restrictions on the events triggering the reconciliation
frommetal3dataclaim to catch update events when the deletion timestamp is
set. It also improves slightly the makefile
> 🐛 Fix bug when cluster is not found

- Makefile
- hack/codegen.sh
- hack/gofmt.sh
- hack/golint.sh
Adds golint.sh and codegen.sh and make gofmt.sh fail if files
are changed
> 🏃 Update test scripts

- api/v1alpha4/common_types.go
- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
This PR adds the new `UnhealthyAnnotation = "capi.metal3.io/unhealthy"` and PR prevents the unhealthy BMH from being selected as the host for metal3machine. With new annotation users can mark BMH as unhealthy.
> ✨ PR prevents the use of BMH annotated as unhealthy

- Makefile
- config/bmo/bmo_pull_policy.yaml
- config/bmo/kustomization.yaml
This PR adds BMO image pull policy for BMO as part of CAPM3 deployment
> 🏃 Add BMO pull policy

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- baremetal/mocks/zz_generated.metal3machine_manager.go
- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_test.go
- controllers/suite_test.go
This PR adds a pause annotation on the BMH associated to the M3M as soon as the object is paused and removes it when it is resumed. This feature is needed for pivoting. It also sets the BMH status in a statusannotation on the BMH to allow for a seamless pivoting.
> ✨ Set Pause annotation on BMH when the cluster is paused

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- go.mod
- go.sum
This adds support for a new state defined in BMO : https://github.com/metal3-io/baremetal-operator/pull/571
> 🏃 Update Baremetal Operator for the new unmanaged state

- baremetal/metal3machine_manager.go
When deleting the Metal3machine, the userData used to provision might
already be deleted and absent from the status of the metal3machine,
causing the metal3machine not to be deleted since the BMH still has the
userData set. This patch forces the deletion of the userData and similar.
> 🐛 Force deletion of BMH attributes when deleting m3m

- go.mod
- go.sum
Update the version of BMO we use so we get the newer BareMetalHost with
the additional field for the boot mode. This prevents the controller from
overwriting the host with partial data and losing the user-configured
value for booting the host.
**Which issue(s) this PR fixes**
Implements https://github.com/metal3-io/metal3-docs/blob/master/design/baremetal-operator/implicit-boot-mode.md
> :running: update baremetalhost crd to include boot mode field

- examples/generate.sh
In CAPI v0.3.7+ yaml files expressions like ${PARAM:=DEFAULTVALUE} were added.
GNU envsubst can't handle such kind of expressions, so enhnaced
implementation of envsubst were used to overcome this.
Fixes #125
> 🐛 Fix shell parameters expansion for CAPI deployment

- README.md
Adds a note regarding the v1alpha4 version of CAPM3 to readme
> 📖  Add v1alpha4 note to readme

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- VERSIONING.md
- hack/tools/release/notes.go
This PR changes the emoji used for the "Other" PR category to make it more inclusive
> 🌱 Opt for a more inclusive Other PR category

- config/bmo/kustomization.yaml
- config/bmo/secret_mount.yaml
- config/bmo/secrets.yaml
- config/default/namespace.yaml
- docs/getting-started.md
- hack/tools/install_kustomize.sh
This PR adds support for basic authentication towards Ironic and Ironic inspector.
Based on #133
> ✨ Add Support for Ironic Basic auth in deployment templates

- config/bmo/kustomization.yaml
- config/bmo/secret_mount.yaml
- config/default/namespace.yaml
- docs/getting-started.md
- hack/tools/install_kustomize.sh
This commit modifies the config folder to deploy BMO with a
custom CA cert to interact with Ironic. The CA cert must be
provided as a base64 encoded string without line wrap in
the IRONIC_CA_CERT_B64 environment variable for clusterctl
> ✨ Add support for TLS with custom CA certificate in BMO

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_test.go
​This PR waits for a BMH to be available and associated before creating the Metal3DataClaim. This ensures that the previous node
is properly deleted before giving an index to the new one (in case of scale-in upgrade).
> 🌱 Modify Metal3Machine association order

- examples/clusterctl-templates/example_variables.rc
Add missing TLS and Basic auth related vars which are required for the clusterctl deployment.
> TLS and Basic auth vars for capm3 v0.4.1 release

- Dockerfile
- Makefile
- Tiltfile
- go.mod
- hack/Dockerfile.unit
- hack/codegen.sh
- hack/ensure-go.sh
- hack/gofmt.sh
- hack/golint.sh
- hack/govet.sh
- hack/tools/go.mod
In order to avoid differences in go version across all repositories, this PR updates go to the latest in hack scripts.
> 🌱 Update golang to latest to match version across all repos

- docs/getting-started.md
- examples/clusterctl-templates/clusterctl-cluster.yaml
- examples/controlplane/controlplane.yaml
- examples/generate.sh
- examples/machinedeployment/machinedeployment.yaml
**What this PR does / why we need it**: This PR will add the nodeDrainTimeout configuration option in cluster, controlplane and worker example template. As to not affect existing deployments, made the default value to be `0s` and the user can override it with desired value.
> ✨ Add nodeDrainTimeout for example cluster template

- README.md
Report v1alpha4 CI job status instead of v1alpha3. We can keep watching v1alpha3 CI status from Metal3-dev-env.
> 🌱 Report v1a4 CI status in README

- baremetal/metal3machine_manager.go
Do not rely on the host's Available() method to decide when a host can
be selected for provisioning.
> :seedling: apply our own rules for host availability

- docs/getting-started.md
Fix typos in the getting-started instructions.
> 📖 Fix typos in docs

- api/v1alpha4/metal3datatemplate_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>
> Fix typo in comment

- Tiltfile
- tilt_modules/cert_manager/README.md
- tilt_modules/cert_manager/Tiltfile
- tilt_modules/extensions.json
Install cert-manager with extension instead of installing it ourselves. Related to https://github.com/kubernetes-sigs/cluster-api/issues/3765
Link to the extension: [cert-manager](https://github.com/tilt-dev/tilt-extensions/tree/master/cert_manager)
> 🌱 Install cert-manager with extension

- Dockerfile
- Tiltfile
- go.mod
- hack/Dockerfile.unit
- hack/codegen.sh
- hack/gofmt.sh
- hack/golint.sh
- hack/govet.sh
Bump the Golang version to [1.16](https://blog.golang.org/go1.16)
> 🌱 Bump the Golang version to 1.16

- Tiltfile
- controllers/suite_test.go
- hack/ensure-kind.sh
- hack/ensure-kubectl.sh
- hack/fetch_ext_bins.sh
Updates:
- kind version to [v0.9.0](https://github.com/kubernetes-sigs/kind/releases/tag/v0.9.0) to align with [CAPI](https://github.com/kubernetes-sigs/cluster-api/blob/master/hack/ensure-kind.sh)
- kubectl version to [v1.19.0](https://github.com/kubernetes/kubectl/releases/tag/v0.19.0) to align with [CAPI](https://github.com/kubernetes-sigs/cluster-api/blob/master/hack/ensure-kubectl.sh)
- k8s version to [1.19.2](https://github.com/kubernetes/kubernetes/releases/tag/v1.19.2) to align with [CAPI](https://github.com/kubernetes-sigs/cluster-api/blob/master/scripts/fetch_ext_bins.sh)
- CAPI version in Tiltfile
> 🌱 Update kind & kubectl & k8s & CAPI versions

- api/v1alpha3/metal3cluster_types.go
- api/v1alpha3/metal3machine_types.go
- api/v1alpha4/metal3cluster_types.go
- api/v1alpha4/metal3machine_types.go
- baremetal/metal3machine_manager.go
Replaces `fmt.Errorf()` with  `errors.Errorf()` for the sake of handling errors consistently.
> 🌱 Use errors.Errorf() instead of fmt.Errorf()

- api/v1alpha4/metal3datatemplate_webhook.go
Fixes typo in Metal3DataTemplate webhook error message
> 🐛 Fix error message in m3dt webhook

- Makefile
Make sure that even if someone clones cluster-api-provider-metal3 outside of `GOPATH` is running `make generate` generated files lands in the same place where `make generate` was executed.
This issue was started in CAPI issue: https://github.com/kubernetes-sigs/cluster-api/issues/4185 and was fixed in https://github.com/kubernetes-sigs/cluster-api/pull/4349. This PR is doing the same changes for CAPM3. 
Fixes #
> 🌱 Use explicit path for conversion-gen output

- docs/api.md
**What this PR does / why we need it**: fix an inaccuracy in the API documentation
Fixes #185
> 📖 fix name of vlanID field in API documentation

- hack/fetch_ext_bins.sh
1. bin is under kb_root_dir, not kb_root_dir/kubebuilder
2. Make full use of $kb_root_dir instead of specify /tmp/kubebuilder directly
Signed-off-by: Ma Xinjian <maxj.fnst@cn.fujitsu.com>
Fixes #
> Fix incorrect use of variable kb_root_dir

- api/v1alpha4/metal3data_types.go
- api/v1alpha4/metal3data_webhook.go
- api/v1alpha4/metal3datatemplate_types.go
- baremetal/metal3datatemplate_manager.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
> Add templateReference logic in Metal3DataTemplate

- hack/tools/install_kustomize.sh
Tests automatically install and use own copy of 'kustomize' binary. Current installation script  does this for linux only, even that all tests run properly on Mac OS too.
This change adds 'kustomize' binary installation also on Mac OS.
Tested: make test
> ✨  Install kustomize also in Mac OS.

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- controllers/metal3labelsync_controller.go
- controllers/metal3labelsync_controller_test.go
- main.go
Introduces a new controller in CAPM3 to synchronize a specific set of labels placed on a BMH with those on the corresponding Kubernetes Node running on that BMH.
Design Proposal: https://github.com/metal3-io/metal3-docs/pull/149
Example 1: Labels on BMH are added to the K Node
1. Add prefix annotation to Metal3Cluster:
```
kubectl annotate metal3cluster test1 metal3.io/metal3-label-sync-prefixes=my-prefix.metal3.io,foo.bar -n=metal3 --overwrite
```
2. Add labels to BareMetalHost:
```
kubectl label baremetalhosts node-0 my-prefix.metal3.io/rack=xyz-123 -n=metal3
kubectl label baremetalhosts node-0 foo.bar/xyz=abc -n=metal3
```
3. You should now see labels show up on the K Node:
```
kubectl get baremetalhosts --show-labels -n=metal3
kubectl get nodes --show-labels
```
Example 2: Label …
> ✨Adds a new controller to synchronize labels between BMHs and K Nodes

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
> 🐛 Fix bug that BMH NetworkData and MetaData cleaned on deprovisioning when they should not

- .gitignore
- Makefile
- examples/generate.sh
- examples/metal3plane/hosts.yaml
- examples/provider-components/image_versions_patch.yaml
- examples/provider-components/kustomization.yaml
- hack/ensure-kustomize.sh
- fixes the `examples/generate.sh` script to successfully generate example manifests. It also pins the versions of images used in example manifests to avoid breaking compatibility with the manifests.
- updates `ensure-kustomize.sh` to use an up-to-date URL for downloading kustomize
This allows generating examples and running `make deploy`, which is a step in a good direction. There is still an issue with `capm3-baremetal-operator-controller-manager` not receiving basic auth credentials, which will be addressed in a future PR.
I will squash the commits after review.
> 🌱 Fix example manifests generation

- config/rbac/role.yaml
- controllers/metal3machine_controller.go
There is a rbac issue with MachineSets while scaling up worker and Metal3MachineController logs outputs:
```
`E0518 07:49:42.976339       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.9/tools/cache/reflector.go:105: Failed to list *v1alpha3.MachineSet: machinesets.cluster.x-k8s.io is forbidden: User "system:serviceaccount:capm3-system:default" cannot list resource "machinesets" in API group "cluster.x-k8s.io" at the cluster scope
`
```
Fixes #
> 🌱 Add rbac rules for MachineSets 

- config/manager/manager_auth_proxy_patch.yaml
Taking in changes as CAPI release-0.3 https://github.com/kubernetes-sigs/cluster-api/pull/4639
> :seedling: Uplift kube-rbac-proxy to v0.8.0

- controllers/metal3labelsync_controller_test.go
Signed-off-by: Zou Yu <zouy.fnst@cn.fujitsu.com>
Fix gofmt warning: redundant type from array, slice, or map composite literal. 
I run the following command:
```sh
gofmt -s -w -d controllers/metal3labelsync_controller_test.go
```
Fixes #
> :seedling: Fix gofmt warning: redundant type from array, slice, or map composite literal

- docs/getting-started.md
Explain the deploy ramdisk in a cleaner way.
Use consistent spelling for Ironic (upper case).
> 📖 getting-started: clean up ironic bits

- config/bmo/secrets.yaml
This PR will remove the secret generation of ironic CA certificate in BMO and use the same CA certificate secret name generated by cert-manager in ironic deployment. This PR is needed to able to run the [PR#859](https://github.com/metal3-io/baremetal-operator/pull/859) in BMO.
> Remove secret generation of ironic CA cert in BMO.

- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
IPAM [v0.0.6 release](https://github.com/metal3-io/ip-address-manager/releases/tag/v0.0.6) is out, this patch updates go modules and configuration files accordingly in release-0.4 branch.
> 🌱 Update go mod and image patch kustomization for the IPAM

- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
IPAM [v0.0.6 release](https://github.com/metal3-io/ip-address-manager/releases/tag/v0.0.6) is out, this patch updates go modules and configuration files accordingly.
> 🌱 Update go modules and image patch kustomization for the IPAM 

- config/bmo/bmo_inject_ca_patch.yaml
- config/bmo/bmo_patch_cert_dns.yaml
- config/bmo/kustomization.yaml
This PR patches `inject-ca-from` annotations in baremetalhost crd and validatingwebhookconfiguration of baremetal operator and also certificate dnsNames. Currently this PR has no effect. But this is prerequisite for https://github.com/metal3-io/baremetal-operator/pull/865 to integration tests pass and bmo validating webhook works properly in capm3.
Problem is baremetal operator itself is running under `baremetal-operator-system` namespace and it renders certificates with `baremetal-operator-system/baremetal-operator-serving-cert`. However, capm3 runs baremetal operator under the `capm3-system` namespace and that's why, webhook in bmo can not find correct certificate to run.
> ✨ Add BMO inject-ca-from custom patching

- Makefile
- docs/e2e-test.md
- scripts/ci-e2e.sh
- templates/test/cluster-template-prow-ha.yaml
- templates/test/cluster-template-prow-single-master.yaml
- test/e2e/config/e2e_conf.yaml
Adds a Makefile target that calls e2e tests wrapper script. This gives more uniformity to the way we start tests.
> Define makefile target for running ci-e2e.sh

- Dockerfile
- hack/Dockerfile.unit
- hack/codegen.sh
- hack/gofmt.sh
- hack/golint.sh
- hack/govet.sh
- hack/markdownlint.sh
- hack/shellcheck.sh
The registry path for DockerHub https://registry.hub.docker.com/v2/ returns a 404. Docker/Podman make a GET request to this path before pulling the image, and they're failing at this step. Whether DockerHub have deprecated or changed the behaviour of their registry is unclear.
Updating the paths to docker.io resolves this issue and allows Docker image pulling once more.
> 🌱 Update DockerHub registry path

- api/v1alpha3/conversion.go
- api/v1alpha3/zz_generated.conversion.go
- api/v1alpha4/metal3machine_types.go
- baremetal/manager_factory.go
- baremetal/metal3machine_manager.go
- baremetal/metal3machinetemplate_manager.go
- baremetal/metal3machinetemplate_manager_test.go
- baremetal/mocks/zz_generated.manager_factory.go
- baremetal/utils_test.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
- controllers/metal3machinetemplate_controller.go
- docs/api.md
- main.go
Implementation of [disabling disk cleaning
](https://github.com/metal3-io/metal3-docs/blob/master/design/cluster-api-provider-metal3/allow_disabling_node_disk_cleaning.md)
> Allow disable automated cleaning

- test/e2e/e2e_suite_test.go
This PR fixes the issue that the e2e test framework uses a deprecated CAMP3 api version. 
Fixes #
> 🐛 Fix the CAMP3 api version in the e2e test framework

- test/e2e/config/e2e_conf.yaml
This PR makes the CAPI and CAPM3 versions defined in e2e config file the same with the version we use to setup the management cluster. 
Fixes #
> 🐛 Parameterize the CAPI and CAPM3 version in the e2e config file

- api/v1alpha4/metal3machine_types.go
- api/v1alpha4/zz_generated.conversion.go
- api/v1alpha5/metal3machine_types.go
- baremetal/manager_factory.go
- baremetal/metal3machine_manager.go
- baremetal/metal3machinetemplate_manager.go
- baremetal/metal3machinetemplate_manager_test.go
- baremetal/mocks/zz_generated.manager_factory.go
- baremetal/utils_test.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
- controllers/metal3machinetemplate_controller.go
- docs/api.md
- main.go
Backport [automated cleaning](https://github.com/metal3-io/cluster-api-provider-metal3/pull/156) feature to the master.
> ✨ Backport "Allow disable automated cleaning"

- config/bmo/secrets.yaml
In non-TLS scenario BMO is waiting for an empty secret which was removed earlier with cert manager setup in ironic.  Because of that the non-tls run was broken. This PR will add the empty secret creation and  during TLS-disabled, we will substitute the secret name as `empty-ironic-cacert` before kustomization.  The change of secret name will be done in [metal3-dev-env](https://github.com/metal3-io/metal3-dev-env/pull/720)
The changes fix the issue with non-TLS.
> 🌱Add generation of empty-ironic-cacert secret for handling TLS disabled scenario

- Makefile
- hack/e2e/environment.sh
- templates/test/cluster-template-prow-ha-centos.yaml
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_test.go
This PR makes the e2e tests pass on a CentOS host by adding a modified template file.
This PR builds on top of #218, so the diff is currently larger than just the relevant changes.
> 🌱 E2E tests CentOS support

- OWNERS
Drop @Jaakko-Os as he is no longer in Metal3 project. Thanks for your work @Jaakko-Os !
> 🌱 Drop Jaakko from the OWNERS list

- config/bmo/secrets.yaml
In non-TLS scenario BMO is waiting for an empty secret which was removed earlier with cert manager setup in ironic. Because of that the non-tls run was broken. This PR will add the empty secret creation and during TLS-disabled, we will substitute the secret name as empty-ironic-cacert before kustomization. The change of secret name will be done in [metal3-dev-env](https://github.com/metal3-io/metal3-dev-env/pull/720).
The changes fix the issue with non-TLS. This changes merged in [master](https://github.com/metal3-io/cluster-api-provider-metal3/pull/237) and needs to back port to the rlease-0.4.
> 🌱Add generation of empty-ironic-cacert secret for handling TLS disabled scenario(back port from master)

- main.go
Set the UserAgent to "cluster-api-provider-metal3-manager".
This string is used to identify actors within a Kubernetes system; for instance, it appears in managedFields.
Currently, it is set to "manager" (if not set, UserAgent defaults to the name of the binary).
ref: [kubernetes-sigs/cluster-api#4257](https://github.com/kubernetes-sigs/cluster-api/pull/4257). 
/hold until CAPI PR is merged.
Upd: new PR has been proposed as a follow up to 4257 which is [4750](https://github.com/kubernetes-sigs/cluster-api/pull/4750) and merged in CAPI master.
> 🌱 Set the UserAgent to "cluster-api-provider-metal3-manager"

- test/e2e/internal/log/log.go
This PR adds an internal log for the e2e tests. The reason is that we cannot use the [log](https://github.com/kubernetes-sigs/cluster-api/blob/test/v0.4.0/test/framework/internal/log/log.go) from the cluster-api e2e test framework before the package is [internal](https://pkg.go.dev/cmd/go#hdr-Internal_Directories).
> ✨ Add internal logging mechanism for e2e test framework

- config/ipam/image_patch.yaml
Currently, we have two branches to track in both CAPM3 and IPAM.
CAPM3 branches:
- **master** (for CAPI v1a4)
- **release-0.4** (for CAPI v1a3)
IPAM branches:
- **master** (for CAPI v1a4)
- **release-0.0** (for CAPI v1a3)
Currently, in both branches of CAPM3 we are pointing to use IPAM image with the tag of `0.0.6` which is a IPAM controller image used by CAPM3 v1a4/CAPI v1a3 and that needs to be changed, since we have CAPM3 and IPAM v1a4 changes in place.
> ⚠️  Update IPAM controller image reference

- test/e2e/config/e2e_conf.yaml
- test/e2e/data/shared/v1alpha4/metadata.yaml
This PR adds CAPI metadata.yaml to the e2e folder, so the [problem](https://pastebin.com/CKtTspda) with `clusterctl init` can be solved. This `metadata.yaml` differs from the one in the root directory. It documents the release series of cluster-api provider, so it is the file located in the root directory of cluster-api repo. 
```
failed to run clusterctl init
Unexpected error:
<*errors.withStack | 0xc001656870>: {
error: <*errors.withMessage | 0xc0008fb2e0>{
cause: <*errors.withStack | 0xc001656840>{
error: <*errors.withMessage | 0xc0008fb2c0>{
cause: <*fs.PathError | 0xc000b8a000>{
Op: "stat",
Path: "/home/****/tested_repo/_artifacts/repository/cluster-api/v0.4.0/metadata.yaml",
Err: <syscall.Errno>0x2,
},
msg: "failed to read file …
```
> 🐛 Add CAPI metadata.yaml to the e2e

- Makefile
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- docs/api.md
- docs/dev-setup.md
- examples/cluster/cluster.yaml
- examples/cluster/kustomizeconfig.yaml
- examples/clusterctl-templates/clusterctl-cluster.yaml
- examples/controlplane/controlplane.yaml
- examples/controlplane/kustomizeconfig.yaml
- examples/generate.sh
- examples/machinedeployment/kustomizeconfig.yaml
- examples/machinedeployment/machinedeployment.yaml
- examples/metal3plane/hosts.yaml
- examples/provider-components/image_versions_patch.yaml
- go.sum
This is on top of #167, and will be rebased once 167 is merged. Updates examples/docs folders accordingly to CAPI v1a4 uplift.  
This PR makes sure to run example generation files properly and also updates documentation accordingly to be compatible with the latest CAPI v1a4 API version. 
Upd: rebased on top of 167. 
**Note:** For example generation  changes this PR expects and assumes that we will have a new release of IPAM from the **master** branch that is compatible with CAPI v1a4. This was tested with [ipam-components.yaml](https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/config/ipam/kustomization.yaml#L6) build manually out of IPAM master branch since it is as is pointing to v0.6.0 yaml which is the IPAM release that is not …
> ✨Update example generation and docs with latest CAPI v1a4 changes

- examples/metal3crds/metal3.io_baremetalhosts.yaml
I accidentally noticed that in some places we still rely on soon deprecated API versions of CRD. Don't use v1beta1 APIs of CRD which is going to be deprecated in the next release 1.22 of Kubernetes.
> 🌱 Don't use v1beta1 APIs of CRD

- templates/test/cluster-template-prow-ha-centos.yaml
This PRs fixes an issue in the Centos cluster template. This issue leads to a networking problem in the Centos target nodes. |The ptoblem is that the `ironicendpoint` bridge doesn't have IP address although it should have it.
> 🐛 Fix the cloud-init in the centos template

- docs/releasing.md
Add a step explaining how to create BMO & Ironic container images with a specific tag whenever making  a new release of CAPM3.
> 📖 Extend releasing document

- api/v1alpha5/metal3cluster_webhook.go
- api/v1alpha5/metal3data_webhook.go
- api/v1alpha5/metal3dataclaim_webhook.go
- api/v1alpha5/metal3datatemplate_webhook.go
- api/v1alpha5/metal3machine_webhook.go
- api/v1alpha5/metal3machinetemplate_webhook.go
- config/webhook/manifests.yaml
Webhook registration should accept both v1 and v1beta1 admissions
Admission Review was previously set to only accept v1beta1 objects given
that Controller Runtime didn't support v1 (even though the two revisions
are effectively the same). This change adds support for both within our
manifests.
equivalent of [kubernetes-sigs/cluster-api#4942](https://github.com/kubernetes-sigs/cluster-api/pull/4942)
> 🐛 Webhook reg should accept both v1 and v1beta1 admissions

- main.go
Currently the readiness of our controller deployments does not include the webhook server. I.e., the deployment is already ready even when the webhooks are not up.
The current PR will help that the wait for readiness will also include the webhook server. This is crucial because otherwise there's a chance that clusterctl immediately fails when we try to deploy resources.
Follows: https://github.com/kubernetes-sigs/cluster-api/pull/4989
> ✨ Add webhook readiness and health check

- go.mod
- go.sum
- test/e2e/common.go
- test/e2e/e2e_test.go
- test/e2e/pivoting_test.go
- test/e2e/yaml.go
This PR Does the following things:
- Fix the issue calico issue in the target cluster of e2e tests. It downloads the calico manifests, then update the yaml file. 
- Print out the log of some shell commands running in e2e tests.
- In pivoting test, run `clusterctl init` before installing BMO because now this installation requires to have cert-manager.
> Fix e2e calico configuration and BMO installation workflow

- baremetal/metal3machinetemplate_manager.go
seeing this in the log:
```
I0817 06:27:09.282274       1 metal3machinetemplate_manager.go:96] controllers/Metal3MachineTemplate/Metal3MachineTemplate-controller "msg"="Synchronized automatedCleaningMode field value between Metal3MachineTemplate %v/%v and Metal3MachineMachine %v/%v" "metal3-machine-template"={"Namespace":"metal3","Name":"test1-workers"} "metal3"="test1-workers-4wtsr"
```
Fixes #
> 🐛 Fix Metal3MachineTemplate log output

- test/e2e/common.go
- test/e2e/pivoting_test.go
This PR fixes the issue with the e2e pivoting test which is the same as the PR on m3-dev-env: https://github.com/metal3-io/metal3-dev-env/pull/765
> Restore the BMO config map and add more logs to the e2e pivoting test

- test/e2e/pivoting_test.go
This PR fixes the problem that "scale in" operation does not work after e2e pivoting on Ubuntu. The problem is that the keepalived container is deleted forcefully, so it does not have time to clean the ironicendpoint IP address on the host. This leftover makes target nodes confuse and cannot connect to ironic.
> 🐛 Fix the problem that "scale in" operation does not work after e2e pivoting

- test/e2e/common.go
- test/e2e/pivoting_test.go
We are now targeting go1.16. Starting with this release, the ioutils
package is now deprecated [0]. This updates usage of ioutils calls for
the new recommended io and os equivalents.
[0] [doc/go1.16#ioutil](https://golang.org/doc/go1.16#ioutil)
> 🌱 Remove deprecated ioutil usage

- docs/architecture.md
some of the existing doc output is incorrect per test result
Fixes #
> 📖update architecture doc per current output

- api/v1alpha5/metal3cluster_types.go
- api/v1alpha5/metal3data_types.go
- api/v1alpha5/metal3dataclaim_types.go
- api/v1alpha5/metal3datatemplate_types.go
- api/v1alpha5/metal3machine_types.go
- api/v1alpha5/metal3machinetemplate_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
This adds the AGE column to all our CRDs to make the printed output consistent with the built in K8s resources.
Keeping things consistent with CAPI# https://github.com/kubernetes-sigs/cluster-api/pull/5180
> ✨ Add AGE column to metal3 CRDs

- templates/test/cluster-template-prow-ha-centos.yaml
- templates/test/cluster-template-prow-ha.yaml
- test/e2e/e2e_test.go
Fixes e2e tests by:
- removing unnecessary `RunAsGroup=true` field to keep up a consistency with m3-dev-env templates
- adding a workaround for nameprefix issue in IPAM kustomization
> Fix e2e tests

- Makefile
- examples/generate.sh
- examples/metal3crds/metal3.io_baremetalhosts.yaml
- hack/tools/go.mod
- hack/tools/go.sum
This PR removes run make target from Makefile since after the uplift to v1alpha5 version, it is not feasible to run go code only anymore. For local development and testing, Tilt is recommended instead.
This PR also updates the BMH CRDs to keep it up to date.
This PR also uplifts the envsubst module in tools.
> ✨ Remove 'run' make target

- hack/e2e/environment.sh
This PR exposes the NUM_NODES, which is the number of baremetal nodes, so we can set this number up from outside (JJB script)
> Expose the parameter of libvirt VM number used by e2e tests

- config/default/capm3/kustomization.yaml
- config/default/kustomization.yaml
Adding `capm3-` prefix in root kustomize adds `capm3- `prefix on ipam objects as well. This created issue in IPAM kustomization since the cert-mnanager/ca-inject-from annotation doesn't get updated. This PR only keeps `capm3-` prefix for capm3 objects.
> 🐛 Remove capm3- prefix from root kustomize

- Tiltfile
- hack/gen_tilt_settings.sh
- tilt_modules/cert_manager/Tiltfile
Update tilt configuration
This PR updates versions of the capi, cert manager and kubernetes components. It also updates path of manifests
> Update tilt configuration

- test/e2e/e2e_test.go
- test/e2e/pivoting_test.go
Recently, the container ironic-inspector-log-watch has been removed from BMO in https://github.com/metal3-io/baremetal-operator/pull/945. This cause an error for the e2e test. This PR aims to fix it by removing this container so the e2e test would no longer try to stop it.
> Delete the container Ironic-inspector-watch-log from the e2e test 

- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
New IPAM [v0.1.1](https://github.com/metal3-io/ip-address-manager/releases/tag/v0.1.1) release is out. Updates controller image/ipam-components ref.
> 🌱 Update IPAM reference

- hack/e2e/environment.sh
- scripts/ci-e2e.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/pivoting_test.go
Currently, with e2e tests, the source cluster infrastructure components are initialized by the file made by m3-dev-env, while the target cluster uses the file that is built by the test framework itself. This causes a mismatch between the source and the target cluster.
This PR makes the e2e test framework use the infrastructure components issued by m3-dev-env, leading to the consistency between the source and target clusters.
Note: By default, m3-dev-env clones CAPM3 repo from upstream and build the infrastructure components from here. This behavior is not what we want in an e2e test because the components should be built from the local CAPM3 repo when the test is executed. Therefore, this PR switches the toggle that prevents m3-dev-env to clone repos. The test framework would copy the …
> 🐛 Use the infrastructure components built by m3-dev-env

- .github/workflows/release.yaml
This patch ensures that we fetch all history for all tags
and branches when checking out with GitHub actions.
> 🌱 Allow fetching repo tags when checking in GitHub Actions

- .github/workflows/release.yaml
- Makefile
We need to make sure that we checkout to the correct branch/tag
before we go to release, because otherwise we use wrong tag
version as the prior one.
> 🐛 Fix bug with missing checkout to a tag during releasing

- go.mod
- go.sum
- hack/e2e/environment.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_test.go
- test/e2e/node_reuse_test.go
Adds e2e node_reuse test and replaces [Ansible feature test](https://github.com/metal3-io/metal3-dev-env/blob/master/vm-setup/roles/v1aX_integration_test/tasks/node_reuse.yml)
> :seedling: e2e node_reuse test

- hack/e2e/environment.sh
- scripts/ci-e2e.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_test.go
This PR allows the e2e tests to apply the cluster template from metal3-dev-env.
> 🌱Add an option to choose the cluster template from metal3-dev-env

- Makefile
Separate bmh crd and crs deployment in Tilt environment.
The crds are required for metal3-dev-env deployment tilt setup. However, the bmh crs can be deployed later.
> Separate bmh crd and crs deployment in Tilt environment

- metadata.yaml
✨ Bump clusterctl metadata to v1beta1
**What this PR does / why we need it**: For v1beta1 support, we should bump our metadata to v1beta1
> ✨ Bump clusterctl metadata to v1beta1

- go.mod
- go.sum
- test/e2e/node_reuse_test.go
The `k8s.io/kubernetes v1.13.0` import results in following security vulnerability 
https://github.com/advisories/GHSA-f5f7-6478-qm6p
https://github.com/advisories/GHSA-vw47-mr44-3jf9
https://github.com/advisories/GHSA-74j8-88mm-7496
This PR intends to remove the import
> Remove vulnerable import k8s.io/kubernetes v1.13.0 

- go.mod
- go.sum
- test/e2e/node_reuse_test.go
This change refactors node_reuse tainting workflow to remove vulnerable import k8s.io/kubernetes v1.13.0
The `k8s.io/kubernetes v1.13.0` import results in following security vulnerability 
https://github.com/advisories/GHSA-f5f7-6478-qm6p
https://github.com/advisories/GHSA-vw47-mr44-3jf9
https://github.com/advisories/GHSA-74j8-88mm-7496
This PR intends to remove the import
> 🐛 Remove vulnerable import k8s.io/kubernetes v1.13.0

- api/v1beta1/common_types.go
- api/v1beta1/metal3cluster_types.go
- api/v1beta1/metal3data_types.go
- api/v1beta1/metal3dataclaim_types.go
- api/v1beta1/metal3datatemplate_types.go
- api/v1beta1/metal3machine_types.go
- api/v1beta1/metal3machinetemplate_types.go
- api/v1beta1/metal3remediation_types.go
- api/v1beta1/metal3remediationtemplate_types.go
This PR will add missing `optional` tag to `omitempty` fields for v1beta1 types and it follows  [CAPI PR](https://github.com/kubernetes-sigs/cluster-api/pull/5301)
Fixes: #320
> 🌱 Audit v1beta1 APIs to follow CAPI conventions

- test/e2e/config/e2e_conf.yaml
This PR updates left out e2e conf file to refer to latest infrastructure provider API version which will be used later in remediation e2e test.
> 🐛 Use proper infrastructure var in e2e conf

- api/v1beta1/metal3cluster_types.go
- api/v1beta1/metal3data_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
This PR will remove remove `omitempty` field and add `optional` tag to some status fields in v1beta1 types. It follows [CAPI PR](https://github.com/kubernetes-sigs/cluster-api/pull/5305). 
PR can be merged after #361 gets in.
> 🌱 Remove omitempty fields and add optional tag to some status fields in v1beta1 types.

- api/v1alpha4/metal3cluster_types.go
- api/v1alpha5/metal3cluster_types.go
- api/v1beta1/metal3cluster_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
Add description for NoCloudProvider
The description is visible with kubectl explain m3mcluster.spec.NoCloudProvider
> 🌱 Add description to m3cluster NoCloudProvider boolean field

- go.mod
- go.sum
Couldn't uplift capi/test to v1.0.1 in #381 since CAPI folks missed test/v1.0.1 tag in the release somehow and now they have added it.
> ✨ Uplift sigs.k8s.io/cluster-api/test to v1.0.1

- .gitignore
- Makefile
- hack/fetch_ext_bins.sh
- hack/tools/install_kubebuilder.sh
- hack/unit.sh
We have been seeing quite many flakiness in the unit test scripts. 
This is a first set of patches that will be trying to fix that flakiness.
1. When running make generate, some of the autogenerated code ends up
in github/ dir, which should be outside of staging area. This patch
adds github/ dir to .gitignore, so that we don't accidentally submit
a PR with those changes included.
2. Current `install_kubebuilder.sh` script downloads a tarball containing
other binaries apart from kubebuilder, such as etcd, kube-apiserver
and kubectl. We use kubebuilder binary only when running make generate
target, meaning there is no need to set up a test k8s env with those
binaries. Those are only needed to setup a fake k8s env while unit
testing, via make unit/test …
> 🌱 Refactor test scripts

- config/default/capm3/manager_image_patch.yaml
Current manager manifest is pointing to the container image with main tag
which is meant for main branch and introduces some breaking changes.
> 🐛 Use v0.5.x tag for manager image in release-0.5 images

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- baremetal/utils.go
- baremetal/utils_test.go
- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_integration_test.go
- controllers/metal3machine_controller_test.go
Use providerID and providerLabel prefixes
This PR parameterizes the providerID and providerID labels with `metal3://` and `metal3.io/uuid` respectively.
This is required in order to change the providerID generation logic.
> 🌱Use providerID and providerLabel prefixes

- baremetal/metal3machine_manager_test.go
- controllers/metal3machine_controller_integration_test.go
- controllers/metal3machine_controller_test.go
- controllers/suite_test.go
The providerID generation is changing by https://github.com/metal3-io/cluster-api-provider-metal3/pull/324. 
Tests also need to change. However, providerID and related objects ids are scattered throughout the tests.
This PR centralizes definition of providerID related objects. This is required before modifying existing providerID related tests.
> 🌱 parameterize providerID parts in tests

- go.mod
- go.sum
Uplift containerd to v1.5.8 to get rid of the following vulnerability
https://github.com/advisories/GHSA-5j5w-g665-5m35
> 🐛 Uplift github.com/containerd/containerd v1.5.8

- Makefile
We have had a release with infrastructure-components.yaml not updated
to point to the release tag image of CAPM3. `MANIFEST_IMG` ensures
to patch the infrastructure-components.yaml before publishing the release
artifacts.
Once merged, we need to backport this change to release-0.5 branch as well.
> 🌱 Ensure setting image tag for current release in infra components

- docs/remediation-controller.md
This PR adds` CAPI MachineHealthCheck` and` CAPM3 Remediation Controller` based health-check and remediation documentation to CAPM3 docs.
> 📖  Add Remediation Controller documentations to CAPM3

- test/e2e/config/e2e_conf.yaml
This PR aims to fix this issue: https://jenkins.nordix.org/view/Metal3/job/airship_master_e2e_v1b1_test_centos/10/console
Currently, when the CAPI e2e  framework checks the present of the cluster, it assumes that KCP is ready at the same time when the cluster object is ready. However, it may be not true because of the uncertainty of the underlying infra.
This PR makes the interval between two checks for the cluster present wider. The goal is when the cluster is checked and determined as "ready", the kcp object also has time to be ready.
> Fix the kcp issue in e2e test

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
This PR addresses handling of some corner cases in node reuse feature, such as:
- avoids cluster deletion problem while testing stack of e2e tests that are run consequitevily by adding a DeletionTimestamp.IsZero() check just before going deep into node reuse logic to avoid fetching non existing resources if any requested while cluster deletion;
- handles m3data re-queuing in cases when machine is deleted during in place upgrade and new machine is immediately failing to get the Metal3Metadata thus breaking the in place upgrade case and also adds needed unit tests.
- improves logging in node reuse
**Note:** These changes were tested using e2e framework tests in #390 and feature tests in [metal3-dev-env/pull/855](https://github.com/metal3-io/metal3-dev- …
> ✨ Rework node reuse logic to handle corner cases

- test/e2e/cert_rotation_test.go
- test/e2e/common.go
- test/e2e/node_reuse_test.go
- test/e2e/pivoting_test.go
- test/e2e/remediation_test.go
This patch fixes the issue in node reuse testing workflow in e2e where:
- after testing KCP node reuse use case, we do scale down KCP to 1 and and it triggers de provisioning of BMHs to start testing MD use case, thus all BMH that were used before would have node reuse labels on them. So while testing MD case, we do not remove them and it will always chooses the same host since other BMHs have already KCP name set in node reuse label. To fix it, we remove old labels from all BMHs and then test MD use case to check if node reuse feature is working.  
- also removing marking/unmarking of BMHs with unhealthy annotation, since now when MD maxSurge field is updated with `0` it deletes the existing machine first and then recreates a new one, resulting in …
> 🐛  Fix node reuse test workflow in E2E

- test/e2e/cert_rotation_test.go
- test/e2e/common.go
- test/e2e/e2e_test.go
- test/e2e/node_reuse_test.go
- test/e2e/pivoting_test.go
- test/e2e/remediation_test.go
This patch fixes the issue in node reuse testing workflow in e2e tests of release-0.5 branch where:
- after testing KCP node reuse use case, we do scale down KCP to 1 and and it triggers de provisioning of BMHs to start testing MD use case, thus all BMH that were used before would have node reuse labels on them. So while testing MD case, we do not remove them and it will always chooses the same host since other BMHs have already KCP name set in node reuse label. To fix it, we remove old labels from all BMHs and then test MD use case to check if node reuse feature is working.  
- also removing marking/unmarking of BMHs with unhealthy annotation, since now when MD maxSurge field is updated with `0` it deletes the existing machine first and then …
> 🐛Fix node reuse workflow in E2E in release-0.5 branch

- test/e2e/remediation_test.go
This PR fixes this issue: 
```bash
• Failure [1432.664 seconds]                                                                                                                                                                           
Workload cluster creation                                                                                                                                                                              
/home/slintes/cluster-api-provider-metal3/test/e2e/e2e_test.go:34                                                                                                                                      
Creating a highly available control-plane cluster …
```
> 🐛 Remove unnecessary and buggy step in e2e remediation test

- baremetal/metal3machinetemplate_manager.go
Due to this bug,  `automatedCleaning` will not be synchronized between
metal3MachineTemplate and metal3Machine when set. Because we are
verifying it from the metal3Machine which should be the metal3MachineTemplate.
> 🐛 Automated cleaning bug fix in machine template controller

- controllers/metal3remediation_controller.go
- controllers/metal3remediation_controller_test.go
Some unit tests for the `reconcileNormal` function on the remediation controller to try and describe what the expected behavior is.
**What this PR does / why we need it**: Ensures that the logic in the remediation controller is adequately covered by tests.
> 🌱 Add unit tests for remediation controller

- config/rbac/leader_election_role.yaml
- main.go
Controller runtime sets by default leader-election-resource-lock to ConfigMapsLeasesResourceLock since v0.7 so consumers can do smooth transitions: https://github.com/kubernetes-sigs/controller-runtime/blob/1730628f118be1128787012c164379e6ac46c75f/pkg/manager/manager.go#L143-L156
Configmap updates to keep the lease alive result in large memory hits for any component that caches/syncs configmaps, particularly the apiserver. Furthermore, it requires additional rbac for controllers. This PR defaults our controller to leases and
should mitigate overwhelming the apiserver in a large management cluster and avoid additional rbac.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the …
> ⚠️ Default LeaderElectionResourceLock to leases

- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_test.go
- test/e2e/upgrade_ironic_test.go
Adds ironic upgrade test into release-0.5 branch
Backport of #336
> ✨Add E2E upgrade ironic test to release-0.5 branch

- hack/unit.sh
Use `docker.io/golang:1.16`  container image for unit.sh script.
We don't necessarily need to create & use `quay.io/metal3-io/capm3-unit`
image, because the only thing this image has is kustomize and
kubebuilder installed via below RUN, which is redundant as those
binaries will be installed during `unit` Makefile target ( as part of
`setup_envs`). At the end, we currently install kubebuilder and
kustomize twice. 
```
RUN ./install_kustomize.sh && \
./install_kubebuilder.sh
```
There will be a follow PR to this, which will remove the
Dockerfile, and update the project-infra respectively to migrate
fully to golang images.
> 🌱 Use golang image as base for unit test containers

- hack/Dockerfile.unit
Drop building capm3:unit image and instead use golang container
image for go tests in Prow. The reason for dropping this image
support is,  it has no benefit anymore but instead it brings extra
things like kubebuilder and kustomize which are not needed to be
build by shell scripts anymore because we donwload those bins via
setup_env Makefile target. This should be merged after the update
in the project-infra repo.
/hold
/cc @furkatgofurov7 @kashifest
> 🌱 Drop capm3:unit container image Dockerfile

- hack/unit.sh
Backport of https://github.com/metal3-io/cluster-api-provider-metal3/pull/441 into release-0.4 branch
> 🌱Use golang image as base for unit test containers

- test/e2e/config/e2e_conf.yaml
- test/e2e/pivoting_test.go
- test/e2e/upgrade_ironic_test.go
Tackles 2 issues:
1. after uplifting to capi  v1.1.0-beta.1 pre-release, pivoting e2e tests started failing during initializing provider components in target cluster, with not being able to fetch releases tagged with a valid semantic version. And that is fixed by pointing to overrides folder during pivoting tests now;
2. backports  https://github.com/metal3-io/cluster-api-provider-metal3/commit/efe3e356afa1183da401fe774d43f751db444e44 which fixes failing mariadb container upgrade in main branch.
> ✨ Fix clusterctl init issue and failing upgrade ironic containers tests in E2E

- Tiltfile
- tilt-provider.json
Update tilt-provider.json to add CAPM3 label in Tilt UX. This [grouping feature](https://blog.tilt.dev/2021/08/09/resource-grouping.html) is supported in tilt version >= v0.22.2.
This patch provides two different grouping strategies:
- by controllers
- and local binaries
See [CAPI](https://github.com/kubernetes-sigs/cluster-api/pull/5217) PR for grouping resources in Tilt.
Also, the corresponding controller and binary will be grouped under 'CAPM3' group label as shown in the local Tilt setup using BMO,CAPM3&IPAM controllers.
Related patches in: [IPAM](https://github.com/metal3-io/ip-address-manager/pull/83)&[BMO](https://github.com/metal3-io/baremetal-operator/pull/1061).
/hold needs local testing
> ✨ Use grouping feature of Tilt to add CAPM3 label

- test/e2e/remediation_test.go
To be fully compliant in e2e tests with respect to the efforts on https://github.com/metal3-io/baremetal-operator/pull/340
> 🐛Rename unused BMH state mentions in e2e tests

- go.mod
- go.sum
Fixes GHSA-mvff-h3cj-wj9c and also keeps up with https://github.com/kubernetes-sigs/cluster-api/pull/5886
> 🐛  Uplift containerd to v1.5.9 and docker to v20.10.11

- test/e2e/common.go
- test/e2e/node_reuse_test.go
- test/e2e/remediation_test.go
Some global variables were defined in the *_test.go files but referenced in "normal" files. This is causing compilation errors since *_test.go files are not included in a normal build (only in go test).
> 🐛 Fix compilation issues in e2e tests

- hack/e2e/environment.sh
- test/e2e/e2e_suite_test.go
This PR pins the calico version used ine2e test to v3.21.0 which is the same as the default calico version in Metal3-dev-env. Pinning calico version helps to avoid the docker rate limit issue because in CI this calico version is baked into the node image.
> ✨ Pin calico version to v3.21.0

- hack/e2e/environment.sh
- test/e2e/e2e_suite_test.go
Cherry picked from commit 6803d334f1b83a95f5c28f7d964e0961e37b2af1
>  ✨ Pin calico version to v3.21.0 in release-0.5 branch

- test/e2e/config/e2e_conf.yaml
- test/e2e/inspection_test.go
- test/e2e/node_reuse_test.go
- test/e2e/remediation_test.go
[Feature tests in m3-dev-env](https://github.com/metal3-io/metal3-dev-env/blob/master/Makefile#L57) contain re-inspection API tests from BMO and e2e misses that test for now. So:
- This adds missing re-inspection API e2e tests to the framework and is called during the remediation tests instead of being called from e2e_test.go separately to save time and not prolong e2e tests running time. To call it separately, we had to do scale up/down operations, since inspection can be tested only with "Available" BMHs'.
More about re-inspection API: https://github.com/metal3-io/baremetal-operator/blob/main/docs/inspectAnnotation.md
>  ✨ Add re-inspection API tests to E2E

- test/e2e/config/e2e_conf.yaml
- test/e2e/inspection_test.go
- test/e2e/node_reuse_test.go
- test/e2e/remediation_test.go
[Feature tests in m3-dev-env](https://github.com/metal3-io/metal3-dev-env/blob/master/Makefile#L57) contain re-inspection API tests from BMO and e2e in release-0.5 branch misses that test for now. So:
- This adds missing re-inspection API e2e tests to the framework in the `release-0.5` branch of CAPM3 and is called during the remediation tests instead of being called from e2e_test.go separately to save time and not prolong e2e tests running time. To call it separately, we had to do scale up/down operations, since inspection can be tested only with "Available" BMHs'.
More about re-inspection API: https://github.com/metal3-io/baremetal-operator/blob/main/docs/inspectAnnotation.md
Backport of https://github.com/metal3-io/cluster-api-provider-metal3/pull …
> ✨ Add re-inspection API tests to E2E in release-0.5 branch

- controllers/metal3machinetemplate_controller.go
This PR renames soon deprecated (original PR in upstream CAPI has been labeled with v1.1 milestone) `HasPausedAnnotation`
function to `HasPaused`
https://github.com/kubernetes-sigs/cluster-api/blob/release-1.1/docs/book/src/developer/providers/v1.0-to-v1.1.md#deprecation
/hold
Original issue in CAPI: https://github.com/kubernetes-sigs/cluster-api/issues/5539
> ⚠️ Rename HasPausedAnnotation function to HasPaused

- test/e2e/pivoting_test.go
After merging [https://github.com/metal3-io/baremetal-operator/pull/1065](https://github.com/metal3-io/baremetal-operator/pull/1065) some tests are broken in pivoting because they cannot find `ironic-api `, ` ironic-conductor`& `mariadb`.
This PR replaces these containers by the all-in-one `ironic` container.
> Replace ironic containers by the all-in-one

- baremetal/manager_factory_test.go
- baremetal/metal3cluster_manager_test.go
- baremetal/metal3data_manager_test.go
- baremetal/metal3datatemplate_manager_test.go
- baremetal/metal3machine_manager_test.go
- baremetal/metal3machinetemplate_manager_test.go
- baremetal/metal3remediation_manager_test.go
- baremetal/utils_test.go
- controllers/metal3cluster_controller_integration_test.go
- controllers/metal3data_controller_test.go
- controllers/metal3datatemplate_controller_test.go
- controllers/metal3labelsync_controller_test.go
- controllers/metal3machine_controller_integration_test.go
- controllers/metal3machine_controller_test.go
- controllers/metal3machinetemplate_controller_test.go
- controllers/metal3remediation_controller_test.go
This commit removes:
- unnecessary 'fakeclient' import alias
- unnecessary variable declarations
This commit also replaces the previously used variable name 'c'
with the 'fakeClient' name as it is more descriptive and it is also
used in CAPI.
This commit also breaks up some long lines in order to make them more
readable.
> :seedling: Standardize controller & baremetal unit test syntax

- test/e2e/e2e_suite_test.go
This PR adds LogFolder Parameter in e2e for collecting kind logs. Please see https://github.com/kubernetes-sigs/cluster-api/pull/5910/ for reference.
> ✨ Add LogFolder parameter in e2e for collecting kind logs

- test/e2e/common.go
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_test.go
- test/e2e/upgrade_baremetal_operator_test.go
- test/e2e/upgrade_ironic_test.go
Adds a simple BMO upgrade e2e test.
This test is very similar to the ironic upgrade test. So far they do not
really upgrade from an older version to the latest. Instead they upgrade
from no tag (latest) to main. So we at least see that it is possible to
rollout an upgrade.
The idea is to later make the tests start from an older release and upgrade to the latest.
> ✨ Add BMO upgrade e2e test

- README.md
- test/e2e/node_reuse_test.go
Airship name from CI jenkins view have been deprecated
> ✨ Update CI badges and artifactory image path with metal3

- go.mod
- go.sum
Uplifts BMO in go modules and also adds github.com/metal3-io/baremetal-operator/pkg/hardwareutils to it since now hardwareutils is the basic module and BMO apis uses it. We could consider adding hardwareutils in apis module with the commit tag in the future.
> ✨ Uplift BMO module in go.mod

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- controllers/metal3machine_controller_integration_test.go
- main.go
This PR adds:
- Capm3FastTrack variable and sets it as default to false 
- A possibility where  bmh.Spec.Online field is changed to on/off during deprovisioning based on values of     
AutomatedCleaningMode and Capm3FastTrack
```
AutomatedCleaningMode   | Capm3FastTrack |   BMH
disabled           false            turn off
disabled           true             turn off
metadata           false            turn off
metadata           true             turn on
```
>  ✨ Allow Capm3 Fast Track in bmh when AutomatedCleaning is enabled

- hack/e2e/environment.sh
Since IMAGE_OS changed to lowercase in Dev_Env in this [PR](https://github.com/metal3-io/metal3-dev-env/pull/948), updates in capm3 hack file are need else it will break the test locally.
> 🐛 Fix IMAGE_OS case

- api/v1alpha5/common_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
This PR will add the live-iso option for v1a5 in release-0.5 branch and changes are done according to main branch https://github.com/metal3-io/cluster-api-provider-metal3/pull/527
> 🐛Cherrypick live-iso option to Image's DiskFormat for v1a5 in release-0.5

- api/v1alpha5/common_types.go
- api/v1beta1/common_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
The image.format option of 'live-iso' was available in the v1alpha4 API but had gone missing in the v1alpha5 and v1beta1 APIs.
**What this PR does / why we need it**: The live-iso option for the disk format of images for Metal3Machines was supported in v1alpha4 and should be supported in v1alpha5 and v1beta1.
Fixes #500
Also, this commit may need cherry-picking into release branches, I'm not sure exactly which branches would need this fix.
> 🐛 Add live-iso option to Image's DiskFormat in v1a5 and v1b1

- .github/workflows/release.yaml
Allow GA releases to trigger on v* tags. Currently it doesn't allow to trigger the
GA action on tags starting with any number except `v0.`
> 🌱 Allow GA releases to trigger on v* tags

- controllers/metal3machinetemplate_controller.go
Normally, automated cleaning mode (either disabled or
metadata) is replicated from a Metal3MachineTemplate spec
to Metal3Machine spec. It is allowed to patch Metal3Machine's
automtedCleaningMode directly, and if that's the case CAPM3
controller should notice is, request a reconciliation for the
Metal3MachineTemplate and reset the automatedCleaningMode on
the Metal3Machine to the same as in Metal3MachineTemplate.
This ensures that the source of the truth is always in the
template.
> 🐛 Reconcile Metal3MachineTemplate on Metal3Machine events

- go.mod
- go.sum
- test/e2e/config/e2e_conf.yaml
Aligns e2e test modules with CAPI release version in go modules, since we missed to uplift e2e test modules while uplifting CAPI to v1.1.2. Also updates e2e config file to use the v.1.1.2 release version of CAPI providers.
> 🌱 Uplift e2e test module to v1.1.2 in go mod and e2e conf file 

- api/v1beta1/metal3machine_types.go
- baremetal/metal3machinetemplate_manager_test.go
- controllers/metal3machinetemplate_controller.go
- controllers/metal3machinetemplate_controller_test.go
Adds unit tests to the `Metal3MachinesToMetal3MachineTemplate` reconciliation request func.
> 🌱 Add unit tests for metal3MachineTemplate reconciliation

- README.md
For the kustomize command to succeed the namespace baremetal-operator-system
must already exist in the kubernetes cluster.
Adds a command to create the target namespace (please see step 2 in https://github.com/metal3-io/baremetal-operator/blob/main/docs/dev-setup.md). Otherwise the kustomize command will fail.
> :book: Add creation of BMO namespace in root README instructions

- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
- baremetal/suite_test.go
Add providerid field metadata.
The metadata has landed on the disk on the provisioned contorlplane node, as shown below.
This PR does not affect the current workflow as it just adds a new field  to the metadata.
Subsequent PRs will make use of this PR.
```
[metal3@test1-qjhht ~]$ head /var/run/cloud-init/instance-data.json  -n 17
{
"base64_encoded_keys": [],
"ds": {
"_doc": "EXPERIMENTAL: The structure and format of content scoped under the 'ds' key may change in subsequent releases of cloud-init.",
"ec2_metadata": {},
"meta_data": {
"instance-id": "4517acf8-d6fe-4afb-8bbb-a6de84a8d515",
"local-hostname": "test1-qjhht",
"local_hostname": "test1-qjhht",
"metal3-name": "node-2",
"metal3-namespace": "metal3",
"name": "test1-qjhht",
"providerid": …
```
> Add providerid field metadata

- docs/api.md
- docs/getting-started.md
- examples/clusterctl-templates/example_variables.rc
- test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/centos-kubeadm-config.yaml
- test/e2e/data/infrastructure-metal3/bases/ubuntu-kubeadm-config/ubuntu-kubeadm-config.yaml
The .kube directory must belong to the (non-root) user issuing kubectl.
Otherwise kubectl will not be able to cache requests and will issue warnings
due to client-side throttling taking place when requests normally hitting the
cache are directed at the server instead.
fix related to issue: https://github.com/metal3-io/metal3-dev-env/issues/957
Fixes example setup templates which lead to kubectl not being able to cache requests correctly. It then issues warnings about client-side-throttling. See https://github.com/metal3-io/metal3-dev-env/issues/957 for more details.
> :seedling: Allow kubectl caching after cluster creation

- baremetal/metal3machine_manager.go
The `GetProviderIDAndBMHID` function is returning the providerID which has the ` providerID(metal://uuid)` format as bmhID which should be just `uuid`.
The problem is more visible when the providerID is directly set on the node itself, making it the source of truth for the providerID field. 
This PR extract the `uuid` part of the providerID.
> Fix bmhID parsing when providerid is set on the node directly.

- baremetal/metal3datatemplate_manager.go
- baremetal/metal3machine_manager.go
- hack/gosec.sh
- test/e2e/common.go
- [Add gosec file for go security checks](https://github.com/metal3-io/cluster-api-provider-metal3/commit/be2c770f7e7d421298d8c02813701450065b3159)
- [Use crypto/rand instead of math/rand](https://github.com/metal3-io/cluster-api-provider-metal3/commit/7a6747d6c18c58e56b57f374ec76e351d7351f81)
- [Reassign loop variable to address gosec G601](https://github.com/metal3-io/cluster-api-provider-metal3/commit/22e3edd51f099e1beb954d0d0d4c79663db5cef2)
- [Cleanup bad filepath using filepath.Clean](https://github.com/metal3-io/cluster-api-provider-metal3/commit/31d76469e8660fb3bb023fd39005e923ba1c8db3)
- [Fix unsafe defer call to file.Close()](https://github.com/metal3-io/cluster-api-provider-metal3/commit/ab30c48124b1f2ffca4b56275ec43c9b91eb7025)
- [Exclude rule G107 and include …
> 🌱 Add gosec file and related changes in release-0.5 branch

- Makefile
- scripts/ci-e2e.sh
- test/e2e/cert_rotation_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/e2e_test.go
- test/e2e/node_reuse_test.go
- test/e2e/upgrade_baremetal_operator_test.go
- test/e2e/upgrade_ironic_test.go
This PR will introduce e2e test for ephemeral cluster such as ironic upgrade, bmo upgrade, cert rotation and node reuse tests.
> 🌱Add e2e tests for ephemeral cluster

- test/e2e/node_reuse_test.go
This PR will fix node reuse test for ephemeral cluster. It was missing the change of clusterClient instead of targetCluster.
> 🐛Fix node reuse test for e2e ephemeral cluster tests

- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- baremetal/mocks/zz_generated.metal3machine_manager.go
- baremetal/suite_test.go
- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_integration_test.go
- controllers/metal3machine_controller_test.go
This PR has three main goals.
**(1)providerID from nodes when noCloudProvider is set to false**
With `Metal3Cluster.Spec.NoCloudProvider` set to `false`.  The source of truth for the `providerID` is the node.
And, the `providerID` field on the `Metal3Machine` should be updated accordingly.
**(2) A new providerID format**
This PR also introduced a new providerID format. The are now two supported providerID formats.
Suppose, we have a bmh named node-0, then the two providerIDs formats are shown below.
```
metal3://d668eb95-5df6-4c10-a01a-fc69f4299fc6
metal3://metal3/node-0/test-controlplane-xyz
```
**(3) preventing  duplicate usage of a providerID**
This PR prevents a providerID from being used by multiple nodes at the same time. To this end, both formats of a given providerID are treated …
> ✨ Introduce an additional providerID format and set providerID from nodes when noCloudProvider is set to false

- controllers/suite_test.go
This is required to identify resources per package in the integration tests.
> 🌱 Add namespace to test case object names

- VERSIONING.md
It fixes:
-  dead link reference, Prow link reference
-  CNCF CLA check for PR authors' notes since it is not required
> 📖 Update Versioning notes

- hack/tools/tools.go
This has to be consistent with the build command in the Makefile in
order for vendoring to work properly (builds with `-mod=vendor` fail without this fix because the correct files aren't vendored).
> 🐛 Fix mockgen path in tools.go

- api/v1beta1/condition_consts.go
Replaces the value of `SettingProviderIDOnNodeFailedReason` with `SettingProviderIDOnNodeFailed` so it's easier to figure out what's going when that error occurs.
> 🐛 Fix condition Reasons values for Metal3Machine

- baremetal/metal3machine_manager.go
Avoid panic when host is nil.
Fixes #
> :seedling: Increase judgment to avoid panic

- baremetal/metal3machine_manager.go
Confirm that the host contains nodeReuseLabelName and then output the relevant log information.
Fixes #
> :seedling: Add judgment before output log

- scripts/environment.sh
- test/e2e/e2e_test.go
- test/e2e/upgrade_management_cluster_test.go
Move the Ironic and BMO upgrade tests to the e2e upgrade test and run them before the CAPM3 upgrade test.
What should we do about the ephemeral test? Should we still run BMO and Ironic upgrade there?
> 🌱 Rearrange e2e upgrade tests

- baremetal/metal3machine_manager.go
When deleting a metal3 machine, print log info if the host is not found.
Fixes #
> 🌱 Add host nil log info to machine manager Delete function

- api/v1beta1/metal3machine_types.go
- api/v1beta1/metal3machine_types_test.go
- controllers/metal3machine_controller_integration_test.go
Verify that the values of Image.URL and Image.Checksum are valid urls.
Fixes #
> :seedling: Add url validation to the subfield of image

- baremetal/metal3data_manager_test.go
- baremetal/metal3datatemplate_manager_test.go
- baremetal/suite_test.go
- controllers/suite_test.go
This PR is specific to the **baremetal** package and is required before parameterizing hard coded resource names.
It mainly removes objects such as the following.
```
testObjectMeta = metav1.ObjectMeta{
Name:     "",
Namespace: namespaceName,
}
```
The problem we are facing is that objects such as testObjectMeta are used for any resource, such as metal3Machine, Machine, cluster and so on. This creates a problem when a specific test cases needs to change the name or namespace.
> Define ObjectMeta metav1.ObjectMeta at Test case level for baremetal package tests

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- baremetal/mocks/zz_generated.metal3machine_manager.go
- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_integration_test.go
- controllers/metal3machine_controller_test.go
currently, the controller is using the new providerID format to do a label based search of the node.
This does not work if  a node with the old providerID `(metal3://bmhID) `was wrongly overwritten with the new format providerID.
This PR fixes this issue and updates tests accordingly.
>  🐛 Handle node search based on label even when bmhID of providerID is overriden.

- .github/workflows/kubesec.yml
- template/sarif.tpl
Kubesec is a security risk analysis tool for Kubernetes manifest files and this PR is going to add a github action script to CAPM3. All the manifest files is going to be scanned by Kubesec weekly.
1.  [Github action test in Nordix](https://github.com/Nordix/cluster-api-provider-metal3/actions/runs/2280892391)
2. [Test result in Nordix](https://github.com/Nordix/cluster-api-provider-metal3/security/code-scanning?query=is%3Aopen+branch%3Aadd-kubesec-moshiur)
**Known issue:**  Kubesec scan on `examples/clusterctl-templates/clusterctl-cluster.yaml` will fail because of two variable used in the file namely:  `${CTLPLANE_KUBEADM_EXTRA_CONFIG} `in line 67 and `${WORKERS_KUBEADM_EXTRA_CONFIG}` in line 152 which includes entries as yaml.  The reason is kubesec is scanning each yaml file content …
> 🌱 Add kubesec for CAPM3

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
Don't write hardware details into `statusAnnotation`, because we don't need to move
inspection data to the target cluster via annotation anymore but do it instead via
hardwareData CRD, which is implemented in https://github.com/metal3-io/baremetal-operator/pull/1099.
Partially fixes https://github.com/metal3-io/cluster-api-provider-metal3/issues/266
> 🌱 Don't write hardware details into statusAnnotation

- .github/workflows/lint-docs.yaml
- .markdownlinkcheck.json
- docs/dev-setup.md
- docs/releasing.md
Add dead link linter github workflow and fix some dead links. This github action fails on broken links when *.md files are modified.
> 🌱  Add dead link linter github workflow

- Makefile
Since we have an issue cleaning the cluster if a test failed it is confusing to run the next tests after a failure since they will definitely fail and override some logs, this PR adds fail fast to ginkgo to stop testing once a spec fails
> Make e2e ginkgo fail fast 

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
This PR 
- Uplifts github.com/docker/distribution to v2.8.1
- Uplifts github.com/metal3-io/ip-address-manager to v1.1.3
- Uplifts github.com/metal3-io/baremetal-operator/apis to latest @ 2022 June 17th
> 🌱 Uplift IPAM to v1.1.3, BMO to latest and docker/distribution to v2.8.1

- baremetal/metal3machine_manager.go
In the recursive call of deleteOwnerRefFromList there is used the
variable refListLen := len(refList) - 1. However, in the recursive call
we use refListLen - 1, so that we have len(refList) - 2 in the end. It
should only be len(refList) - 1 though.
**Which issue(s) this PR fixes**
Fixes #565
> :bug: Fix recursion in deleteOwnerRefFromList

- Makefile
- scripts/ci-e2e.sh
Currently the e2e CI tarball does not contain the serial-logs because they got cleaned before the logs collection stage.
This PR fix this issue by making the dev-env cleaning triggered from the pipeline cleaning stage after collecting the logs
> 🐛 Move dev-env cleaning to the makefile so it get triggered from the pipeline cleaning stage

- test/e2e/pivoting_test.go
- test/e2e/upgrade_management_cluster_test.go
These configmaps are created/edited from metal3-dev-env when setting up
the environment. It is better to let them stay as they are to avoid
conflicts and mistakes. They are cleaned/reset every time the bootstrap
cluster is lanuched anyway.
Wait for https://github.com/metal3-io/metal3-dev-env/pull/975 before merging this.
> 🌱 Leave BMO and Ironic configmaps alone

- baremetal/metal3remediation_manager.go
- controllers/metal3remediation_controller.go
- test/e2e/metal3remediation_test.go
The updated remediation flow introduced by https://github.com/metal3-io/cluster-api-provider-metal3/pull/668 has an issue, the remediations CRs can't be deleted because the finalizer isn't removed.
The fix is: Initialize patch helper after getting current CR!!! Otherwise nothing will deleted by patch, only added.
Some more improvements done along the way deugging this:
- Requeue CR when patch fails
- CRs with deletion timestamp are handled in normal CR flow (finalizer needs to be removed)
- add CR deleted check to e2e test
- slightly better logging
- use controller utils for finalizer handling
> 🐛 Fix remediation cleanup

- baremetal/metal3machine_manager.go
The name matching was catching BMHs with overlapping names
like worker1 and worker10. This commit extends the matching
to include the namespace, name and delimiters for the BMH.
> :bug: Fix overlapping providerID duplicate detection

- api/v1beta1/metal3machine_types.go
- api/v1beta1/metal3machine_types_test.go
Add verification processing when DiskFormat is live-iso.
Checksum is not required for live-iso.
> :seedling: Improve the verification of Image

- scripts/environment.sh
Until the e2e upgrade test starts with CAPI 0.4.x + CAPM 0.5.x + K8s 1.23.x it is not possible to set
the starting version of the target cluster (FROM_K8S_VERSION) higher than 1.23.x
> :bug: Fix initial target cluster K8s version

- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
Fixes: #680 
This fixes an issue where old IPClaims could be reused by CAPM3 before IPAM had a chance to delete them. One easy way to reproduce it is to scale down IPAM to 0 (to make sure it never has time to delete old claims) and then do an upgrade of the KCP.
CAPM3 will then happily reuse the old IPClaims for the new machines even though they have deletion timestamps.
Once IPAM is scaled up again, it will proceed to clean up the IPClaims, resulting in missing IPClaims for all the new machines.
The fix I have implemented here is to make CAPM3 check for deletion timestamps before "accepting" the IPClaim. So CAPM3 will simply requeue and wait for a "proper" IPClaim.
I guess an alternative would be to use the claims with a deletion timestamp and …
> 🐛 Don't use IPClaims with deletion timestamp

- metadata.yaml
Update metadata to include capi 1.2.X releases
Otherwise we get, 
```
est:~ $ clusterctl init --infrastructure=metal3:v1.2.0-rc.0
Fetching providers
Error: invalid provider metadata: version v1.2.0-rc.0 for the provider capm3-system/infrastructure-metal3 does not match any release series
```
> 🌱 Update metadata to include capi 1.2.X releases

- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
- controllers/metal3data_controller.go
- Add a finalizer on IPClaims to protect them from accidental deletion while still in use.
- Also remove the owner reference on the IPClaim before marking for deletion so that IPAM can use it to determine if the IPClaim is still in use or not.
- Edited some confusing comments
I'm a bit unsure if this should be considered a "feature" or something else. Put 🌱 "other" for now.
> 🌱 Use finalizer on IPClaim to avoid premature deletion

- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
The initial implementation for checking if an IPClaim was in use, checked the ownerRef to determine if CAPM3 was using it or not. Since this was an API change in IPAM and a bit now really what ownerRefs are for, we are reverting it and rely on finalizers instead.
Relevant PR in IPAM: https://github.com/metal3-io/ip-address-manager/pull/133
> 🌱 Don't remove ownerRef from IPClaim when deleting

- OWNERS
This PR updates the OWNERS file to move inactive approvers/reviewers to emeritus. Also add Lennart Jern as a reviewer as he has reached the number of commits to be eligible for reviewer.
> 🌱 Update owners file to move inactive approvers/reviewers to emeritus and add Lennart as a reviewer

- test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/centos-kubeadm-config.yaml
- test/e2e/data/infrastructure-metal3/bases/ubuntu-kubeadm-config/ubuntu-kubeadm-config.yaml
The network config format was already changed in metal3-dev-env. We need to use the same here or it will be ignored and break the tests.
Also fixes the systemctl commands for enabling the monitor.keepalived unit. It looks like there has been some changes in systemd which make `systemctl enable monitor.keepalived.service` fail because it is operating on a symlink.
```
Failed to enable unit: Refusing to operate on alias name or linked unit file: monitor.keepalived.service
```
My understanding is, that instead of first linking and then enabling the link, we should just enable the unit using the absolute path. This also creates a symlink.
This issue is not *yet* seen on Ubuntu because it has an older systemd version.
See:
- …
> 🐛 Use keyfile format for CentOS network config

- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
- baremetal/suite_test.go
- If the IPClaim is old (=not matching current Metal3Data), attempt to clean it up
- If the IPClaim is in use, accept it even if it has a deletion timestamp. This could happen e.g. if the user tried to delete it but the Metal3Data/Metal3Machine still exists.
> 🌱 Improve handling of IPClaims with deletion timestamp

- api/v1beta1/metal3datatemplate_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
In #268 pr, v1alpha4 v1alpha5 has been fixed to 802.3ad (LACP) bond mode, but only v1beta1 is missing.
Fixes # N/A
> 🐛 Fix missing LACP bond mode

- scripts/ci-e2e.sh
After this PR https://github.com/metal3-io/metal3-dev-env/pull/1072 BMOBRANCH var is moved from lib/common.sh to lib/releases.sh. So we need to source both the files here.
> 🐛 Fix BMOBRANCH fetching in e2e by sourcing lib/releases from dev env

- test/e2e/inspection_test.go
- test/e2e/pivoting_test.go
- test/e2e/remediation_test.go
- test/e2e/upgrade_management_cluster_test.go
This fixes the flake we have been seeing in the e2e tests where it gets stuck scaling up the KCP in remediation.
In the e2e tests we often have to wait for BMHs/M3Ms/Machines to be in some specific state. In some places we had mistakenly not added any conditions to the Eventually call, or used it in a not supported way. This commit makes the use of Eventually more consistent and fixes the missing conditions.
I'm also working on a larger follow up PR for factoring out the common code and turn it into functions.
> 🐛 Fix e2e waiting for status

- hack/gen_tilt_settings.sh
- scripts/ci-e2e.sh
- scripts/environment.sh
- test/e2e/data/shared/v1beta1/metadata.yaml
Also, fetch correct CAPI release when running e2e upgrade tests `{GINKGO_FOCUS:-} == "upgrade"`
This is a follow-up to #674
> 🌱 Add v1.2 CAPI release contract to e2e metadata file

- baremetal/metal3remediation_manager.go
Fix nil panic when setting unhealthy annotation on host
> 🐛 Remediation: fix nil panic when setting unhealthy annotation on host

- test/e2e/common.go
- test/e2e/e2e_suite_test.go
- test/e2e/inspection_test.go
- test/e2e/live_iso_test.go
- test/e2e/node_reuse_test.go
- test/e2e/pivoting_based_feature_test.go
- test/e2e/pivoting_test.go
- test/e2e/remediation_based_feature_test.go
- test/e2e/remediation_test.go
- test/e2e/upgrade_management_cluster_test.go
This PR extracts some of the code we are using in many places to wait for BMHs/M3Ms/Machines/Nodes into separate functions. Some other functions are also moved to common.go since they are used from multiple tests.
To make it easier to see what is going on and what the state is, it also adds some functions to print the status similar to `kubectl get nodes,machines,m3m,bmh` and adds calls to them throughout the tests.
Please note that there are 2 commits. One is for the actual refactorization and one is for adding logs. For easier review, it may make sense to look at them one at a time. If you would rather want separate PRs let me know. I can split it up.
>  🌱 Refactor e2e tests and add more logs

- test/e2e/upgrade_management_cluster_test.go
- The cluster template is huge and clutters the logs. Skip printing it.
- The upgrade test for k8s was waiting for 4 BMHs to be provisioned when in fact the cluster only has 2 machines.
> 🌱 E2e: fix upgrade, don't print cluster template

- test/e2e/pivoting_based_feature_test.go
Fixes an issue in the e2e ephemeral test. For the ephemeral test there are no Metal3 CRDs in the target cluster, so we should not try to print them.
> 🌱 E2e: Don't print CRs in target cluster when running ephemeral test

- scripts/ci-e2e.sh
- scripts/environment.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/upgrade_management_cluster_test.go
This PR remove the custom upgrade test and reuse [clusterctl_upgrade](https://github.com/kubernetes-sigs/cluster-api/blob/release-1.2/test/e2e/clusterctl_upgrade.go) test from capi.
> 🌱 Reuse capi upgrade test function

- Makefile
Seems like #758 has overridden the OS var exported for e2e test here https://github.com/metal3-io/cluster-api-provider-metal3/blob/9db40bfee4ea49ffba46c47235d51ef719a385ff/test/e2e/pivoting_based_feature_test.go#L35
Jenkins logs main e2e test : https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_main_e2e_test_centos/117/console
> 🐛 Fix overriding OS env var from Makefile

- test/e2e/pivoting_based_feature_test.go
When tests fail after pivoting we are missing the resource from the target cluster in the tar ball this PR fix this issue.
Fixes #
> 🐛 Dump target cluster resources before repivoting

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
Uplifts CAPI to the latest patch release, which includes security fixes.
> 🌱 Uplift CAPI to v1.2.5

- .github/workflows/release.yaml
https://github.com/metal3-io/cluster-api-provider-metal3/pull/781/commits/834790ada9d15291ca8e447f2c3464ffc3173acd changed the path to put release notes under releasenotes folder from  `$(RELEASE_NOTES_DIR)/releasenotes.md` to `$(RELEASE_NOTES_DIR)/$(RELEASE_TAG).md`  thus leaving release.yaml file with old path. This should fix that path issue.
> 🐛  Fix body_path in the release.yaml

- Dockerfile
What this PR does / why we need it:
This change moves the base container images into ARGs which can be overridden at build time.
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
N/A
> 🌱 build: introduce support for FROM overrides

- Makefile
This PR removes `failfast` so we will run all the tests even when a spec fails in the middle. `failfast` was introduced because when the test fail in pivoting all the next tests were get failed which should be fixed by https://github.com/metal3-io/cluster-api-provider-metal3/pull/759
> 🌱 remove ginkgo failFast when running e2e tests

- scripts/environment.sh
- test/e2e/common.go
- test/e2e/config/e2e_conf.yaml
- test/e2e/node_reuse_test.go
- test/e2e/pivoting_based_feature_test.go
- test/e2e/remediation_based_feature_test.go
- test/e2e/upgrade_management_cluster_test.go
Co-authored-by: Kashif Khan <kashif.khan@est.tech>
For now all e2e test use the previous minor version as default k8s version instead of the latest.
This PR refactor e2e to use the latest k8s version for all the test except tests that require an old version like `clusterctl upgrade` from `v1alpha5` that requires k8s `v1.23.8` or `nodeReuse` that does k8s upgrade from the previous minor version to the latest
> 🌱 Use latest k8s version instead of previous minor version for e2e tests

- config/crd/kustomization.yaml
- config/crd/patches/skipcrdnamecheck_in_metal3datas.yaml
CAPI v1.3.X minor release is introducing a CRD name check and `clusterctl` will emit a warning for provider CRDs which don't comply with the CRD naming conventions. This warning can be skipped for resources not referenced by Cluster API core resources via the `clusterctl.cluster.x-k8s.io/skip-crd-name-preflight-check` annotation. The contracts specify:
```
> The CRD name must have the format produced by sigs.k8s.io/cluster-api/util/contract.CalculateCRDName(Group, Kind)
```
This PR makes sure that proper annotation is added to the metal3datas CRD using the kustomize patches, to avoid getting a warning when running `clusterctl init` with new v1.3.X CAPI minor releases.
xref: https://github.com/kubernetes-sigs/cluster-api/pull/7506#discussion_r10155446 …
> 🌱 Add SkipCRDNamePreflightCheckAnnotation to Metal3Data CRD

- test/e2e/cert_rotation.go
- test/e2e/common.go
- test/e2e/inspection.go
- test/e2e/metal3remediation.go
- test/e2e/node_reuse.go
- test/e2e/pivoting_based_feature_test.go
- test/e2e/pivoting_test.go
- test/e2e/remediation.go
- test/e2e/remediation_based_feature_test.go
- test/e2e/upgrade_baremetal_operator.go
- test/e2e/upgrade_ironic.go
- test/e2e/upgrade_management_cluster_test.go
Refactor e2e:
use function inputs instead of global vars
remove test suffix from function files
> 🌱  Refactor e2e: Remove test suffix from function files and use function inputs instead of global vars

- hack/gen_tilt_settings.sh
This logic change matches metal3-dev-env PR#1118.
Rely on Github's release order + prefix filter, instead of jq's max() which sorts v1.3.0-rc1 as newer than v1.3.0, which is wrong for the versioning convention we use.
/assign furkatgofurov7
> 🐛hack: download latest CAPI for tilt

- Makefile
`--progress ` was deprecated in Ginkgo v2 (https://github.com/onsi/ginkgo/blob/master/CHANGELOG.md#ginkgo-output-now-includes-a-timeline-view-of-the-spec) and we need to move to `--show-node-events` parameter, see the deprecation warning below:
```
Test Suite Failed
You're using deprecated Ginkgo functionality:
=============================================
--progress is deprecated .  The functionality provided by --progress was confusing and is no longer needed.  Use --show-node-events instead to see node entry and exit events included in the timeline of failed and verbose specs.  Or you can run with -vv to always see all node events.  Lastly, --poll-progress-after and the PollProgressAfter decorator now provide a better mechanism for debugging …
```
> 🌱 Ginkgo v2: Use --show-node-events parameter instead of --progress

- hack/markdownlint.sh
Pin markdownlint image to 0.12.0 with SHA to guard against changes without explicit acknowledgement.
Makes OpenSSF scorecard happier as well by pinning down another dependency.
Fixes #
> Bump mdl to 0.12.0 and pin it to sha:digest

- hack/shellcheck.sh
Pin shellcheck to 0.9.0 with digest.
Shellcheck 0.9.0 was released this morning. This way it is in line with other repositories, and pinned by digest.
> 🌱 shellcheck: pin to 0.9.0

- examples/clusterctl-templates/clusterctl-cluster.yaml
**What this PR does / why we need it**
User would be confused when they want to try metal3 provider for the first time. Add naive default to create Machine correctly at least.
**Which issue(s) this PR fixes**
Fixes https://github.com/metal3-io/cluster-api-provider-metal3/issues/820
> Add default Metal3DataTemplate to example

- controllers/metal3cluster_controller_integration_test.go
- controllers/metal3cluster_controller_test.go
- scripts/environment.sh
- test/e2e/common.go
- test/e2e/config/e2e_conf.yaml
- test/e2e/pivoting_based_feature_test.go
- test/e2e/remediation_based_feature_test.go
Due to changes in kubeadm and cluster-api for the container registry, we need to bump the upgraded k8s version to pass the test.
It is currently hard to tell what state the cluster was in when it failed. This should hopefully make it a bit clearer.
Similar to https://github.com/metal3-io/cluster-api-provider-metal3/pull/714 (but this was hard to backport it seems).
Fixes #
> 🌱 Bump upgraded k8s version and add basic logging after e2e tests

- scripts/environment.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/node_reuse.go
- test/e2e/upgrade_kubernetes_test.go
This PR:
- adds kubernetes upgrade test to e2e upgrade tests
- changing workflow from patching new image variables to m3machitemplate to creating new m3mtemplate with new variables in node reuse and k8s upgrade tests    
- hardcodes INIT_WITH_KUBERNETES_VERSION variable to  v1.23.8 (latest v1a4 supports)
> 🌱 Add kubernetes upgrade test to e2e upgrade

- Makefile
- scripts/environment.sh
- test/e2e/common.go
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/integration.go
- test/e2e/integration_test.go
- test/e2e/pivoting.go
- test/e2e/pivoting_based_feature_test.go
- test/e2e/remediation_based_feature_test.go
- test/e2e/upgrade_kubernetes_test.go
This PR adds ci-provisioning and provisioning (which currently can be run only from dev-env using ansible) to e2e tests.
Also added logs collections for all containers before pivoting, which is the behavior in dev-env pivoting.
> 🌱 Add integration test to e2e

- .github/workflows/kubesec.yml
- .github/workflows/lint-docs.yaml
- .github/workflows/release.yaml
Set top-level permissions to read, only allowing write where necessary.
Pin actions by a sha.
> 🐛 .github: secure github actions

- Dockerfile
Pin golang:1.19.4 with a digest.
> 🌱 pin golang to 1.19.4 with digest

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.3.2
>  🌱 Uplift CAPI to v1.3.2

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.2.9
> 🌱 Uplift capi to v1.2.9

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.3.2
> 🌱 Uplift CAPI to v1.3.2 

- Tiltfile
- config/manager/manager.yaml
- hack/tools/remove_sec_ctx.py
It is always good to not rely on the defaults, but be explicit. Set explicit, secure securityContext for the capm3 controller manager deployment and containers.
Functionally, the only thing actually changing for runtime is setting the seccompProfile to RuntimeDefault. Without this, default setting is Unconfined.
> ✨ add explicit securitycontext to controllers

- test/e2e/config/e2e_conf.yaml
- test/e2e/upgrade_management_cluster_test.go
Fix upgrade test issue:
Unset custom var env after management upgrade
Apply bmh to metal3 namespace after removing management ns
> :bug: Clean varenv after mngmt upgrade

- hack/ensure-kind.sh
Take ensure-kind.sh from CAPI, that has added support for Mac (Darwin), raised minimum kind version to 0.17.0 and added support for `set -x` via `TRACE` env.
Also, fix the script not to fail if GOPATH_BIN in not in user's path before running the script, but print a warning and then use full path for the kind so we can do version check properly, and also warn user that he needs to fix their PATH.
> 🌱 hack: update ensure-kind.sh

- test/e2e/cert_rotation.go
- test/e2e/config/e2e_conf.yaml
- test/e2e/pivoting.go
- test/e2e/upgrade_ironic.go
- test/e2e/upgrade_management_cluster_test.go
- Support running Ironic with MariaDB
- Use new deploy script args instead of positional booleans
- Add keepalived variable to e2e config for consistency
Related:
- https://github.com/metal3-io/baremetal-operator/pull/1196
- https://github.com/metal3-io/metal3-dev-env/pull/1127
> 🌱 E2e: Support running Ironic with MariaDB

- hack/gomod.sh
gomod.sh has only checked top-level go.mod/go.sum so far, which means api/ and hack/tools go.mods have not been verified.
The script also did not work locally at all, since /workdir was mounted read-only and "go mod tidy" writes to the directory.
Utilize existing "make modules" target.
> :bug: hack: gomod needs to verify all go.mod files

- Dockerfile
golang images less than v1.18.10 is vulnerable. Relates to https://github.com/kubernetes-sigs/cluster-api/issues/7974
> 🌱 Bump Dockerfile golang image tag to v1.18.10

- hack/gomod.sh
- hack/tools/go.mod
- hack/tools/go.sum
gomod.sh has only checked top-level go.mod/go.sum so far, which means api/ and hack/tools go.mods have not been verified.
The script also did not work locally at all, since /workdir was mounted read-only and "go mod tidy" writes to the directory.
Utilize existing "make modules" target.
Fix hack/tools/go.sum as its been merged earlier without mod tidy.
Manual backport of #857
> 🐛 hack: gomod needs to verify all go.mod files

- hack/gomod.sh
gomod.sh has only checked top-level go.mod/go.sum so far, which means api/ and hack/tools go.mods have not been verified.
The script also did not work locally at all, since /workdir was mounted read-only and "go mod tidy" writes to the directory.
Utilize existing "make modules" target.
Uplift the Go used from insecure Go 1.17 to Go 1.18.
Manual backport of #857
> hack: gomod needs to verify all go.mod files

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- baremetal/mocks/zz_generated.metal3machine_manager.go
- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_test.go
Running the unit test on latest main branch fails with:
```
• [FAILED] [0.000 seconds]
Metal3Machine manager Test SetNodeProviderID Test SetNodeProviderID [It] Set target ProviderID, matching node
/Users/fgofurov/workspace/cluster-api-provider-metal3/baremetal/metal3machine_manager_test.go:2618
[FAILED] Unexpected error:
<*baremetal.RequeueAfterError | 0x14000be7a48>: {
RequeueAfter: 30000000000,
}
requeue in: 30s
occurred
In [It] at: /Users/fgofurov/workspace/cluster-api-provider-metal3/baremetal/metal3machine_manager_test.go:2595 @ 03/01/23 09:31:45.073
------------------------------
• [FAILED] [0.000 seconds]
Metal3Machine manager Test SetNodeProviderID Test SetNodeProviderID [It] Set target ProviderID, providerID set
/Users/fgofurov/workspace/cluster-api-provider-metal3/baremetal/metal …
```
> Revert "🐛 Remove bmhID arg from SetNodeProviderID call"

- README.md
e2e triggers are being unified to format : `/test-<os>-e2e-<type>-<branch>`
related prs:
https://gerrit.nordix.org/c/infra/cicd/+/17454
https://github.com/metal3-io/project-infra/pull/490
> 📖 Unify e2e triggers format

- api/v1beta1/condition_consts.go
- baremetal/metal3data_manager.go
- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- controllers/metal3machine_controller.go
Co-authored-by: Adil Ghaffar <muhammad.adil.ghaffar@est.tech>
When there is an issue on ip allocation on ipam `m3m` will be waiting without explicitly showing what the user should look for. This PR adds a waiting condition to `m3m` when `m3d` is not ready and the latter would show in the `ErrorMessage` any error in the ip allocation.
> 🌱 Add m3d waiting condition to m3m object

- hack/manifestlint.sh
kubeval is not maintained anymore, and suggest moving to kubeconform. Change manifestlint.sh to use kubeconform.
Pin kubeconform image with a version and a digest.
This is a manual cherry-pick of #824
> 🐛 manifestlint: move from kubeval to kubeconform

- hack/gomod.sh
gomod.sh was cleaned up in main, cherry-pick for release-1.1. This makes running gomod.sh locally possible as intended.
Manual cherry-pick of #857.
> 🐛 cherry-pick gomod.sh changes from main

- .github/workflows/kubesec.yml
- .github/workflows/lint-docs.yaml
- .github/workflows/release.yaml
Workflows use resources that are only available when run in the [metal3-io/cluster-api-provider-metal3](https://github.com/metal3-io/cluster-api-provider-metal3) repository, so workflow run would always fail when they run in a forked repository. They are of no value to fork repositories. They are triggered by the schedule event, so they cause regular annoying and confusing workflow failure notifications for every fork owner. Rather checking these workflows only in upstream repo is enough. This PR is inspired by https://github.com/arduino/arduino-cli/pull/888
> 🌱 Disable scheduled workflows from running in forks

- scripts/ci-e2e.sh
This set command fails, as its missing -o to read the pipefail option.
> 🐛 fix malformatted pipefail option in ci-e2e.sh

- scripts/fetch_target_logs.sh
- test/e2e/integration_test.go
- test/e2e/pivoting.go
This PR will help the log collection of target cluster during e2e tests. It has the following parts:
-  It will fetch target cluster kubeconfig and save it to tmp folder with kubeconfig-test1.yaml, which will help the project-infra log collection of target during failure in target cluster and also helps to collect logs of target cluster before re-pivoting in case of successful run.
- Fetch target clulster resources during integration test.
- Add script to collect target logs before re-pivot.
>  🌱 Improve target log collection for e2e

- docs/releasing.md
Something went sideways merging the previous update in #916 . It got replaced by the IPAM release documentation. Merge proper documentation back with updates. Remove some parts that will go to metal3-io/metal3-docs#321
> 📖 update releasing.md and fix typos

- go.mod
- go.sum
- test/go.mod
- test/go.sum
Bump BMO and hardwareutils to 0.3.0-rc.0 in preparation for CAPM3 1.4.0-rc.0 release.
> 🌱 bump BMO to 0.3.0-rc.0

- go.mod
- go.sum
- test/go.mod
- test/go.sum
Bump BMO and hardwareutils to 0.3.0
> 🌱 bump BMO to 0.3.0

- README.md
Currently e2e budge is pointing to ansible integration job this pr fix it
> 🐛 Point build status to e2e instead of ansible

- docs/releasing.md
Add post-release actions within CAPM3 repository in the releasing.md Actions taken outside of CAPM3 are documented in the high-level releasing.md in metal3-docs.
1. Link to the metal3-docs releasing.md
2. Fix the go module tagging not to be annotated (release workflow might get messed up, only primary tag to be annotated)
3. Add branch protection rules
4. Add build badges
> 📖 update releasing.md with post-release actions

- test/e2e/upgrade_management_cluster_test.go
BMO require some secret that will be created when ironic get deployed in order to be available so we are switching the order of deploying them
> 🐛 Deploy ironic before bmo in upgrade test

- Dockerfile
bump golang image from 1.19.6 to 1.19.9
> :seedling: uplift golang image from 1.19.6 to 1.19.9

- Dockerfile
Bump golang for controller image to 1.19.9
Pin distroless.
Manual cherry picks of https://github.com/metal3-io/cluster-api-provider-metal3/pull/969 and https://github.com/metal3-io/cluster-api-provider-metal3/pull/958
> 🌱 bump golang image from 1.19.6 to 1.19.9, pin distroless

- Makefile
- hack/tools/go.mod
- hack/tools/go.sum
- hack/tools/tools.go
This is a dependency of the Makefile, and without it, we fail to vendor our golang files properly.
> :bug:  tools: add setup-envtest to tools.go

- .gitignore
In `baremetal/remote/remote.go`, we import `"sigs.k8s.io/cluster-api/util/kubeconfig"`, and the "kubeconfig" line in the `.gitignore` file causes this directory to be omitted from the vendor directory.  In vendorized scenarios, this causes builds to fail.
> :bug: Remove kubeconfig from .gitignore

- Makefile
- test/e2e/e2e_suite_test.go
- test/e2e/live_iso_test.go
- test/e2e/pivoting_based_feature_test.go
- test/e2e/remediation_based_feature_test.go
- test/e2e/upgrade_kubernetes_test.go
- test/e2e/upgrade_management_cluster_test.go
Currently, during keep tests environment is not cleaned up after successful e2e test. The env should be kept only tests fails. This PR fixes this issue by introducing KEEP_TEST_ENV variable.
> 🐛 Fix cleanup for keep tests

- test/e2e/common.go
What this PR does / why we need it:
This is fixing generation of sha256sum, it was not being formatted properly before which was resulting in wrong hash.
> :bug: Fixing sha256sum generation

- api/go.mod
- go.mod
- go.sum
Bump github.com/docker/distribution to v2.8.2 since the dependabot didn't bump all of the entries.
> 🌱 Bump github.com/docker/distribution to v2.8.2

- test/e2e/config/e2e_conf.yaml
- test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/centos-kubeadm-config.yaml
- test/e2e/pivoting_based_feature_test.go
From the centos node image I have removed the code that blocekd cloud-init
network configuration features that also blocked the IPAM integration.
As the result of the node image change, some processes have to be modified in the centos kubeadm
scripts. Kubeadm script changes include:
- Moving keepalived's K8s api monitoring from custom daemon to vrrp script in keeaplived
- Adding a delay after the kubelet and crio are started to avoid flakes with kubeadm
(this will be improved in a follow-up from a delay to an actual status check)
- Fixing the startup order of eth0 and ironicendpoint interfaces
A polling check was added to delay the certmanager deployment during target cluster bootstrapping
until all pods are running, this helps to avoid accidentally assigning IPs from crio default cni
IP …
> :bug: Modify kubeadm scripts to re-enable IPAM integration in e2e tests

- hack/tools/release/notes.go
Backport mariadb-image line to the release note generator, so it is automatically added to release notes.
> 🌱 backport mariadb-image line to release note generator

- test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/centos-kubeadm-config.yaml
- there is a default CNI configuration provided for crio during installation,
that enables the default CNI plugin (bridge) and configures a default CNI network
for crio using the default plugin.
- The default CNI config is switched to a CNI config procided by calico durin the
e2e tests many times and this on-the-fly switching causes stabilitu issues during the tests
Example of stability issues:
- Pods receive IPs from and attached to CRIO's default pod network before calico node is deployed then
when Calico node is deployed the old pod network is removed and a new is created and
the old pods can't be reached causing all sorts of issues.
This commit:
- removes the default CNI configuration to force CRIO to wait on the CNI
config generated by calico thus there won't be a collision between …
> :bug: Fix crio - calico CNI config collision on centos during e2e tests

- baremetal/metal3machine_manager.go
Manual backport of #1012 
Add a mutex lock to the Associate function. This function is not thread safe since we work on a common pool of BMHs. One BMH could potentially be associated with multiple M3Ms without this lock.
> 🐛 Fix race condition when associating BMH to M3M

- test/e2e/config/e2e_conf.yaml
The PR https://github.com/metal3-io/cluster-api-provider-metal3/pull/968/ should have bumped the calico to v3.25.1 but the commit seems to be missing. Bumping it here then.
> 🌱 Bump Calico to v3.25.1

- scripts/environment.sh
- test/e2e/upgrade_kubernetes_test.go
- test/e2e/upgrade_management_cluster_test.go
Adds labels to kubernetes and clusterctl upgrade tests to seperate the test using GINKGO_FOCUS
> 🌱 Seperate k8s and clusterctl upgrade tests

- test/e2e/config/e2e_conf.yaml
- test/e2e/node_reuse.go
This PR:
- introduces wait loops that wait for all pods to be running at the end of scale up and
scale down cycles to make sure that the workloads of the cluster won't get stuck or kept
in scheduling longer than absolutely needed
- disables control plane node tainting during the node_reuse test to get rid of the
complexity of managing tains parallel to scale up/down async processes
- noSchedule taints are disabled for control plane nodes because of an other reason also,
namely that during most of the test there are no other nodes than control plane nodes
available for scheduling so it doesn't make sense tainting them
> :bug: Refactor taint usage and flow controll in node_reuse e2e test 

- Tiltfile
- config/default/capm3/namespace.yaml
Added manifest file to enforce restricted pod security standards for capm3 repository.
> :seedling: Added pod security standards manifest file for CAPM3

- test/e2e/config/e2e_conf.yaml
In case of e2e feature tests, 7m has proven to be insufficient in situations when the machine marked for deletion is hosting all the Metal3, CAPI, cert manager and calico controllers .
7m seems to be enough for machines that have relatively few pods but it could happen that a heavily utilized node is being deleted and 7min is not enough.
> :bug: Increase machine deletion timeout during e2e tests

- .github/dependabot.yml
Dependabot is currently not updating gomodules in api/, test/ and hack/tools dir. This PR updates it.
> 🌱 Include all gomods in different directories for Dependabot

- test/e2e/cert_rotation_test.go
Removed mariadb restart check in certRotation test. Because we do not run any tests with mariadb for 1.2 release.
> :bug: Removed mariadb restart check in certRotation test

- main.go
- main_test.go
Added tls configuration flags for CAPM3.
This enables flags --tls-min-version and --tls-max-version flags, which can be used to limit TLS versions server accepts. Choices are TLS12 and TLS13, so you can force TLS 1.2 only, TLS 1.3 only, or (default) TLS 1.2 and TLS 1.3 is negotiated between server and client.
This also disables TLS 1.0 and TLS 1.1 as they're insecure and obsolete and not supported by Go TLS library.
> :sparkles: Add TLS configuration flags for CAPM3

- main.go
- main_test.go
Added tls configuration flags for CAPM3.
This enables flags --tls-min-version and --tls-max-version flags, which can be used to limit TLS versions server accepts. Choices are TLS12 and TLS13, so you can force TLS 1.2 only, TLS 1.3 only, or (default) TLS 1.2 and TLS 1.3 is negotiated between server and client.
This also disables TLS 1.0 and TLS 1.1 as they're insecure and obsolete and not supported by Go TLS library.
> :sparkles: Added tls configuration flags for CAPM3.

- .github/dependabot.yml
IPAM bump in CAPM3 needs more than just gomod bump, so having dependabot create PR for it is waste of resources. We do releasing of IPAM and CAPM3 back to back, and will do IPAM uplift in CAPM3 right after we've released it.
> 🌱 ignore ipam in dependabot config

- api/v1beta1/metal3datatemplate_webhook.go
#769 introduced defaulting for IPAM pool references that changes group and kind to metal3 IPAM. Since Metal3DataTemplates are immutable, this causes issues with existing resources when they are continuously applied (gitops).
The easiest option is to remove the defaulting in the webhook, since there are two more instances of defaulting in the DataManager ([here](https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/baremetal/metal3data_manager.go#L400) and [here](https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/baremetal/metal3data_manager.go#L434)).
Fixes #1010
> 🐛 remove ipam pool reference defaulting to metal3

- scripts/ci-e2e.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/upgrade_management_cluster_test.go
CAPM3 v1.4 seems not supporting k8s v1.23.8 this PR set fixed k8s version for each upgrade from release based on capi k8s support https://cluster-api.sigs.k8s.io/reference/versions.html#core-provider-cluster-api-controller
> 🐛 Fix k8s version based on clusterctl upgrade version

- .mdlrc
- CONTRIBUTING.md
- README.md
- docs/api.md
- docs/architecture.md
- docs/dev-setup.md
- docs/disk_cleaning.md
- docs/e2e-test.md
- docs/getting-started.md
- docs/ip_reuse.md
- docs/remediation-controller.md
- hack/markdownlint.sh
- test/README.md
Remove .mdlrc to have the same markdownlint rules as all other repos. We have plenty of long lines in shell sections and tables, so we move the MD013 rule ignore to the command line of the script to make it clear.
> :book: remove .mdlrc and fix complaints

- test/e2e/upgrade_clusterctl_test.go
Rename upgrade management cluster to upgrade clusterctl and add the correct upgrade from release to the describe text.
Also remove passed message from the aftereach as it shows that even when the test fail
> 🌱 Rename upgrade managment test and remove unecessary passed msg

- main.go
We currently have an issue with concurrency when associating a BMH to a M3M. A mutex was already added before to the Associate function. However, this does not completely solve the issue, because a caching client is used. In other words, the next M3M to associate can sometimes use cached data about the BMHs and pick one that is already associated.
This is a temporary workaround for #1004
> 🐛 Set M3M concurrency to 1 and add warning

- test/e2e/pivoting.go
BMO is caching the old node states after pivoting back and that might be the cause to the flake where the bmh is not deleted in centos this PR tries to solve the issue by reinstating bmo after moving back to source cluster
> 🌱 Remove and reinstall BMO in source cluster before and after pivot

- scripts/ci-e2e.sh
- test/e2e/config/e2e_conf.yaml
This PR will enable the Mariadb for ironic instead of SQLite, as we have database lock issue with SQLite. Community suggested to use Mariadb to resolve the issue in  CI. We can move back to SQLite once the issue is fixed from ironic.
Workaround for [#1082](https://github.com/metal3-io/cluster-api-provider-metal3/issues/1082) and keep the issue open to track the fixes of the SQLite issue
> 🐛Enable Mariadb instead of SQLite

- scripts/environment.sh
- test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/centos-kubeadm-config.yaml
- test/e2e/data/infrastructure-metal3/bases/cluster/md.yaml
- test/e2e/data/infrastructure-metal3/bases/ubuntu-kubeadm-config/ubuntu-kubeadm-config.yaml
- test/e2e/upgrade_kubernetes_test.go
- test/e2e/upgrade_management_cluster_test.go
Manual backport of #982.
This PR also removes container-runtime flag from Kubelet since it is unsupported from v1.27
> Add features label for e2e feature tests for ginkgo focus to release 1.4

- scripts/ci-e2e.sh
- test/e2e/config/e2e_conf.yaml
Reverts metal3-io/cluster-api-provider-metal3#1092
> Revert "🐛Enable Mariadb instead of SQLite"

- test/e2e/common.go
- test/e2e/e2e_suite_test.go
- test/e2e/integration_test.go
Now only collects qemu serial logs.
This PR contains the basic implementation of [CAPI log collector,](https://github.com/kubernetes-sigs/cluster-api/blob/ddb18986a0e325c8a877b19be817079938e32bae/test/framework/cluster_proxy.go#L105) and the collecting of serial logs. In the future, different logs can also be collected.
The collected logs can be checked in the tarball from the path: `e2e_artifacts/_artifacts/machines/`
> ✨ Added a log collector implementation for Metal3

- .github/PULL_REQUEST_TEMPLATE.md
VERSIONING.md no longer exists. This PR is to update to the correct link and also remove minor confusion between sparkles and seedling to avoid confusion to new contributors.
Fixes #
> 🌱 Update  Pull request template

- scripts/environment.sh
- test/e2e/basic_integration_test.go
This test will only create a cluster and collect logs from it. The resource flavor will be fixed here https://github.com/metal3-io/project-infra/pull/554
Fixes: #897
> 🌱 Added basic integration test

- docs/api.md
- docs/architecture.md
- docs/dev-setup.md
- docs/e2e-test.md
- examples/generate.sh
- hack/gen_tilt_settings.sh
- scripts/ci-e2e.sh
- scripts/environment.sh
- test/e2e/config/e2e_conf.yaml
This PR bumps the Kubernetes version in CAPM3 to v1.27.4. It aligns with the recent bump performed in the dev-env repository https://github.com/metal3-io/metal3-dev-env/pull/1263.
> Bump k8s version to v1.27.4

- scripts/environment.sh
- test/e2e/config/e2e_conf.yaml
fix setting INIT_WITH_KUBERNETES_VERSION (is used in clusterctl upgrade tests)
downgrade KUBERNETES_VERSION in release 1.3
>  🌱 Fix pivoting feature tests in release 1.3

- scripts/fetch_target_logs.sh
- test/e2e/upgrade_clusterctl_test.go
This will help to debug logs more efficiently and also able to collect logs during failed test .
>  🌱Add log and manifest collection for clusterctl upgrade test

- main.go
Fixed the code quality issues mentioned in [1320](https://github.com/metal3-io/baremetal-operator/issues/1320)
> :seedling: Fix code quality issues in TLS configuration code

- api/go.mod
- docs/releasing.md
- go.mod
- test/go.mod
This PR removes unnecessary replace blocks from go modules and updates release doc to check CAPI bumps while releasing.
>  🌱 Remove unnecessary replace blocks from go modules and update release document

- .github/dependabot.yml
This PR allows patch updates for the ignored dependencies and group the k8s.io dependencies to reduce the number of individual PRs.
>  🌱 Add dependabot groups and allow patch updates

- Dockerfile
Bump BUILD_IMAGE to golang:1.20.7
> 🌱 bump golang build_image to 1.20.7

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
Uplifts CAPI to latest stable patch release
> 🌱 Bump CAPI to v1.5.1 

- Tiltfile
- examples/generate.sh
- hack/gen_tilt_settings.sh
- test/e2e/config/e2e_conf.yaml
Uplifts cert-manager to v1.12.3
> 🌱 Bump cert-manager to v1.12.3

- README.md
Update README.md about release 1.5 related info.
> :book: update README.md on 1.5 release

- test/e2e/data/shared/main/metadata.yaml
We have missed adding the contract
> 🐛  Add missing CAPI v1.5 contract in e2e config

- test/e2e/data/shared/main/metadata.yaml
> 🐛 Add CAPI contract for e2e in release-1.5

- scripts/ci-e2e.sh
This PR fixes setting CAPI_CONFIG_FOLDER variable:
- Sets CAPI_CONFIG_FOLDER according to old branches and sets default value for new branches.
> fix setting CAPI_CONFIG_FOLDER variable

- README.md
Update build badge URLs, and update/remove non-1.5 related information related to testing etc.
> :book: update README.md

- hack/tools/release/notes.go
Improve release notes generation by adding empty section for superseded or reverted PRs, adding empty line between image tags and thanking our contributors, as well as changing wording on the mariadb-image and ironic-image tags.
> :book: improve release notes tool

- scripts/ci-e2e.sh
This PR adds v1.5 case to CAPI_FROM_RELEASE variable for clusterctl upgrade test
> 🌱 Fix v1.5 clusterctl upgrade tests

- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
- main.go
This adds a few tests for ensureM3IPClaim, with and without
EnableBMHNameBasedPreallocation set to true. Also made sure that the label
map exists on the Metal3Data before trying to add labels to it.
- Fixes some naming in the unit tests.
- Adds a bit more logs and improves misleading messages.
Fixes #
> 🌱 Minor cleanups and added tests

- .github/dependabot.yml
Updating GH actions weekly is excessive noise. Run it monthly.
> 🌱 run dependabot less often for GH actions

- hack/ensure-golangci-lint.sh
The digest for ensure-golangci-lint linux/amd64 is incorrect, and also the script fails to unbound variable when checking the SHA.
This fixes "make lint", and "make test", which are no longer utilized as CI tests, but only run locally.
Additionally, make the digest check also check the ARCH, which is the root cause of these mismatches.
Later on, I will add project-infra test to actually verify these scripts work.
> 🐛 fix ensure-golangci-lint digest for linux/amd64

- .golangci.yaml
- hack/gosec.sh
- test/e2e/common.go
- test/e2e/pivoting.go
- test/e2e/upgrade_clusterctl_test.go
Gosec does not handle submodules well. Ignore them and run them separately so they run against correct dependencies.
Bump gosec to 2.17.0, and fix new errors it has discovered.
Remove G107 exclude, it is no longer present.
NOTE: In CI, the gosec image is coming via project-infra, gosec image change is only affecting local runs for now.
> 🌱 bump gosec to 2.17.0, and fix gosec for submodules

- test/e2e/common.go
A different user is generating sha256sum for the images than is reading them back in. Change back to 544 as it was before #1213.
> :bug:  fix too tight file permissions in e2e

- Dockerfile
- Makefile
- README.md
- Tiltfile
- api/go.mod
- api/go.sum
- examples/generate.sh
- go.mod
- go.sum
- test/e2e/config/e2e_conf.yaml
- test/go.mod
- test/go.sum
- Bump CAPI to v1.5.2
- Bump Cert-manager to v1.13.0
- Bump GO to 1.20.8
> 🌱 Bumping CAPI to 1.5.2

- Dockerfile
- README.md
- Tiltfile
- api/go.mod
- api/go.sum
- examples/generate.sh
- go.mod
- hack/gen_tilt_settings.sh
- test/e2e/config/e2e_conf.yaml
- test/go.mod
- test/go.sum
- Bump CAPI to v1.4.7
- Bump Cert-manager to v1.13.0
- Bump GO to 1.20.8
> 🌱 Bumping CAPI to 1.4.7

- go.mod
- go.sum
- test/go.mod
Also removes the unnecessary replaces which also was also wrongly pointing to v1.4.6
> 🌱 Bump capi/test module to v1.4.7

- docs/releasing.md
Clarify module tagging instructions one more time. Signing is also creating annotated tags. Also add reminder to push the tags too.
> :book: clarify tag usage in releasing.md

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
Bump IPAM to latest release on main branch as well.
It was bumped in release-1.5 in #1230
> 🌱 bump IPAM to 1.5.1

- docs/releasing.md
- hack/verify-release.sh
Script that can be used to verify release content.
```console
+# USAGE:
+#
+# This script aims to verify a release content per docs/releasing.md
+# is all done, all images are built and release in general good to go.
+# It can be executed before making a release tag to verify Go dependencies
+# and vulnerabilities are already fixed.
+#
+# Git setup:
+# This script expects to be executed in the root directory of CAPM3
+# repository, with the release commit/tag in question checked out.
+#
+# Command line arguments:
+# arg1: mandatory: version without leading v, eg. 1.5.0
+#
+# Environment variables:
+# GITHUB_TOKEN: mandatory: your bearer token that has access to the release
+# REMOTE: optional: use this git remote for tag checks: Default: autodetected
+# CONTAINER_RUNTIME: optional: …
```
> :seedling: add hack/verify-release.sh script

- hack/verify-release.sh
In case module group versions mismatch, grep failed to print out the mismatching modules. Fix the grep with "-E", and remove unnecessary curlys around it as well, after grep was optimized.
> 🌱 fix module printout in hack/verify-release.sh

- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
This limits the listing of IPClaims to the namespace of the Metal3Data. Without this limit, CAPM3 could delete IPClaims in other namespaces, provided that they have the same labels. The labels are based on the name of the IPPool and Metal3Data(Template), which can be the same in other namespaces.
This also adds a few unit tests that check specifically the behavior when deleting IPClaims when there are multiple, in multiple namespaces. One of these tests trigger the bug described in #1250.
Fixes #1250
> 🐛 Fix IP-reuse deletion bug

- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
Manual cherry pick of #1251.
When listing the IPClaims, we currently only select by labels, so there is no limit on what namespace the IPClaim belongs to. The labels are based on the name of the IPPool and the name of the Metal3Data. Within the same namespace these will be unique, but not necessarily cluster wide.
This commit limits the list of IPClaims to the same namespace as the Metal3Data. It also adds a few unit tests to check the behavior when we have multiple IPClaims, potentially in separate namespaces and with identical labels.
Fixes #
> 🐛 IP reuse: Fix M3d/IPClaim deletion bug

- hack/verify-release.sh
Using GLOBIGNORE makes the code simpler, and allows us to ignore the hack/tools/go.mod for sed as well, not just in grep. This fixes issue that module versions are reported as incorrect, if hack/tools/go.mod is the one with wrong version, yet the output then does now show the hack/tools/go.mod as culprit.
> 🌱 use GLOBIGNORE to ignore hack/tools/go.mod in verify-release.sh

- main.go
This PR should fix the issue of a single BMH associating with multiple M3Ms when concurrency is enabled. It does so by disabling caching for BMH objects alltogether.
Fixes #1004
> 🐛 Fix one BMH associating to multiple M3Ms

- baremetal/metal3machine_manager.go
The current format results in error log which looks like this: "could not find node with labelnodelabelmetal3.io/uuid=b8d8272d-36d8-4eb3-a999-90bee3039b16"
Fixes #
> :bug: Fix the "Could not find node with label" error message

- hack/ensure-go.sh
Minor code improvement in ensure-go.sh as suggested here: https://github.com/metal3-io/baremetal-operator/pull/1405#discussion_r1372984661
> 🌱 Minor code improvement in ensure-go

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
Bumping it manually since it seems dependabot has only caught the test/ module bump.
> 🌱 Bump CAPI to v1.5.3

- test/go.mod
- test/go.sum
Manual-cherry pick of #1297 to close dependabot alert.
> Security: Deny containers access to /sys/devices/virtual/powercap by default. This change hardens against [CVE-2020-8694](https://scout.docker.com/v/CVE-2020-8694), [CVE-2020-8695](https://scout.docker.com/v/CVE-2020-8695), and [CVE-2020-12912](https://scout.docker.com/v/CVE-2020-12912), and an attack known as [the PLATYPUS attack](https://platypusattack.com/). For more details, see [advisory](https://github.com/moby/moby/security/advisories/GHSA-jq35-85cj-fj4p), [commit](https://github.com/moby/moby/commit/c9ccbfad11a60e703e91b6cca4f48927828c7e35).
> 🌱 bump docker/docker to v24.0.7+incompatible

- CONTRIBUTING.md
Updating contributing guide regarding signing off of commits
> 📖 Commit signing off update.

- hack/verify-release.sh
Github API does not allow fetching draft release notes by tag, only by release id. Add the required code to fetch that, and also do not bail out if it fails, just skip the tests that require the data.
Also fix osv-scanner exiting the script before printing the vulnerabilities. It returns failure when vulns are found.
/hold
until https://github.com/metal3-io/ip-address-manager/pull/381 merges
/cherry-pick release-1.5
/cherry-pick release-1.4
> 🌱 improve hack/verify-release.sh draft release note handling

- Dockerfile
- Makefile
Bump golang version to 1.20.11 which will fix security vulnerability [CVE-2023-45284](https://osv.dev/vulnerability/GO-2023-2186)
> 🌱Bump golang version 1.20.11 release-1.5

- Dockerfile
Bump golang version to 1.20.11 which will fix security vulnerability [CVE-2023-45284](https://osv.dev/vulnerability/GO-2023-2186)
> 🌱Bump golang version to 1.20.11 for release-1.4

- main.go
Rest of the flags in main.go are pflag, perhaps this was a typo/mistake to declare this as a go flag.
> 🐛  Use pflag instead of go flag for TLSMinVersion

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- docs/api.md
- test/e2e/pivoting_based_feature_test.go
It's valid to use other `controlplane.cluster.x-k8s.io` controlplane provider resources, so remove the explicit check for Kind
We [already check the Group ](https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/api/v1beta1/groupversion_info.go#L30) e.g `controlplane.cluster.x-k8s.io` which should be sufficient to ensure we're retrieving a controlplane resource name.
Fixes: #1310
> ✨ Don't assume KubeadmControlPlane for nodeReuse

- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
In certain conditions `addressFromM3Claim` can accept an old IPClaim (about to be deleted) for a new Metal3Data. This commit fixes this by checking the UID of the owner reference instead of just trusting the name.
Conditions to trigger the issue during a rollout:
1. The IPClaim name must be the same before and after rollout. This can happen when BMH name based pre-allocations are used and the same BMH is used for the old and new M3M. Alternatively, if the Metal3Data happens to be named the same (i.e. it has the same index).
2. The IPClaim must not get the deletion timestamp until after the new Metal3Data has gotten the IPAddress from it (race). The reason for this is that we already check and avoid using IPClaims that has a deletion timestamp. …
> 🐛 Fix race condition getting IPAddress for Metal3Data

- api/v1alpha5/metal3cluster_types.go
- api/v1alpha5/metal3data_types.go
- api/v1alpha5/metal3dataclaim_types.go
- api/v1alpha5/metal3datatemplate_types.go
- api/v1alpha5/metal3machine_types.go
- api/v1alpha5/metal3machine_types_test.go
- api/v1alpha5/metal3machinetemplate_types.go
- api/v1alpha5/metal3remediation_types.go
- api/v1alpha5/metal3remediationtemplate_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediations.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediationtemplates.yaml
Set v1alpha5 API types unserved and deprecated in CRDs
Part of https://github.com/metal3-io/cluster-api-provider-metal3/issues/971
>  ⚠️ Stop serving v1alpha5 API Versions

- api/v1beta1/groupversion_info.go
- api/v1beta1/metal3cluster_types.go
- api/v1beta1/metal3data_types.go
- api/v1beta1/metal3dataclaim_types.go
- api/v1beta1/metal3datatemplate_types.go
- api/v1beta1/metal3machine_types.go
- api/v1beta1/metal3machinetemplate_types.go
- api/v1beta1/metal3remediation_types.go
- api/v1beta1/metal3remediationtemplate_types.go
- api/v1beta1/v1beta1_suite_test.go
This is recommend for the CAPI providers as mentioned the v1.5 to v1.6 migration guide: https://cluster-api.sigs.k8s.io/developer/providers/migrations/v1.5-to-v1.6#suggested-changes-for-providers.
The original issue was discussed in https://github.com/kubernetes-sigs/cluster-api/issues/9011. The issue is using controller-runtime based scheme builder causes a lot of unnecessary dependancies added in go modules. Compared to that apimachinery was chosen as a better alternative.
> 🌱  Use k8s apimachinery scheme builder instead of controller-runtime scheme builder

- Dockerfile
- Makefile
There are some vulnerabilities that are fixed in 1.20.12. They're not affecting us, but scanners nag, so might as well bump.
> 🌱 bump golang to 1.20.12

- .github/workflows/build-images-action.yml
- .github/workflows/dependabot.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/kubesec.yml
- .github/workflows/lint-docs.yaml
- .github/workflows/pr-verifier.yaml
- .github/workflows/release.yaml
Move permissions from top-level to job-level as well.
Cleanup actions formatting to be the same for easier reading and maintenance. Add missing version tags.
These is highlighted by the CLOmonitor/OpenSSF Scorecard. This restores score for token permissions to 10/10.
> 🌱 reduce github actions permissions

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump CAPI to v1.6.1

- CONTRIBUTING.md
Adds v1.6.x and updates v1.4.x support timeline. v1.4.x is now EOL but will be tested for one more release cycle as promised in the contributing guide.
> 📖 Update Support matrix in Contributing guide

- .markdownlint-cli2.yaml
- CONTRIBUTING.md
- docs/api.md
- hack/markdownlint.sh
Switch markdownlint container to markdownline-cli2. This CLI version supports the enable/disable rules in markdown files and allows us to ignore issues locally, not just globally.
- project-infra PR https://github.com/metal3-io/project-infra/pull/619 needs to merge for markdownlint here to pass
> :book: switch markdownlint container to markdownlint-cli2

- hack/ensure-kubectl.sh
If we don't default to the kubernetes version used for the test, it will always use v1.29.0 and it will error out for upgrade tests where we use older k8s version to begin with.
> 🐛 Default k8s version in ensure-kubectl script

- hack/ensure-kubectl.sh
Co-authored-by: Tuomo Tanskanen <tuomo.tanskanen@est.tech>
In `ensure-kubectl.sh `script, for older versions of k8s (<= v1.27.x) the check produces an expected output like  `echo -e 'v1.29.0\nversion.Info{Major:"1",` the comparison cannot make sense of it and instead of erroring out, the test continues. Whereas for newer version the output is as expected `echo -e 'v1.29.0\nv1.28.1'` and the comparison in the script errors out if the kubectl version is not correct. We fix it here by making sure we use the old kubectl version flag first (`--client --short`) and if it fails we check with the `--client ` only since `--short` is now removed in v1.29.x for example.
> 🐛 Fix for kubectl version command for different versions of k8s

- Tiltfile
This PR fixes a setup issue:  `start.sh: line 34: can't create process.txt: Permission denied`. Modifications in the Tiltfile ensure process.txt is now correctly created with full permissions (0777).
> 🌱 Fix Permission Issue for process.txt in Tiltfile Configuration

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump CAPI to v1.5.6

- .github/workflows/build-images-action.yml
Image build action is not triggering for anything but main, which is the only trigger not having `*` in it. So, let's try removing the quotes as any of the [GH examples](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push)  do not use quotes unless it is mandatory (ie. leading `*`, or `[]`).
> 🌱 try fix GH workflow for image building

- test/e2e/cert_rotation.go
Some leftovers were still there even after #1483 and #1481, which is only caught in feature test.
> 🌱  Remove ironic-inspector from container list for e2e tests

- test/e2e/common.go
- test/go.mod
When EnsureImage fails to download an image instead of giving the right error that the `image is not available` it downloads a failed page(https://artifactory.nordix.org/ui/native/metal3/images/k8s_v1.28.0/), and in provisioning ironic tries to use it.  This PR is fixing this by erroring out the right message and also failing early instead of trying to provision with non existent image.
Fixes #
> 🐛 EnsureImage download image fix

- .github/workflows/golangci-lint.yml
- .golangci.yaml
- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
- baremetal/metal3machine_manager_test.go
- baremetal/metal3remediation_manager_test.go
- controllers/metal3labelsync_controller_test.go
- controllers/metal3machine_controller_integration_test.go
- controllers/metal3remediation_controller.go
- hack/ensure-golangci-lint.sh
- test/e2e/cert_rotation.go
- test/e2e/common.go
- test/e2e/pivoting.go
- test/e2e/upgrade_clusterctl_test.go
- test/e2e/upgrade_ironic.go
> 🌱 Bump golangci-lint to v1.56.2

- api/go.mod
- api/go.sum
- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- test/go.mod
- test/go.sum
JSON unmarshalling can enter infinite loop.
https://osv.dev/vulnerability/GO-2024-2611
Manual cherry-pick of #1508.
> 🐛 bump google.golang.org/protobuf to v1.33.0

- Dockerfile
- Makefile
v1.21.8 has fixed some CVEs https://github.com/golang/go/issues?q=milestone%3AGo1.21.8+label%3ACherryPickApproved
> 🌱 Bump golang to v1.21.8

- README.md
jjbs have no mention of release-1.2 branch. This is a leftover trigger
> 🌱 Remove release-1.2 upgrade test description from README

- test/e2e/common.go
- test/e2e/healthchek.go
This PR makes to choose ip address from baremetal pool to access node in healthcheck tests. 
Node is not ssh able with provisioning ip address. 
Fixes #1527
> 🐛 e2e: Specify ip address pool for retreiving ip for accessing node

- baremetal/metal3data_manager.go
- Fix Metal3Data Manager log levels
Fixes #1551
> 🌱 Fix: Metal3Data Manager log levels

- Makefile
- hack/tools/release/notes.go
Support beta and RC releases in release note generator. Move some logic from Makefile to the release note generator, and then add nice unfolding summary section to hide details in beta/rc notes.
Fix previous release tag pattern detection in Makefile.
Remove ironic-image related notes, as it has proper release process itself now.
Below, I'll add the output of `v1.7.0-beta.0` beta output:
---
```yaml
Changes since v1.6.1
---
- Remove v1alpha5 API Version (#1525)
:rotating_light: This is a BETA RELEASE. Use it only for testing purposes. If you find any bugs, file an [issue](https://github.com/metal3-io/cluster-api-provider-metal3/issues/new/).
<details>
<summary>More details about the release</summary>
- e2e: Specify ip address pool for retreiving ip for accessing node (#1528)
- bump …
```
> 🌱 support beta and rc releases in release note generator

- hack/verify-release.sh
Ironic image is now released separately, no need to check them during CAPM3 release process anymore.
> 🌱 remove ironic image related checks in verify-release.sh

- README.md
> 🌱  Update e2e feature tests link

- scripts/environment.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/upgrade_clusterctl_test.go
Fixing and simplifying clusterctl upgrade tests.
Fixes #
> 🌱 Fixing and simplifying clusterctl upgrade tests

- test/e2e/common.go
- test/e2e/config/e2e_conf.yaml
- test/e2e/upgrade_clusterctl_test.go
Adding release markers in e2e config and clusterctl upgrade tests. These markers resolve to the latest patch release of the minor mentioned in the marker.
Fixes #
> 🌱 Add release markers to e2e config

- README.md
After migrating to prow jenkins operator and merging changes to trigger feature tests from prow this PR update the triggers on readme.md
> 📖 Update e2e feature tests triggers

- README.md
Updating readme after migrating e2e integration to prow jenkins operator
> 🌱 Update e2e integration triggers

- README.md
Update triggers on release 1.5
> 🌱 [release-1.5] Update triggers after migration to prow

- Makefile
- test/e2e/e2e_suite_test.go
- test/e2e/ip_reuse_test.go
- test/e2e/live_iso_test.go
- test/e2e/pivoting_based_feature_test.go
- test/e2e/remediation_based_feature_test.go
- test/e2e/upgrade_clusterctl_test.go
- test/e2e/upgrade_kubernetes_test.go
These vars are removed from project-infra https://github.com/metal3-io/project-infra/pull/703 , now it is throwing errors form project-infra [PRs ](https://jenkins.nordix.org/view/Metal3/job/metal3-ubuntu-e2e-integration-test-main/63/consoleFull) since we still have traces of these vars here in CAPM3, removing these unused vars.
> 🌱 Remove keep test env related vars and configs

- scripts/environment.sh
The version we upgrade from needs to be close enough (one minor version) to the version we upgrade to.
This fixes the kubernetes upgrade test that was broken with this error:
```
"admission webhook \"validation.kubeadmcontrolplane.controlplane.cluster.x-k8s.io\" denied the request: KubeadmControlPlane.cluster.x-k8s.io \"test1\" is invalid: spec.version: Forbidden: cannot update Kubernetes version from v1.28.1 to v1.30.0"
```
> 🌱 Bump Kubernetes upgrade from version

- README.md
- docs/e2e-test.md
This PR add documentation about k8s-upgrade tests which run on branches
Fixes #
> 📖 Add info about k8s-upgrade tests for release branches

- README.md
Link to the job https://jenkins.nordix.org/job/metal3-ubuntu-e2e-feature-test-main/ was changed. It should be reflected in the repo README.
> :book: Fix dead link to ubuntu feature test

- test/e2e/e2e_suite_test.go
- test/go.mod
This PR attempts to solve the log.SetLogger(...) was never called issue. 
In [CI e2e runs](url) we see the following stacktrace https://jenkins.nordix.org/view/Metal3/job/metal3-ubuntu-e2e-integration-test-main/176/consoleFull. This PR fixes the issue. 
```
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
12:49:34  Detected at:
12:49:34  	>  goroutine 292 [running]:
12:49:34  	>  runtime/debug.Stack()
12:49:34  	>  	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
12:49:34  	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
12:49:34  	>  	/home/metal3ci/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.4/pkg/log/log.go:60 +0xcd
12:49:34  	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithName(0xc0000cf040, {0x2669614, …
```
>  🌱  Fix log.SetLogger(...) was never called issue

- .github/dependabot.yml
This PR adds release-1.7 branch as the target branch. Also for this reason the current config adds the main branch as the target branch first and then copies the package ecosystems for release-1.7 branch.
>  🌱 Configure dependabot for release-1.7 branch

- .github/dependabot.yml
With the recent introduction of release branch configuration for dependabot, it is pushing bumps for minor versions of dependancies as well. We don't want minor version bumps for release branches. Setting it to patch versions.
> 🌱 Fix dependabot release branch config to bump only patch versions

- .github/dependabot.yml
Fixing patch version bumps via groups for release branches was probably a bad idea here https://github.com/metal3-io/cluster-api-provider-metal3/pull/1708. It has caused chaos and multiple different dependencies are now being grouped together in one PR. Current fix tries to tackle that by bringing back k8s group and then add an ignore rule for all dependancies in release branch to only allow patch bumps.
> 🌱 Group dependabot k8s bumps for release branches and ignore major, minor bumps for all dependancies

- .github/dependabot.yml
This PR configures dependabot to push only patch version bumps for github actions.
> 🌱 Bump only patch versions for release branch github actions

- Makefile
- examples/templates/clusterclass.yaml
This PR is a followup to #1405
It fixes issues with redundant test env related vars and configs that couses the test to fail at start. Those were removed in #1624 and should be also removed for clusterclass.
Also, it tries to fix issue with `{{ ds.meta_data.hostname }}'` reference reported [in the comment here](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1405#discussion_r1584187652).
It seems that,[ according to the cluster-api repository](https://github.com/kubernetes-sigs/cluster-api/blob/main/bootstrap/kubeadm/api/v1beta1/kubeadm_types.go#L231), `NodeRegistration.Name` defaults to hostname, so I believe referencing hostname explicitly here is redundant and minght be deleted.
> :bug: Clusterclass e2e test fix

- main.go
- main_test.go
TLS config code causes security linters to report false positive about TLS versions that can be configured.
This is porting over [CAPO PR 2037](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2037).
> 🌱 refactor TLS config

- baremetal/metal3datatemplate_manager.go
- controllers/metal3datatemplate_controller.go
This improves naming, adds comments, etc. No functional changes!
Fixes #
> 🌱 Minor cleaning of M3DT manager code

- .github/dependabot.yml
golang.org/x/* libs only release minor versions. No patch versions. We need to allow minor version bumps for these libs for release branches for this reason.
> 🌱 Allow minor version bumps for golang.org/x/* dependancies for release branch

- baremetal/metal3data_manager.go
- baremetal/metal3datatemplate_manager.go
- baremetal/metal3datatemplate_manager_test.go
- baremetal/metal3machine_manager.go
- baremetal/utils.go
- controllers/metal3data_controller.go
As the title describes. 
**Which issue(s) this PR fixes** 
Fixes #1356
> :bug: Protect Metal3Data and Metal3DataClaim with Finalizers

- .github/dependabot.yml
Dependabot is not picking up the ignore rule for `golang.org/x/*`  and hence not updating it. It might be the `*` is superseding everything. We will try to move it below the `*` rule to check if it helps dependabot picking it up
Fixes #
> 🌱 Move golang.org/x/* ignore rules after the * rule

- .github/workflows/release.yaml
- .golangci.yaml
- Dockerfile
- Makefile
- Tiltfile
- api/go.mod
- go.mod
- hack/build.sh
- hack/codegen.sh
- hack/gomod.sh
- hack/tools/go.mod
- hack/unit.sh
- test/go.mod
This PR bumps golang to v1.22.3 in Dockerfile, gomodules and container images for different tests in hack/ directory.
> 🌱 Bump golang to v1.22

- Dockerfile
- Makefile
Bump golang to 1.21.11 for:
- https://osv.dev/vulnerability/GO-2024-2887
- https://osv.dev/vulnerability/GO-2024-2888
> 🌱 bump golang to 1.21.11

- baremetal/metal3machine_manager.go
Changing errors in pause annotation functions from terminal to transient. When BMH is rebooted there is a chance we get a terminal error from these functions which can cause machines to be in a failed state.
> :bug: Changing errors in pause annotation functions from terminal to transient

- baremetal/metal3cluster_manager.go
- baremetal/metal3cluster_manager_test.go
- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- controllers/metal3machine_controller.go
This is a bug and it is a followup of https://github.com/metal3-io/cluster-api-provider-metal3/pull/1765. 
According to 
- https://github.com/fabriziopandini/cluster-api/blob/main/docs/book/src/developer/architecture/controllers/cluster.md, 
- https://github.com/fabriziopandini/cluster-api/blob/main/docs/book/src/developer/architecture/controllers/control-plane.md and 
- https://github.com/fabriziopandini/cluster-api/blob/main/docs/book/src/developer/architecture/controllers/machine-pool.md 
once `failureReason` or `failureMessage` surface on the CAPI object who is referencing the infra object, they cannot be restored anymore. Hence, CAPM3 should not clear them as well.
For the same reason, this PR is removing one of the occurrences of setError so as not to through terminal error while …
> 🐛 Remove clearError() function for infrastructure objects

- go.mod
- go.sum
- test/e2e/config/e2e_conf.yaml
- test/go.mod
- test/go.sum
Bumping BMO and minor fix in e2e config
> 🌱 Bump BMO and minor fix in e2e config

- .github/dependabot.yml
This PR adds release-1.6 branch config in dependabot.
> 🌱 Configure dependabot for release-1.6 branch

- examples/clusterctl-templates/clusterctl-cluster.yaml
The PR adds variables to override the default cidrblocks for the services and pods in the clusterctl-cluster.yaml template file. 
Fixes #
fixes #1484
>  📖 overridable variables in the clusterctl-cluster.yaml template

- scripts/fetch_manifests.sh
There is a possibility to miss same kinds of manifest in different namespace. So this PR will add the namespace directory in manifest collection to gather all the manifests which will improve debugging capability.
> 🌱Add namespace directory in manifest collection

- .github/dependabot.yml
This commit adds newly introduced multi-directories feature in dependabot. With this hopefully all the go modules would be bumped in one PR for a dependancy.
>  🌱  Optimize the dependabot config with multidir configuration

- hack/build.sh
- hack/codegen.sh
- hack/gomod.sh
- hack/manifestlint.sh
- hack/markdownlint.sh
- hack/shellcheck.sh
- hack/unit.sh
In CAPM3, there was only issues in codegen. Fix that, plus made it dynamically detect all the config and generated files, so they're included if they'd be generated elsewhere. It is in line with BMO generate.sh now.
For others, simply adding one shellcheck ignore for a optional check many people have enabled about, tired of seeing my editor complain :)
> 🌱 Fix issues in running local hack scripts

- scripts/ci-e2e.sh
- scripts/environment.sh
We no longer need to pass-thru KUBECTL_SHA256 as we download it and verify it from the downloaded checksum.
This depends on https://github.com/metal3-io/metal3-dev-env/pull/1437 merging first.
/hold
> :seedling: remove KUBECTL_SHA256 passthru

- baremetal/metal3remediation_manager.go
- baremetal/mocks/zz_generated.metal3remediation_manager.go
- config/rbac/role.yaml
- controllers/metal3remediation_controller.go
- controllers/metal3remediation_controller_test.go
- main.go
- test/e2e/common.go
- test/e2e/node_deletion_remediation.go
- test/e2e/remediation_based_feature_test.go
- test/go.mod
- test/go.sum
Currently, Metal3Remediation deletes the Node object to speed up the remediation, however, starting from Kubernetes 1.28 (GA) the new out-of-service taint is available, and CAPM3 can use it in place of deleting the node.
Fixes #1725
> ✨ Use Out-of-service taint in Node remediation in place of deletion

- .github/workflows/release.yaml
- .golangci.yaml
- Dockerfile
- Makefile
- Tiltfile
- controllers/metal3data_controller_test.go
- controllers/metal3datatemplate_controller_test.go
- hack/build.sh
- hack/codegen.sh
- hack/ensure-go.sh
- hack/gofmt.sh
- hack/gomod.sh
- hack/govet.sh
- hack/unit.sh
This is done since golang 1.20 is already deprecated
Fixes #1829
> 🌱 Bump golang 1.22 in release 1.6

- config/manager/manager.yaml
This ensures we have a useful termination message in the Pod if a manager exits unexpectedly.
Check: kubernetes-sigs/cluster-api#10580
> 🌱 Set terminationMessagePolicy to FallbackToLogsOnError for manager

- test/go.mod
- test/go.sum
https://osv.dev/GHSA-v23v-6jw2-98fq
It is not called in our code, but shows up in scans, so fix it.
> 🌱 bump docker/docker to v26.1.5

- metadata.yaml
- test/e2e/data/shared/main/metadata.yaml
This PR add CAPI v1.8 contracts
> 🌱 Add CAPI v1.8 contract

- scripts/fetch_manifests.sh
- scripts/fetch_target_logs.sh
Silence fetch logs and fetch manifests scripts as they are too noisy in jenkins logs which makes debugging unpleasant.
> 🌱 Silence fetch logs and fetch manifests scripts

- go.mod
- go.sum
- scripts/fetch_manifests.sh
- scripts/fetch_target_logs.sh
- test/go.mod
- test/go.sum
As we accidentally published BMO v0.8.0-rc.0 instead of v0.7.0-rc.0, we decided to skip release-0.7 and jump directly to release-0.8.
> :seedling: Bump BMO to v0.8.0-rc.0

- README.md
Update job triggers after release-1.8
> :book: Update job triggers documents

- README.md
The current badge has wrong job name, hence the badge appears as "not run".
> :seedling: Fix Centos e2e feature test badge

- controllers/metal3cluster_controller.go
- controllers/metal3data_controller.go
- controllers/metal3datatemplate_controller.go
- controllers/metal3labelsync_controller.go
- controllers/metal3machine_controller.go
- controllers/metal3machinetemplate_controller.go
- controllers/metal3remediation_controller.go
- main.go
This PR intends to use CAPI's ClusterCacheTracker https://github.com/kubernetes-sigs/cluster-api/pull/8744. However, since CAPM3 didn't use CAPI's remote NewClusterClient previously, this has to be done in two steps. Once this PR merges we can remove CAPM3's infra remote code and use CAPI's ClusterCacheTracker consistently.
> 🌱 Use CAPI's ClusterCacheTracker 

- .github/workflows/pr-verifier.yaml
Reuse PR verifier workflow from project-infra, so it is easier to maintain in a single place and reduces number of dependabot bump PRs targeting Github Actions, creating less noise.
> 🌱 Reuse PR verifier workflow from project-infra

- baremetal/metal3datatemplate_manager.go
- baremetal/metal3datatemplate_manager_test.go
- baremetal/mocks/zz_generated.metal3datatemplate_manager.go
- controllers/metal3data_controller.go
- controllers/metal3datatemplate_controller.go
- controllers/metal3datatemplate_controller_test.go
**What this PR does / why we need it:**
This PR fixes some non terminating Data/DataTemplate deletion. Some Metal3Data and Metal3DataTemplates were not destroyed  in rare circumstances due to missing reconcile events caused  by two distinct problems.
DataTemplate deletion has a watch over DataClaims but deletion  can only be performed when Data are completely removed (finalizer  executed) because Data resource requires the template.
We keep the facts that Data and DataClaims are still existing.
* When DataClaims exist, we do not remove the finalizer and wait   for reconcile events from the watch.
* If we have neither DataClaims or Data, we can safely  remove the finalizer. Deletion is complete.
* Otherwise we have to make a busy wait on Data deletion as there is no more claim to generate …
> :bug: Fix unterminating DataTemplate deletion

- controllers/metal3cluster_controller.go
- controllers/metal3data_controller.go
- controllers/metal3datatemplate_controller.go
- controllers/metal3labelsync_controller.go
- controllers/metal3machine_controller.go
- controllers/metal3machinetemplate_controller.go
If an otherwise succesful reconcile has a failure during the deferred patch process (typically conflict), the error is ignored, the resource is never modified and the reconciliation may never be retriggerred.
The fix propagates error err to global variable rerr.
**Which issue(s) this PR fixes**
Fixes #2002
> :bug: Propagate errors during patch to reconcile

- .github/dependabot.yml
Dependabot always bumps the CAPI main package and CAPI test package separately, which is waste of PRs and CPU time.
> :seedling: make CAPI a pattern in dependabot

- test/e2e/config/e2e_conf.yaml
After moving to new infra we are seeing flake where test times out while deleting cluster. This PR is increasing cluster delete timeout
- Example failure: https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3-periodic-centos-e2e-feature-test-release-1-7-features/50/consoleFull
- same failure in main: https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3-periodic-centos-e2e-feature-test-main-features/56/consoleFull
Fixes #
> 🌱 Increasing deletion timeout of cluster

- test/e2e/basic_integration_test.go
- test/e2e/common.go
- test/e2e/config/e2e_conf.yaml
- test/e2e/healthcheck.go
- test/e2e/integration_test.go
- test/e2e/ip_reuse_test.go
- test/e2e/logcollector.go
- test/e2e/md_remediations_test.go
- test/e2e/pivoting.go
- test/e2e/pivoting_based_feature_test.go
- test/e2e/remediation_based_feature_test.go
- test/e2e/upgrade_clusterctl_test.go
- test/e2e/upgrade_kubernetes_test.go
Adding more logs and fixing issues in healthcheck test.
This PR is 
- Making sure that Metal3RemediationTemplate is deleted after the healthcheck test is done.
- Wrapping "kubelet stop" command around Eventually so it does not fail. If eventually is not used the ssh connection fails sometimes, and failure is most of the time in the first "kubelet stop"(https://github.com/metal3-io/cluster-api-provider-metal3/blob/aa67ad5c84af874212be142c92aac195114556c9/test/e2e/healthchek.go#L51). Adding some wait eventually fixes the issue.
- Fixing FetchClusterLogs function, in case of any error FetchClusterLogs was returning and missing logs for remaining pods, that is fixed in this PR.
- Changing logs folder from "clusters" to "target_cluster_logs", in project …
> 🌱 Fixing issues in healthcheck test

- Makefile
Recently we have seen failure couple of times on our PR because of timeout on lint jobs. Previously we were having 10m timeout and now because of slow behavior during download or installation, it is taking more that 10 minutes to finish the job. So we are increasing the timeout to 15 minutes.
Example Error:
```
level=info msg="[loader] Go packages loading at mode 575 (imports|name|types_sizes|exports_file|deps|files|compiled_files) took 7m35.412810649s"
level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 128.217442ms"
level=info msg="Memory: 5297 samples, avg is 237.5MB, max is 1731.2MB"
level=info msg="Execution took 9m59.9976098[49](https://prow.apps.test.metal3.io/view/s3/prow-logs/pr-logs/pull/metal3-io_cluster-api-provider-metal3/2051/test/1849171193945395200#1:bui …
```
> 🌱 Increase test time for lint job to avoid failure because of timeout

- scripts/ci-e2e.sh
- scripts/environment.sh
- test/e2e/scalability_test.go
Add test that apply scaled number of bmh on dev-env using fakeIPA.
by default the test apply 100 BMH by batches each 20 BMHs applied in the same time 
TODO:
- Merge prow trigger: https://gerrit.nordix.org/c/infra/cicd/+/22355
- Merge DevEnv running fakeIPA PR: https://github.com/metal3-io/metal3-dev-env/pull/1450
> 🌱 Add scalability test

- test/e2e/data/infrastructure-metal3/bases/clusterclass-centos-kubeadm-config/clusterclass-centos-kubeadm-config.yaml
`KubeadmControlPlaneTemplate` has indentation mistake in template field which was not intercepted by webhook but caused weird issues
> 🐛 Fix clusterclass KubeadmControlPlaneTemplate file

- test/e2e/config/e2e_conf.yaml
- test/e2e/healthcheck.go
- test/e2e/remediation_based_feature_test.go
Fix healthcheck test flake 
ref: https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3-periodic-centos-e2e-feature-test-release-1-8-remediation/35/consoleFull 
the same fix on the main was in this PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/2046 
this is a manual backport of it, it skips other improvements of the main PR only backporting the fix.
> 🌱 Fix e2e healthcheck flake 

- api/v1beta1/metal3machinetemplate_webhook.go
- api/v1beta1/metal3machinetemplate_webhook_test.go
This mirrors the code in metal3machine webhook.  We are loosening the requirement on `Image`: when using `CustomDeploy`, `Image` is optional.
Ref: #1501
> :bug: Add CustomDeploy to metal3machinetemplate webhook

- Dockerfile
- Makefile
**What this PR does / why we need it**: Bump Golang 1.22.8 > 1.22.9 in release-1.8
> 🌱 Bump Golang to 1.22.9

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
We can configure bootstrap by setting `ConfigRef` or `DataSecretName`. Here, we correct the logic that determines if bootstrapping is ready to allow the data secret method as well as `ConfigRef`.
> :bug: bootstrap: add support for data secret

- hack/verify-release.sh
Make use of 'make go-version' rather than parse it from Dockerfile. Cherry-picked from IPAM.
> :seedling: simplify go version handling in verify-release.sh

- .github/workflows/golangci-lint.yml
- .golangci.yaml
- Dockerfile
- Makefile
- Tiltfile
- baremetal/metal3cluster_manager.go
- baremetal/metal3data_manager.go
- baremetal/metal3datatemplate_manager.go
- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- controllers/metal3cluster_controller.go
- hack/build.sh
- hack/codegen.sh
- hack/ensure-golangci-lint.sh
- hack/gomod.sh
- hack/unit.sh
- test/e2e/common.go
- test/e2e/remediation.go
1. Get rid of deprecated golangci-lint configs
2. add timeout to the action, otherwise it'll be timed out in 1 minute. 15 minutes is consistent with "make lint" timeout.
1. Fix new linter errors by removing the return value which is always nil (unparam linter), and thus meaningless.                                                                              
2. "exportloopref" is not needed from Go 1.22 onwards, replaced by "copyloopvar" in golangci-lint 1.60.2.                                                                                  
3. Ambiguous string warnings in Wrapf fixed.
4. Fix gosec issue about int32 overflow
Fixes: #2047
> :seedling: bump golang to 1.23.3 and golangci-lint to 1.60.3

- test/e2e/common.go
Recently we have experienced net.OpError error or http2streamerror error while downloading image quite frequently. This PR uses wget instead which is more resilient to http/network issues. We should change it to httpGet when network improves again.
>  🌱 Use wget while downloading image

- scripts/ci-e2e.sh
**What this PR does / why we need it**: 
Some e2e CI test are experiencing failure due to 
`./scripts/ci-e2e.sh: line 82: CAPM3RELEASEPATH: unbound variable`
`./scripts/ci-e2e.sh: line 92: CAPIRELEASEPATH: unbound variable`
script/ci-e2e.sh is using function `get_latest_release` that used to be set in the Metal-dev-env code base. In [this PR ](https://github.com/metal3-io/metal3-dev-env/pull/1474). Moving to use the function `get_latest_release_from_goproxy` that replaced the function should fix the problem. This function is no longer in CAPM3 release 1.8 but need to be patched to  releases 1.6 and 1.7.
> :bug: Use GOPROXY to download releases

- test/e2e/data/bmo-deployment/overlays/release-0.8/kustomization.yaml
- test/e2e/data/bmo-deployment/overlays/release-latest/kustomization.yaml
BMO manifests have removed kub-rbac-proxy due to deprecation. This PR adapts the e2e tests accordoingly.
For reference:
- https://github.com/metal3-io/baremetal-operator/pull/2102
- https://github.com/metal3-io/baremetal-operator/pull/2115
Fixes: #2121
> 🌱 Adapt e2e test after removal of kube-rbac-proxy in BMO manifest

- .gitignore
- test/e2e/data/.gitignore
`scripts/ci-e2e.sh` nowadays generates secrets as files for ironic and bmo overlays used in E2E, and at the end of the test, xml files to store result of the tests. All of these files need to be git-ignored.
> :seedling: Add ironic secrets files and junit e2e result file to gitignore

- docs/api.md
- docs/dev-setup.md
- docs/e2e-test.md
**What this PR does / why we need it**: Links have changed. Change them to ones that pass the link check. 
Fixes #
> :seedling: Change broken links

- controllers/suite_test.go
- main.go
As of Go 1.20 there is no reason to call Seed with a random value 
klogr.New()  is deprecated, klog.Background will automatically use the right logger
> 🌱 Removes depreacted klogr.New() and rand.Seed()

- Makefile
- scripts/ci-e2e.sh
- scripts/environment.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/data/fkas/kustomization.yaml
- test/e2e/data/fkas/resources.yaml
- test/e2e/data/infrastructure-metal3/bases/cluster-with-topology/cluster-with-topology.yaml
- test/e2e/data/infrastructure-metal3/bases/cluster-with-topology/kustomization.yaml
- test/e2e/data/infrastructure-metal3/cluster-template-centos-fake/kustomization.yaml
- test/e2e/data/infrastructure-metal3/clusterclass-metal3/clusterclass-metal3.yaml
- test/e2e/data/infrastructure-metal3/clusterclass-metal3/kustomization.yaml
- test/e2e/scalability_test.go
- test/go.mod
- test/go.sum
This PR introduces a scalability end-to-end test for CAPM3, applying multiple clusters using ClusterClass and reusing the existing ScaleSpec test framework from Cluster API (CAPI). The test is designed to simulate a large-scale environment with realistic configurations and is based on both FakeIPA and FKAS for authentication and endpoint management.
Test passed here: https://jenkins.nordix.org/view/Metal3/job/metal3-centos-e2e-scalability-test-main/9/console
> 🌱 Add e2e scalability test with fake systems

- hack/fake-apiserver/Dockerfile
This version is used in the other Dockerfiles, but not FKAS'. Bumping it to match.
This fixes go mod download failure in build action.
> :seedling: Bump Golang version to 1.23.4 in FKAS Dockerfile

- scripts/ci-e2e.sh
Set value of CAPM3RELEASE instead of relying on metal3-dev-env
Fixes #2181
> 🌱 Set value of CAPM3RELEASE instead of relying on metal3-dev-env

- README.md
Update build badges and test triggers in README.md for release-1.9.
> :book: update build badges and triggers in README.md

- Dockerfile
- Makefile
**What this PR does / why we need it**: Bump Golang to 1.23.4
> :seedling: Bump Golang to 1.23.4

- scripts/environment.sh
- test/e2e/basic_integration_test.go
- test/e2e/common.go
- test/e2e/integration_test.go
- test/e2e/ip_reuse.go
- test/e2e/ip_reuse_test.go
- test/e2e/pivoting_based_feature_test.go
- test/e2e/remediation_based_feature_test.go
- test/e2e/upgrade_kubernetes_test.go
Tests failing with following error after 1.9 because MachineSetPreflightChecks is moved to beta and the default value for it is set to true, before it was false:
```
I1227 11:18:04.605619    1 machineset_preflight.go:139] "Scale up on hold because MachineSet version (1.32.0) and ControlPlane version (1.31.2) do not conform to the kubernetes version skew policy as MachineSet version is higher than ControlPlane version (\"KubernetesVersionSkew\" preflight check failed); MachineSet version (1.32.0) and ControlPlane version (1.31.2) do not conform to kubeadm version skew policy as kubeadm only supports joining with the same major+minor version as the control plane (\"KubeadmVersionSkew\" preflight check failed). The operation will continue after the …
```
> 🌱 Remove CP scaling from e2e-feature-test

- scripts/ci-e2e.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/scalability_test.go
Scalability test is currently running with hardcoded number of clusters and number of clusters provisioned in parallel (both are set to 5). Also, the number of clusters cannot be lower than the number of fake nodes set by dev-env, but so far we have not taken it into account.
We should parameterize these numbers, and use the NUM_NODES param from dev-env as number of clusters. This could change in the future, when we include multi-node clusters into scalability test, but that won't likely happen in a near future.
> :seedling: Parameterize scalability test

- CONTRIBUTING.md
- README.md
- docs/e2e-test.md
Updating docs to accommodate release 1.9
Fixes #
> 📖 Updating docs for release 1.9

- test/e2e/config/e2e_conf.yaml
- test/e2e/node_reuse.go
- test/e2e/pivoting_based_feature_test.go
Fix e2e pivoting(node_reuse) test
In the Node Reuse test suite, we perform only patch uplifts rather than minor Kubernetes upgrades. This approach focuses solely on testing the Node Reuse feature during rollouts, as the specific details of the Kubernetes version update are not the primary concern.
Why This Approach?
During the Node Reuse test flow, there is a scenario where we scale MachineDeployment while the KCP is at version 1.32, and the MachineDeployment is at version 1.31.2. Recent changes in Cluster API introduced stricter checks via MachineSetPreflightChecks, which disallow this version mismatch. By limiting the tests to patch uplifts, we avoid these restrictions and ensure smooth execution of the Node Reuse test flow.
**Which issue(s) this …
> 🌱 Fix e2e pivoting(node_reuse) test

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- test/e2e/pivoting.go
Metal3Machine should not own BMH. It should consume it and release it when not needed. we already put a M3M consumer reference on BMH. This also would mean that for pivoting use cases we must add the clusterctl move labels in the CRDs. Otherwise BMH wont be pivoted to target clusters.
⚠️ Now, BMH object/CRD needs to have The object has the `clusterctl.cluster.x-k8s.io/move` label or the `clusterctl.cluster.x-k8s.io/move-hierarchy ` label to make sure BMH is pivoted to target cluster and removed from the source. `clusterctl.cluster.x-k8s.io/move` and `clusterctl.cluster.x-k8s.io/move-hierarchy` labels could be applied to single objects or at the CRD level (the label applies to all the objects).
We still keep the removal of owner reference code for one minor release cycle to facilitate …
> ⚠️  Remove Metal3Machine owner reference from BMH

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- test/e2e/pivoting.go
This reverts commit 715a0d05d1eb85a16e61f2f0a6e9151d290e3dda from https://github.com/metal3-io/cluster-api-provider-metal3/pull/1742
For currently unknown reason, this breaks pivoting. Despite adding the move labels to BMH, something is not moved or the move order is random and relationships are not properly reconciled after move. Move works like 10% of the time, so technically it works, but clearly timing or random affects it. This must be figured out before reapplying the change.
> :bug: Revert "Remove Metal3Machine owner reference from BMH"

- scripts/ci-e2e.sh
- test/e2e/live_iso_test.go
This commit:
- Changes the target string looked for via the serial logs by the ginkgo live-iso test code to verify that the live iso image has been booted properly.
- Removes the redundant use of the "cat" command from the boot verification process in the live-iso test
-  Changes the name of the live-iso test image to the new image that is uefi compatible.
This change is needed because the release1.8 e2e feature test are failing the live-iso boot verification even when the live-iso boot menu is visible in the serial logs.
> :bug: Fix live-iso serial console boot verification in e2e 

- test/e2e/data/ironic-deployment/overlays/release-latest/kustomization.yaml
We have removed the IP address from the CA in the source manifests. This breaks the replacement because it was selecting ALL certificates. This commit changes it to only select the ironic-certificate.
Fixes #
> 🌱 E2E: Fix Ironic kustomization

- api/v1beta1/metal3cluster_types.go
- api/v1beta1/metal3cluster_webhook.go
- api/v1beta1/metal3cluster_webhook_test.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clustertemplates.yaml
Instead of using `// +kubebuilder:default=true` to set a default value for `CloudProviderEnabled`, we are configuring defaults through a defaulting webhook. This approach avoids conflicts with the `NoCloudProvider` field in the validation webhook.
Using `kubebuilder:default` makes it impossible to distinguish whether the value of `CloudProviderEnabled` was explicitly set by the user or automatically assigned by the default. This distinction is critical because our validation webhook ensures that `CloudProviderEnabled` and `NoCloudProvider` do not conflict when both are set. If we rely on `kubebuilder:default`, the validation webhook cannot function as intended, as it cannot determine the source of the `CloudProviderEnabled` value. By shifting …
> 🌱 remove  kubebuilder:default=true for CloudProviderEnabled and set defaults in defaulting webhook

- Dockerfile
- Makefile
- hack/fake-apiserver/Dockerfile
Golang stdlib has issue in crypto/x509, fixed in golang 1.23.5. https://osv.dev/GO-2025-3373
Golang stdlib has issue in net/http, fixed in golang 1.23.5. https://osv.dev/vulnerability/GO-2025-3420
Both codepaths are used in the code.
> :bug: bump golang to 1.23.5

- README.md
OpenSSF CII Best Practices badge is expected to be repository specific. Our old badge is organization-wide, and does not quality for points in OpenSSF Scorecard for example.
I've done the CII analysis for CAPM3 alone, and we have received a passing badge for CAPM3 now.
> :book: update OpenSSF CII Best Practices badge

- test/e2e/data/ironic-deployment/overlays/release-27.0/kustomization.yaml
We have removed the IP address from the CA in the source manifests. This
breaks the replacement because it was selecting ALL certificates. This
commit changes it to only select the ironic-certificate.
See https://github.com/metal3-io/baremetal-operator/pull/2222
> 🌱 E2E: Adjust Ironic kustomization patch

- .github/workflows/golangci-lint.yml
- .github/workflows/lint-docs.yaml
- .github/workflows/pr-gh-workflow-approve.yaml
- .github/workflows/pr-verifier.yaml
We have "edited" as leftover workaround from days before we had "PR auto-reapprover" workflow in some jobs. In some jobs it is specifically needed as those workflows check the PR metadata which is covered by the edited. Add "ready_for_review" for consistency as a trigger type as well.
Similar PRs will be pushed across Metal3 repos to make things consistent after [discussion in ironic-image PR.](https://github.com/metal3-io/ironic-image/pull/620#pullrequestreview-2604851729)
> :seedling: workflows: sync pull_request trigger types

- Dockerfile
- Makefile
- hack/fake-apiserver/Dockerfile
This is to get rid of https://osv.dev/GO-2025-3447, where code path is called, but the vulnerability is only on ppc64, so it is not exploitable.
> :bug: bump golang to 1.23.6

- test/e2e/logcollector.go
- test/e2e/pivoting.go
- test/e2e/upgrade_clusterctl_test.go
**What this PR does / why we need it**: Rewrite fetch_manifest.sh into golang.
> :seedling: Rewrite fetch_manifest.sh into golang

- test/e2e/upgrade_clusterctl_test.go
**What this PR does / why we need it**: Metal3-periodic-e2e-clusterctl-upgrade-test-main is failing with: 
```
When testing cluster upgrade from releases (v1.8=>current) [clusterctl-upgrade] [It] Should create a management cluster and then upgrade all the providers
[2025-02-19T22:48:03.512Z] /home/metal3ci/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.9.4/e2e/clusterctl_upgrade.go:258
[2025-02-19T22:48:03.512Z] 
[2025-02-19T22:48:03.512Z]   [FAILED] Unexpected error:
[2025-02-19T22:48:03.512Z]       <errors.aggregate | len:4, cap:4>: 
[2025-02-19T22:48:03.512Z]       Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "[https://cert-manager-webhook.cert-manager.svc:443/validate?timeout=30s](https://cert-manager-webhook.cert-manager.svc/valid …
```
> 🌱 Debug clusterctl upgrade test failure

- test/e2e/e2e_suite_test.go
- test/e2e/pivoting.go
**What this PR does / why we need it**: New way of deploying requires e2e changes
> :bug: Add use of IPAMprovider to e2e tests

- baremetal/metal3data_manager.go
In bb4123346 a typo was introduced.
This is now eliminated again.
Correction of a typo introduced during refactoring.
None known to me.
> 🌱 Eliminate typo in networkDataSuffix

- docs/releasing.md
- hack/verify-release.sh
**What this PR does / why we need it**: Due to changes in the day IPAM is deployed manifests were deleted. Logic and links to these manifest have become obsolete.
> :book:  Remove IPAM manifests related links and check in release process

- Dockerfile
- Makefile
Bump golang to 1.23.7.
We'll have bunch of dependencies requiring this soon due vulns fixed in it.
Manual cherry-pick of #2375
> :seedling: bump golang to 1.23.7

- test/e2e/data/ironic-deployment/overlays/release-26.0/kustomization.yaml
Same as https://github.com/metal3-io/cluster-api-provider-metal3/pull/2308 but now for BMO release-0.8 that is being changed in https://github.com/metal3-io/baremetal-operator/pull/2276
We have removed the IP address from the CA in the source manifests. This
breaks the replacement because it was selecting ALL certificates. This
commit changes it to only select the ironic-certificate.
Fixes #
/hold
until https://github.com/metal3-io/baremetal-operator/pull/2276 is merged
> 🌱 E2E: Adjust Ironic kustomization patch for BMO 0.8

- Makefile
**What this PR does / why we need it**: Let's take `metal3-periodic-ubuntu-e2e-integration-test-release-1-9` as an example. This test runs `make` in `metal3-dev-env` where container images (with correct tags) get pulled. Some time later the test moves into `cluster-api-provider-metal3` folder and runs `make e2e-test`. At this time CAPM3, BMO and IPAM images will get pulled again but this time the tag is set to latest. This is unnecessary. This fix will pull the correct images if they are missing instead of always bulling images that are unused in many cases.
> :bug: Fix: pulling unused images in the middle of tests

- test/e2e/pivoting.go
After the IPAM provider name was changed from `metal3ipam` to `metal3` in https://github.com/metal3-io/metal3-dev-env/pull/1509, we need to do the same thing in capm3 e2e.
> :seedling: Change IPAM provider name to independent Metal3 IPAM in e2e test

- api/v1beta1/metal3data_types.go
- api/v1beta1/metal3datatemplate_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
Per godoc, it must be another paragraph in same comment block. Fix the two instances where they're not. This results documentation generate properly.
> :seedling: fix deprecation notice paragraph style

- .github/workflows/golangci-lint.yml
- .github/workflows/lint-docs.yaml
- .github/workflows/pr-gh-workflow-approve.yaml
- .github/workflows/pr-verifier.yaml
Re-adding "edited" trigger to testing workflows to workaround Dependabot workflow issue.
Ref: https://github.com/metal3-io/ironic-standalone-operator/issues/162
> :seedling: fix dependabot testing issues by re-adding "edited"

- test/e2e/common.go
- test/e2e/logcollector.go
- test/e2e/pivoting.go
- test/e2e/upgrade_clusterctl_test.go
Use `Logf` throughout the e2e tests instead of various fmt.Print* here and there.
Also cleanup the `writeToFile` to return an error instead of just logging them.
Fixes #
> 🌱 E2E: Unify logging and cleanup

- .gitignore
- test/e2e/data/cert-manager-test.yaml
- test/e2e/upgrade_clusterctl_test.go
The clusterctl-upgrade periodics that have been failing lately due to two issues. This is addressing the first of them. What happens is that the cert-manager webhook is not completely ready when we try to deploy ironic, even though we wait for the deployments to be `Available`. This is because it takes some time for the webhook to be registered, get a valid certificate and so on.
To fix this, we add a simple check that we can `Eventually` apply an Issuer and Certificate. When that succeeds we know the webhook is working.
Fixes #
> 🌱 E2E: Ensure cert-manager webhook is available

- test/e2e/config/e2e_conf.yaml
- test/e2e/data/cert-manager-test/certificate.yaml
- test/e2e/data/cert-manager-test/issuer.yaml
- test/e2e/data/cert-manager-test/kustomization.yaml
- test/e2e/data/cert-manager-test/namespace.yaml
- test/e2e/logcollector.go
- test/e2e/upgrade_clusterctl_test.go
The Metal3 IPAM was previously bundled with CAPM3. Now we deploy it
separately as a CAPI IPAM provider. In clusterctl upgrade tests going
from a version where IPAM is bundled, to a version where it is not, we
must install it after the upgrade.
This commit adds a post upgrade hook to the clusterctl upgrade tests
that installs the Metal3 IPAM.
NOTE: This also includes https://github.com/metal3-io/cluster-api-provider-metal3/pull/2380 we can merge that first or we can close it. I just wanted to make sure I don't hit that issue when testing the upgrade.
Fixes #
> 🌱 E2E: Install independent Metal3 IPAM after upgrade

- releasenotes/v1.10.0-beta.0.md
Round two of the release as the release workflow was broken.
> :rocket: Release v1.10.0-beta.0

- baremetal/metal3machine_manager.go
This PR improves how NICs without IP addresses are handled during MachineStatus population.
Skips adding NICs that have an ip address field to prevent invalid Metal3Machine status updates. Interfaces with no ip addresses are visible on bmh.
Otherwise,  patching Metal3Machine status will fail with following error:
`status.addresses[n].address: Invalid value: "": addresses[n].address in body should be at least 1 chars long`
Issue seen in [BML tests](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3-periodic-bml-integration-test-centos/318/)
> 🐛 Handle NICs without IP addresses

- releasenotes/v1.10.0.md
**What this PR does / why we need it**: Release v1.10.0
> :rocket: Release v1.10.0

- Makefile
- docs/e2e-test.md
- scripts/environment.sh
- test/e2e/config/e2e_conf.yaml
**What this PR does / why we need it**: Change Kubernetes version in e2e tests
Envtest uplift to 1.33 is done in a separate PR https://github.com/metal3-io/cluster-api-provider-metal3/pull/2535 because the is an issue with it.
> :seedling: Change Kubernetes version in e2e tests

- test/e2e/upgrade_clusterctl_test.go
Cert-manager was installed with the default version from CAPI in clusterctl upgrade tests. This commit changes it so that the version is taken from the e2e config.
Fixes #
> 🌱 E2E: Use cert-manager version from config

- scripts/ci-e2e.sh
- test/e2e/basic_integration_test.go
- test/e2e/common.go
- test/e2e/integration_test.go
Here we have introduced SKIP_APPLY_BMH var for skipping BMH creation from dev-env and added the code to apply the BMH from CAPM3  during basic and integration test.  These changes  will be part of the decoupling dev-env [issue](https://github.com/metal3-io/cluster-api-provider-metal3/issues/1996)
> 🌱Apply BMH from CAPM3 during test and skip BMH creation from dev-env

- scripts/ci-e2e.sh
- test/e2e/common.go
- test/e2e/ip_reuse_test.go
- test/e2e/pivoting_based_feature_test.go
- test/e2e/remediation_based_feature_test.go
- test/e2e/upgrade_kubernetes_test.go
This PR is a part of the SKIP_BMH_APPLY from dev-env side and it will apply from CAPM3 e2e test. This is a sub task which will fix part of the [issue](https://github.com/metal3-io/cluster-api-provider-metal3/issues/1996) which will add the BMH apply for feature tests.
> 🌱Apply BMH from CAPM3 e2e feature tests

- test/go.mod
- test/go.sum
Bump circl to v1.6.1 due GHSA-2x5j-vhc8-9cwm
Manual cherry-pick of https://github.com/metal3-io/cluster-api-provider-metal3/pull/2598
> 🌱 bump cloudflare/circl to v1.6.1 in /test

- Dockerfile
- Makefile
- hack/fake-apiserver/Dockerfile
Bump golang to 1.24.4.
This closes following uncalled/unrelated vulnerabilities in stdlib:
- https://osv.dev/GO-2025-3749
- https://osv.dev/GO-2025-3750
- https://osv.dev/GO-2025-3751
> :seedling: bump golang to 1.24.4

- Makefile
**What this PR does / why we need it**: Uplift Kubernetes to 1.33 in envtest
> :seedling: Uplift Kubernetes to 1.33 in envtest

- scripts/ci-e2e.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/md_remediations_test.go
**What this PR does / why we need it**: Improve deleting BMHs in BeforeEach. Before BMHs weren't deleted conditionally and test failed if there wasn't any BMHs applied yet. Removed unnecessary reapplying of BMHs after the test.
Fixes #
> :seedling: Fix deleting BMHs in md_remediation

- test/e2e/md_rollout_test.go
**What this PR does / why we need it**: Adopt MachineDeployment rolling upgrades test from CAPI: https://github.com/kubernetes-sigs/cluster-api/blob/main/test/e2e/md_rollout.go.
Fixes partially #1080
> :seedling: Adopt md_rollout test from CAPI

- hack/verify-release.sh
Fixes a small typo in verify release while checking mariadb image tag in release notes. Currently it wrongly complains about missing the line since the text doesn't match. It was missing `:`
> 🌱 Fix small typo in verify release

- test/e2e/healthcheck.go
Fix remediation test
We were comparing int32 with *int32 which was failing.
healthcheck.Status.CurrentHealthy was previously int32 now its *int32. This PR is fixing that, making sure we compare right types.
On line 182 `NodeStartupTimeoutSeconds: ptr.To(int32(0)),` is removed, this is not related to the fix, just refactor. it was not there before recent CAPI uplift but mistakenly added when converting v1beta1 object to v1beta2. 
Fixes #
> 🌱 Fix remediation test

- Dockerfile
- Makefile
- hack/fake-apiserver/Dockerfile
Bump golang to 1.24.6.
ref: https://groups.google.com/g/golang-announce/c/x5MKroML2yM
> :seedling: bump golang to 1.24.6

- .github/workflows/osv-scanner-scan.yml
The osv-scanner workflow should continue on error when uploading SARIF files and send Slack notifications for both vulnerabilities and workflow failures.
This ensures we get notified of any issues with the workflow.
Fixes #
> 🌱 Add continue-on-error and improve Slack notifications for osv-scanner

- test/e2e/data/ironic-deployment/overlays/pr-test/ironic_bmo_configmap.env
- test/e2e/data/ironic-deployment/overlays/release-26.0/ironic_bmo_configmap.env
- test/e2e/data/ironic-deployment/overlays/release-27.0/ironic_bmo_configmap.env
- test/e2e/data/ironic-deployment/overlays/release-29.0/ironic_bmo_configmap.env
- test/e2e/data/ironic-deployment/overlays/release-latest/ironic_bmo_configmap.env
We have seen flaky behavior during e2e test where IPA downloader was having longer time to download image and which was causing failure to have available ironic deployment. This will fix the slowness in IPA image download process.
> 🌱 Add IPA_BASEURI in ironic config to fix IPA download from cache

- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_test.go
- test/e2e/upgrade_clusterctl_test.go
- Delete child resources before machine
- remove postUpgradeWaitDeletingResources hook from clusterctl upgrade tests
Fixes https://github.com/metal3-io/cluster-api-provider-metal3/issues/2702
> 🐛 Delete child resources before machine

- docs/releasing.md
Alpha release mention was missing in release documentation. Alpha release should follow the same convention as beta release.
> 📖 Add Alpha release in release documentation

- docs/e2e-test.md
- scripts/ci-e2e.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/data/shared/capi/v1.12/metadata.yaml
- test/e2e/upgrade_clusterctl_test.go
**What this PR does / why we need it**: Enable testing main branch against CAPI's nightly builds which are built from its main branch.
> :seedling: Enable testing with CAPI nightly builds

- Dockerfile
- Makefile
DWARF is mostly needed when we are using Delve. DWARF was originally created for C language and the need for it in go and other debugging features is very small in general. As such, switch to using `-ldflags="-s -w"` by default and have an option to opt in for debugging info for those who would really need it. As a real example, we can gain ~30% (i.e. 26MB) image size reduction for capm3 controller and faster build process.
**Before**
Size profiler comparison: 
```
$ bloaty -d sections manager
FILE SIZE        VM SIZE
--------------  --------------
32.1%  25.6Mi  46.4%  25.6Mi    .text
22.6%  18.0Mi  32.7%  18.0Mi    .gopclntab
12.2%  9.70Mi  17.6%  9.70Mi    .rodata
7.9%  6.28Mi   0.0%      64    .debug_info
7.4%  5.90Mi   0.0%      64    .strtab …
```
> 🌱 cmd: strip out symbol table & DWARF debugging info

- test/e2e/data/infrastructure-metal3/v1.11/bases/cluster-with-topology/cluster-with-topology.yaml
- test/e2e/data/infrastructure-metal3/v1.11/bases/cluster/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-metal3/v1.11/bases/cluster/crs.yaml
- test/e2e/data/infrastructure-metal3/v1.11/bases/cluster/md.yaml
- test/e2e/data/infrastructure-metal3/v1.11/bases/clusterclass-centos-kubeadm-config/clusterclass-centos-kubeadm-config.yaml
- test/e2e/data/infrastructure-metal3/v1.11/bases/clusterclass-cluster/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-metal3/v1.11/bases/clusterclass-cluster/crs.yaml
- test/e2e/data/infrastructure-metal3/v1.11/bases/clusterclass-cluster/md.yaml
- test/e2e/data/infrastructure-metal3/v1.11/bases/clusterclass-ubuntu-kubeadm-config/clusterclass-ubuntu-kubeadm-config.yaml
- test/e2e/data/infrastructure-metal3/v1.11/bases/clusterclass/clusterclass.yaml
- test/e2e/data/infrastructure-metal3/v1.11/bases/opensuse-leap-kubeadm-config/kustomization.yaml
- test/e2e/data/infrastructure-metal3/v1.11/bases/opensuse-leap-kubeadm-config/opensuse-leap-kubeadm-config.yaml
- test/e2e/data/infrastructure-metal3/v1.11/bases/ubuntu-kubeadm-config/ubuntu-kubeadm-config.yaml
- test/e2e/data/infrastructure-metal3/v1.11/cluster-template-centos-md-remediation/md.yaml
- test/e2e/data/infrastructure-metal3/v1.11/cluster-template-centos-md-remediation/mhc.yaml
- test/e2e/data/infrastructure-metal3/v1.11/cluster-template-opensuse-leap/kustomization.yaml
- test/e2e/data/infrastructure-metal3/v1.11/cluster-template-ubuntu-md-remediation/md.yaml
- test/e2e/data/infrastructure-metal3/v1.11/cluster-template-ubuntu-md-remediation/mhc.yaml
- test/e2e/data/infrastructure-metal3/v1.11/clusterclass-metal3/clusterclass-metal3.yaml
1.11 templates were using v1beta1 CAPI, this PR is changing it to v1beta2
Fixes #
> 🌱 Fix 1.11 cluster templates to use v1beta2

- Dockerfile
- Makefile
- hack/fake-apiserver/Dockerfile
New go patch including security fixes: https://groups.google.com/g/golang-announce/c/4Emdl2iQ_bI
Fixes #
> 🌱 Bump golang to v1.24.8
