- README.md
- docs/getting-started.md
This PR does documentation update related to releasing v1alpha3
> 📖 Update documentation for release v1alpha3

- config/manager/manager_image_patch.yaml
This PR changes the image used to be the release-0.3 branch
> 🏃 Change manager image tag to follow release-0.3 branch

- baremetal/metal3machine_manager.go
> :bug: UpdateObject function should operate on a deepcopy of the object

- baremetal/metal3machine_manager.go
- controllers/metal3machine_controller.go
This patch make release-0.3 changes issued in [48](https://github.com/metal3-io/cluster-api-provider-metal3/issues/48)
> 🐛This PR fixes issue #48

- docs/api.md
- docs/architecture.md
This PR updates the versions in the docs
Fixes #55
> 📖 Fix version in docs

- docs/api.md
- docs/architecture.md
This PR fixes the version in the documentation to v1alpha3
Fixes #55
> 📖 Replace versions in docs

- baremetal/metal3machine_manager_test.go
- go.sum
https://github.com/metal3-io/cluster-api-provider-metal3/issues/46
> add tests for updateObj and createObj

- api/v1alpha2/doc.go
- api/v1alpha2/metal3machine_types.go
- api/v1alpha3/doc.go
- api/v1alpha3/metal3machine_types.go
- api/v1alpha4/doc.go
- api/v1alpha4/metal3machine_types.go
- baremetal/manager_factory_test.go
- baremetal/metal3cluster_manager.go
- baremetal/metal3machine_manager.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
- docs/api.md
- docs/architecture.md
- docs/deployment_workflow.md
- docs/dev-setup.md
- examples/generate.sh
This PR fixes small nits and comments.
> :bug: Fix small nits

- baremetal/metal3machine_manager.go
- go.sum
> :bug: CAPM3 should not select a BMH that is paused

- clusterctl-settings.json
Fix provider name & version in clusterctl-setting.json
> :bug: Fix provider name & version in clusterctl-setting

- docs/api.md
This PR updates the documentation of the API for Metal3DataClaim objects
> 📖 Update API docs for Metal3DataClaim objects

- baremetal/utils_test.go
- hack/golint.sh
This PR adds a golint script and fixes the fmt script to fail if it changes a file. This is to improve the CI jobs.
> 🏃 Add a golint hack script and fix fmt to fail in case of changes

- api/v1alpha2/conversion.go
- api/v1alpha4/metal3datatemplate_webhook_test.go
- baremetal/metal3cluster_manager_test.go
- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
- baremetal/metal3datatemplate_manager.go
- baremetal/metal3datatemplate_manager_test.go
- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- baremetal/utils_test.go
- controllers/metal3data_controller_test.go
- controllers/metal3datatemplate_controller.go
- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_test.go
This removes the warning issued by some formatting tools
> 🏃 use gofmt -s to simplify the code

- OWNERS
Add reviewers who are not already in the approvers list based on the
policy described in https://github.com/metal3-io/metal3-docs/pull/93
/hold
> 🏃 initialize reviewers list

- Makefile
- config/bmo/bmo_image_patch.yaml
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- config/ipam/pull_policy_patch.yaml
- go.mod
- go.sum
- hack/gofmt.sh
This PR updates the image and pull policy patches for the IPAM controller. It also adds some verbosity to the gofmt job and update BMO.
> 🏃 Update config image patches and pull policy

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
In order to properly pivot the BMH, we need to set two annotations
on the BMH, one to pause the reconciliation, the other with the
marshalled status. This commit adds the second annotation as part
of the pausing workflow.
> 🐛 Add an annotation with BMH status when pausing it

- OWNERS
> 🏃 Add fmuyassarov, furkatgofurov7, jan-est as reviewer

- docs/api.md
This PR adds unhealthy annotation documentation into api documentation of CAPM3.
> 📖  Add unhealthy annotation documentation

- .gitignore
- Makefile
- README.md
- Tiltfile
- docs/dev-setup.md
- examples/clusterctl-templates/clusterctl-cluster.yaml
- hack/ensure-kind.sh
- hack/gen_tilt_settings.sh
- hack/kind_with_registry.sh
- hack/kustomize-sub.sh
- hack/tools/go.mod
- hack/tools/go.sum
- tilt-provider.json
- Add Tiltfile
- Update Makefile
- Update docs
- Update cluster template to remove problematic spaces
- update hack scripts
- add tilt-provider.json for integration with CAPI
> 🌱 Add Tilt setup for easier development

- docs/getting-started.md
This PR adds note regarding mapping K.Node <--> BMH after pivoting
Fixes #70
> 📖  Add note about node<--->bmh mapping after pivoting

- config/bmo/kustomization.yaml
Fixes # Add missing namespace ironic configmap
> :bug: Add missing namespace ironic configmap

- docs/getting-started.md
Fixes incorrect variable in the getting-started doc.
> :bug: Fix incorrect variable in the doc

- docs/dev-setup.md
This PR fixes couple of small flaw in the dev-setup.md doc.
> 🐛 Update dev-setup.md

- api/v1alpha4/metal3dataclaim_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
Signed-off-by: Ma Xinjian <maxj.fnst@cn.fujitsu.com>
Fixes #
> Fix wrong comment about Metal3DataClaim

- hack/fetch_ext_bins.sh
Signed-off-by: Ma Xinjian <maxj.fnst@cn.fujitsu.com>
```
$ make test
$ ls -l /tmp/ | grep kubebuilder-tools
-rw-r--r--  1 root root 52352311 Nov 25 16:33 kubebuilder-tools-1.16.4-linux-amd64.tar.gz
```
Fixes #
> Cleanup downloaded file

- OWNERS
reorders OWNERS file alphabetically.
> 🌱 reorder OWNERS alphabetically

- api/v1alpha2/metal3cluster_types.go
- api/v1alpha2/metal3machine_types.go
- api/v1alpha2/metal3machinetemplate_types.go
- api/v1alpha3/metal3cluster_types.go
- api/v1alpha3/metal3machine_types.go
- api/v1alpha3/metal3machinetemplate_types.go
- api/v1alpha4/metal3cluster_types.go
- api/v1alpha4/metal3data_types.go
- api/v1alpha4/metal3dataclaim_types.go
- api/v1alpha4/metal3datatemplate_types.go
- api/v1alpha4/metal3machine_types.go
- api/v1alpha4/metal3machinetemplate_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
Add more shortNames for metal3 config objects in a consistent way.
> 🌱Add more shortNames for metal3 config objects

- .github/ISSUE_TEMPLATE/bug_report.md
Update template for bug reporting in CAPM3.
> 🌱 Update template for bug reporting

- hack/ensure-kind.sh
Fix comparison of kind versions.
> Fix kind version comparison

- docs/architecture.md
- docs/deployment_workflow.md
- docs/dev-setup.md
- docs/getting-started.md
> 🐛 Use consistent spelling for Ironic

- docs/dev-setup.md
Update instruction for using Tilt environment
> Update instruction for using Tilt environment

- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
This PR updates the image patch and kustomization for the IPAM controller. 
Fixes #
> 🌱 Update ipam config image patch and kustomization

- api/v1alpha4/metal3machine_types.go
- baremetal/metal3cluster_manager_test.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
- controllers/metal3labelsync_controller.go
Signed-off-by: Zou Yu <zouy.fnst@cn.fujitsu.com>
Fixes #
> :seedling: Fix some typos

- baremetal/metal3machine_manager_test.go
Fix unnecessary code duplication in test code.
> 🐛 Fix code duplication

- baremetal/metal3data_manager.go
As per discussion in [comment](https://github.com/metal3-io/cluster-api-provider-metal3/pull/169#discussion_r624987647).
Fixes #
> 🐛 Cleanup code duplication from data manager

- OWNERS
Adding Furkat and Anwar as approvers as agreed. Russel is being removed as per his request.
> ✨ Add Furkat and Anwar as approvers

- Makefile
- docs/dev-setup.md
- examples/controlplane/controlplane.yaml
- templates/test/cluster-template-prow-ha.yaml
- templates/test/cluster-template-prow-single-master.yaml
- test/e2e/config/e2e_conf.yaml
This PR introduced changes needed for examples to use predefined BMH status.
> 🌱 Use predefined BMH status in examples

- Makefile
- docs/dev-setup.md
- examples/controlplane/controlplane.yaml
Port changes from #212 to branch master.
> Use predefined BMH status in examples (master)

- hack/e2e/config_ubuntu.sh
- scripts/ci-e2e.sh
Make changes required to run e2e tests in the CI. Extracted from the #218 PR.
> e2e: Adjust e2e tests to running in the CI

- OWNERS
I can't commit to being an approver in this repo, so I am removing myself.
> :seedling: remove dhellmann from owners

- api/v1alpha4/conversion_test.go
Adds conversion tests for v1a5 type.
> ✨ Add conversion tests for v1alpha5 API

- baremetal/metal3cluster_manager_test.go
- baremetal/metal3data_manager_test.go
- baremetal/metal3datatemplate_manager_test.go
- baremetal/suite_test.go
- controllers/metal3cluster_controller_integration_test.go
- controllers/metal3data_controller_test.go
- controllers/metal3datatemplate_controller_test.go
- controllers/metal3labelsync_controller_test.go
- controllers/metal3machine_controller_integration_test.go
- controllers/metal3machine_controller_test.go
- controllers/suite_test.go
- main.go
We don't have v1 APIs yet, so let's be explicit.
> ✨ Use correct aliases for capm3 api

- OWNERS
Synchronize OWNERS file between master and release-0.4 branches so that those in the OWNERS file of the master branch are able to approve/lgtm in release-0.4 branch too.
> 🌱 Sync OWNERS file between master and release-0.4 branches

- controllers/metal3labelsync_controller.go
https://github.com/metal3-io/cluster-api-provider-metal3/issues/238
Fixes # https://github.com/metal3-io/cluster-api-provider-metal3/issues/238
> 🐛 Increase retry interval in label-sync controller to 30 seconds

- controllers/metal3cluster_controller.go
This PR implements https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20210203-externally-managed-cluster-infrastructure.md for the Metal3 provider.
**Release note**:
```release-note
Metal3 provider now supports the externally managed annotation as documented here https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20210203-externally-managed-cluster-infrastructure.md
```
> ✨Implement externally managed annotation

- main.go
Addresses [comment](https://github.com/metal3-io/cluster-api-provider-metal3/pull/167#discussion_r652656419) from #167 .
> ✨ Align flag names with k8s components

- OWNERS
You can find the list of pull request from @namnx228 in https://github.com/metal3-io/cluster-api-provider-metal3/pulls?q=is%3Apr+is%3Aclosed+author%3Anamnx228 or the commits in https://github.com/metal3-io/cluster-api-provider-metal3/commits?author=namnx228.
> 🌱 Add namnx228 to the reviewers list

- .github/workflows/release.yaml
- .gitignore
- Makefile
- hack/tools/release/notes.go
This automates releasing process via GitHub actions. 
Whenever there is a new tag pushed to the repository,
GitHub actions will execute `release.yaml`, which will
run `make release-notes`, `make release-manifests`
and and publish all the generated artifacts.
> ✨ Automate releasing process with GitHub actions

- hack/e2e/environment.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/node_reuse_test.go
- test/e2e/remediation_test.go
Fix node_reuse flakiness such as:
https://jenkins.nordix.org/view/Metal3/job/airship_metal3io_capi_m3_master_e2e_test_centos/24/console
https://jenkins.nordix.org/view/Metal3/job/airship_metal3io_capi_m3_master_e2e_test_centos/23/console
https://jenkins.nordix.org/view/Metal3/job/airship_metal3io_capi_m3_master_e2e_test_centos/18/console
https://jenkins.nordix.org/view/Metal3/job/airship_metal3io_capi_m3_master_e2e_test_ubuntu/30/console
https://jenkins.nordix.org/view/Metal3/job/airship_metal3io_capi_m3_master_e2e_test_ubuntu/16/console
> 🐛 Fix node_reuse and remediation flakiness

- README.md
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>
> 🌱 Fix an outdated URL in README.md

- hack/e2e/environment.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/node_reuse_test.go
- test/e2e/remediation_test.go
This PR fixes node_reuse and remediation  flaky issues on release-0.5
> 🐛 Fix flaky issues on node reuse remediation tests

- docs/api.md
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>
> 📖  Fix a typo in docs/api.md

- README.md
**What this PR does / why we need it**
Add pivoting and provider installation instructions.
It is quite important to list the steps, because I have
seen quite many folks on the community having issues
with installation of the provider, especially after BMO
was taken out.
> 📖 Add pivoting and provider installation instructions

- config/ipam/image_patch.yaml
> ✨ Update IPAM image reference

- baremetal/metal3machine_manager.go
Add a function to retrieve nodes using labels.
Needed for avoiding code duplication as nodes will be retrieved using new and legacy labels of the providerID.
Required by: https://github.com/metal3-io/cluster-api-provider-metal3/pull/324
> 🌱 Add a function to retrieve nodes using labels

- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
- baremetal/suite_test.go
Add provideruid field in m3mdata resource.
The new field is to be consumed by the new providerID logic https://github.com/metal3-io/cluster-api-provider-metal3/pull/324
> ✨ Add providerID in m3mdata

- test/e2e/cert_rotation_test.go
This PR fixes the flaky issue: 
https://jenkins.nordix.org/job/airship_metal3io_capi_m3_v1b1_e2e_test_ubuntu/143/console 
In details, in the e2e cert rotation test, right after the pod is running, the secrets are deleted.
However, the containers in the pod may not yet execute the inotify/kill part of its entrypoint script. Maybe because of infra delay, it needs more time to reach this step. So the inotify and the-thing-need-to-be-kill are not there when the secret are deleted. That is the reason why the container doesn't restart as expected.
> Fix the flaky issue with cert-rotation

- OWNERS
Add @smoshiur1237  as reviewer based
on his contribution (10 min commits).
> 🌱 Add smoshiur1237 as reviewer

- go.mod
- go.sum
Address security  vulnerability https://github.com/advisories/GHSA-77vh-xpmg-72qh
> 🐛 Require image-spec v1.0.2

- test/e2e/config/e2e_conf.yaml
- test/e2e/node_reuse_test.go
This PR adds image and binary upgrade onto node_reuse test
> 🌱Cover upgrade test requirements in node reuse e2e tests

- README.md
This PR documents e2e trigger phases to the README file
> 📖 Introduce trigger phrases for e2e test in README

- go.mod
- go.sum
This PR keeps up with https://github.com/kubernetes-sigs/cluster-api/pull/5886/
> 🌱  Uplift to github.com/docker/docker v20.10.11

- go.mod
- go.sum
> 🐛 Uplift containerd to v1.5.9

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
Rewrites nodeReuse related MachineDeployment/MachineSet tests in m3machinemanager
> 🐛 Rewrite MachineDeployment/MachineSet tests in m3machinemanager

- baremetal/manager_factory_test.go
- baremetal/metal3machine_manager_test.go
Test coverage:
1. mangae_factory.go covers 42.9% --> 100%
2. metal3machine_mangager.go covers 73.5%
> 🌱Add test entries for metal3machine manager and manager_factory

- README.md
- test/e2e/node_reuse_test.go
Airship name from CI jenkins view have been deprecated
> ✨ Update CI badges and artifactory image path with metal3

- docs/dev-setup.md
Add instruction for accessing tilt dashboard remotely and locally
> 📖 Add instruction for accessing tilt dashboard remotely and locally

- OWNERS
Jan is no longer working on this project.
> :seedling: Remove jan as an active reviewer

- OWNERS
Add @fmuyassarov as an approver to the repo as discussed in the email.
> Add fmuyassarov as an approver

- controllers/metal3machinetemplate_controller.go
Normally, automated cleaning mode (either `disabled` or `metadata`) is replicated from a
Metal3MachineTemplate spec to Metal3Machine spec. It is allowed to patch Metal3Machine's
`automtedCleaningMode` directly, and if that's the case  CAPM3 controller should notice it,
request a reconciliation for the Metal3MachineTemplate and reset the `automatedCleaningMode`
on the Metal3Machine to the same as in Metal3MachineTemplate. This ensures that the source
of the truth is always in the template.
> 🐛 Reconcile Metal3MachineTemplate on Metal3Machine events

- README.md
Related to https://gerrit.nordix.org/c/infra/cicd/+/12409
> 📖 Update ubuntu based e2e tests trigger phrases

- README.md
Updates root readme file with latest changes since release v1.1.0 is out and CAPI release v1.1.2 is being used as of now. 
Also, updates a bit deployment process workflow
> 📖 Update root README file

- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
- baremetal/suite_test.go
Remove providerID field from m3mdata
Reverts https://github.com/metal3-io/cluster-api-provider-metal3/pull/369
> Remove providerID field from m3mdata

- test/e2e/node_reuse_test.go
This PR adds: 
- Fix update nodes conflict when untainting by using patch instead of update https://jenkins.nordix.org/view/Metal3%20Main/job/metal3_main_v1a5_e2e_test_ubuntu/22/console
> 🐛 Replace update taints with patch node taints

- baremetal/metal3data_manager_test.go
- baremetal/metal3datatemplate_manager_test.go
- baremetal/metal3machine_manager_test.go
- baremetal/metal3remediation_manager_test.go
- baremetal/suite_test.go
- baremetal/utils_test.go
- controllers/metal3data_controller_test.go
- controllers/metal3datatemplate_controller_test.go
- controllers/metal3labelsync_controller_test.go
- controllers/metal3machine_controller_integration_test.go
- controllers/metal3machine_controller_test.go
- controllers/metal3machinetemplate_controller_test.go
- controllers/suite_test.go
> 🌱Parameterize namespace name in tests

- OWNERS
OWNERS file in main branch ref: https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/OWNERS
> 📖 Synchronize OWNERS file in release-0.5 branch with main

- docs/api.md
- scripts/ci-e2e.sh
metal3 Dev-env default branch was changed to main this PR updates CAPM3 accordingly
> 🌱 Change dev-env default branch from master to main in e2e script

- OWNERS
I was added to the OWNERS file when bootstrapping the project/repo, but I've not found time to be an active reviewer on this repo, so removing myself to make that clear
> 🌱 Remove hardys from OWNERS

- README.md
- docs/e2e-test.md
Add some docs on e2e tests, especially upgrade BMO/Ironic
> 📖 Document e2e tests

- go.mod
- go.sum
- hack/tools/go.mod
Fixes # Also fixing the modules path in hack/tools/go.mod
> ✨ Uplift BMO modules to latest (March 2022)

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
> 🌱 Uplift IPAM in gomod and kustomize files

- baremetal/metal3remediation_manager_test.go
This PR adds following unit tests for metal3remediation_manager:
- GetUnhealthyHost (new entries added)
- SetUnhealthyAnnotation
- SetRebootAnnotation
- TimeToRemediate
41.2 -->> 74% coverage is done.
> 🌱 Add and update unit tests for metal3remediation manager.

- baremetal/metal3data_manager.go
**What this PR does / why we need it**: 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:  
Fixes #250
> :seedling: Improve logging of Data creation

- baremetal/metal3machine_manager_test.go
This PR adds two unit tests entries to the Delete function of metal3machine_manager.go file.
> 🌱 Expand unit tests for node reuse feature in Delete function

- baremetal/metal3machine_manager.go
In many CI failed jobs (e.g [jenkins_logs](https://jenkins.nordix.org/view/Metal3%20Main/job/metal3_main_v1b1_e2e_test_ubuntu/101/console))  the machine resources logs state the error `unable to update the target node with providerID: Operation cannot be
fulfilled on nodes "test1-lm7wz": the object has been modified; please apply
your changes to the latest version and try again` 
This is caused by the providerID update added in the PR #563 
This PR replaces the update with patch in order to avoid these conflicts when updating nodes.
> 🐛 Patch instead of update when setting the node providerID

- docs/dev-setup.md
> :book: Fix an outdated link in dev-setup.md

- baremetal/metal3data_manager.go
Modify the returned error message to be more accurate.
> :seedling: Modify the error message in createSecrets

- baremetal/metal3remediation_manager.go
- baremetal/metal3remediation_manager_test.go
> :seedling: Fix nil point error in metal3remediation_manager

- Tiltfile
- examples/generate.sh
- hack/gen_tilt_settings.sh
Follows https://github.com/kubernetes-sigs/cluster-api/pull/6432
> 🌱 Update cert-manager to v1.7.2

- baremetal/metal3cluster_manager_test.go
Improve unit test coverage:
CountDescendants: 75% -> 100% coverage
listDescendants: 72.7% -> 77.8% coverage
> :seedling: Add test case to descendantsTestCases

- baremetal/metal3machine_manager_test.go
This PR fixes unit tests of chooseHost function:
- pass objects porperly to fake client
- add available state to hosts
- fix expectedHostname condition
> 🐛 Fix choose host function unit tests

- hack/e2e/environment.sh
- test/e2e/node_reuse_test.go
Add Centos 9 support to v0.5 e2e tests,
> :seedling: Add Centos 9 support for release-0.5 branch e2e test

- scripts/ci-e2e.sh
- test/e2e/config/e2e_conf.yaml
**What this PR does / why we need it:**
Parameterizes the CAPI and CAPM3 versions in e2e conf.
> 🌱 e2e conf parameterization

- baremetal/metal3data_manager_test.go
- baremetal/metal3datatemplate_manager_test.go
- baremetal/metal3machine_manager_test.go
- baremetal/metal3remediation_manager_test.go
- baremetal/suite_test.go
- baremetal/utils_test.go
- controllers/metal3data_controller_test.go
- controllers/metal3datatemplate_controller_test.go
- controllers/metal3labelsync_controller_test.go
- controllers/metal3machine_controller_integration_test.go
- controllers/metal3machinetemplate_controller_test.go
- controllers/suite_test.go
Change hard coded object names and uuids
fixes: https://github.com/metal3-io/cluster-api-provider-metal3/issues/592
> Change hard coded object names and uuids

- README.md
This PR also renames release.yaml to release.yml. This is a test to check if the extension is bothering github actions
>  🌱 Name CI test badges correctly

- .github/workflows/kubesec.yml
- template/sarif.tpl
> 🌱 Add kubesec for CAPM3

- test/e2e/pivoting_test.go
Add CAPI labels on hardwareData CRD (added in https://github.com/metal3-io/baremetal-operator/pull/1099) so that hadwareData object is also pivoted as part of clusterctl move operation. Ref: https://github.com/metal3-io/metal3-dev-env/pull/969
> 🐛 Fix e2e pivoting by adding capi labels on hardware data crd

- baremetal/metal3cluster_manager.go
- baremetal/metal3cluster_manager_test.go
Avoid returning err with nil in error cases
> :seedling: fix ControlPlaneEndpoint in metal3cluster_manager

- baremetal/metal3machine_manager.go
- baremetal/metal3remediation_manager.go
- controllers/metal3data_controller.go
- controllers/metal3labelsync_controller.go
The form should be key:value pair as the definition:
func (l Logger) Info(msg string, keysAndValues ...interface{})
🐛 
A panic will occur.
Fixes #
> 🌱 Improve logging in machine manager

- OWNERS
To contribute further to the community, I would like to be a reviewer. Here is my contribution(10 min commits):
https://github.com/metal3-io/cluster-api-provider-metal3/pulls?q=is%3Apr+is%3Aclosed+author%3Azhouhao3
> 🌱 Add zhouhao3 as a reviewer

- Makefile
- scripts/ci-e2e.sh
- scripts/environment.sh
depends on https://github.com/metal3-io/project-infra/pull/409
> 🌱 Use ginkgo focus instead of boolean

- OWNERS
What this PR does / why we need it:
This PR is syncing owner list with main branch.
> 📖 Synchronize OWNERS file with main branch

- baremetal/metal3machine_manager.go
> :seedling: fix error panic

- docs/e2e-test.md
- scripts/ci-e2e.sh
- test/e2e/live_iso_test.go
What this PR does / why we need it:
e2e test with live iso.
Discussion on slack regarding live iso:
https://kubernetes.slack.com/archives/CHD49TLE7/p1653654187046809
> 🌱 Add live ISO e2e test

- README.md
Related to:
https://github.com/metal3-io/project-infra/pull/415
https://gerrit.nordix.org/c/infra/cicd/+/14151
Edit: Also updates ref links to daily jobs in root README file
> 📖 Update trigger phrases with new changes in CI

- test/e2e/live_iso_test.go
Which issue(s) this PR fixes:
Fixes the cleanup of cluster after live-iso test. Replaced dumpSpecResourcesAndCleanup with just deprovisioning of node, in live iso test we are not creating target cluster, we just provision one node with live ISO image and when test is done we have to deprovision it. Function dumpSpecResourcesAndCleanup was not working because there was no target cluster, so now we are just deprovisioning the live ISO booted node.
> 🐛 Live ISO cleanup fix

- OWNERS
I can no longer commit to contributing to Metal3 as I've moved to another project.
/cc @kashifest @furkatgofurov7
> 🌱 Move fmuyassarov to emeritus_approvers

- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
clean up return parameters and update comments to reflect current behaviour
I've refactored the IP address allocation and release functions to share the logic used to determine from which pools to allocate.
I've also cleaned up a few things in the process
- `releaseAddressFromM3Pool` no longer returns whether it was successful or if reconciliation should be requeued, both were unused
- both `getAddressFromM3Pool` and `releaseAddressFromM3Pool` no longer interact with the addresses map, as that was not necessary. They also no longer check whether a pool was processed already, as each pool will only be processed once.
This is in preparation for implementing CAPI IPAM Contract support (#671), so I've renamed `getAddressFromM3Pool` and …
> 🌱 share logic between ip address allocation and release

- test/e2e/live_iso_test.go
Backporting live-iso fix to realease-1.1
https://github.com/metal3-io/cluster-api-provider-metal3/pull/690
> 🐛Only use redfish-virtualmedia for live-iso test (backport)

- OWNERS
This adds @adilGhaffarDev as reviewer! :tada: 
Adil has done a great job with live-iso testing and redfish-virtualmedia among others.
> 🌱 Add Adil as reviewer

- api/v1alpha5/metal3datatemplate_types.go
- api/v1alpha5/zz_generated.conversion.go
- api/v1beta1/metal3datatemplate_types.go
- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
This reverts parts of 0b68abba36a02539fe5a5df7d3643f1c0e98f84c that made
changes to the API.
> 🌱 Revert API breaking change

- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
- baremetal/utils.go
- config/manager/manager.yaml
- main.go
Fixes #630 
Related to: https://github.com/metal3-io/ip-address-manager/pull/119
> ✨ Support IP Reuse for BMHs using Preallocations

- OWNERS
Cherry pick the commit https://github.com/metal3-io/cluster-api-provider-metal3/pull/710 on owner file to release-0.5 was failing because of conflicts this PR syncs the file after resolving the conflict
> 🌱 sync OWNER file with main

- docs/api.md
- scripts/ci-e2e.sh
Fix dev-env template path since it was changed on dev-env here https://github.com/metal3-io/metal3-dev-env/pull/1061
> 🐛 Fix dev-env templates path

- README.md
also, add existing release-1.1 branch e2e test triggers in readme notes
> 📖 Note new release-1.2 branch e2e test triggers in readme

- scripts/environment.sh
- test/e2e/data/infrastructure-metal3/bases/cluster/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-metal3/bases/cluster/crs.yaml
- test/e2e/data/infrastructure-metal3/bases/cluster/kustomization.yaml
- test/e2e/pivoting_based_feature_test.go
This PR installs CNI using ClusterResourceSet
> 🌱 Install CNI with ClusterResourceSet

- test/e2e/data/infrastructure-metal3/bases/cluster/crs.yaml
- test/e2e/upgrade_management_cluster_test.go
Since we are using CRS to apply CNI I remove also the manual CNI apply
> Prameterize api version for ClusterResourceSet

- Tiltfile
- hack/gen_tilt_settings.sh
xref: https://github.com/metal3-io/metal3-dev-env/pull/1094#event-7661271690
> 🌱 Bump cert-manager to v1.10.0 in Tiltfile and script

- Makefile
This PR does:
- Fix an issue when pushing a new tag, i.e `v1.2.1` for a new release from the repo, Makefile target `release-notes` generates release notes with the wrong tag: instead of using the: `latest release - 1` (in our case v1.1.3), it fetches a pre-release` latest release - 2` (v1.2.0-rc.1) which is wrong. This should fix it by excluding pre-release tags if any.
- Improve `make release-notes` target to generate a specific message for pre-releases.
> 🌱 Fix PREVIOUS_TAG fetching in release-notes Makefile target

- .github/workflows/release.yaml
- Makefile
and `make release-notes` generation for pre-releases custom 
Cherry picks: https://github.com/metal3-io/cluster-api-provider-metal3/pull/781, https://github.com/metal3-io/cluster-api-provider-metal3/pull/782
> 🌱 Improve release automation process

- docs/ip_reuse.md
Documents IP Reuse feature in https://github.com/metal3-io/cluster-api-provider-metal3/pull/656
> 📖 Add IP reuse documentation

- test/e2e/data/infrastructure-metal3/v1beta1/metadata.yaml
- test/e2e/upgrade_management_cluster_test.go
> 🐛 Fix running e2e upgrade tests with pre-releases

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
Uplifts CAPI to the latest patch release, which includes security fixes.
> 🌱 Uplift CAPI to v1.2.6

- test/e2e/pivoting.go
https://github.com/metal3-io/cluster-api-provider-metal3/pull/728 follow up check comment https://github.com/metal3-io/cluster-api-provider-metal3/pull/728#discussion_r1030632080
> 🌱 Remove test suffix from pivoting function file

- hack/gomod.sh
- hack/gosec.sh
- hack/markdownlint.sh
Use docker.io consistently as image registry, and pin more checks by a version and digest.
> 🌱 use docker.io consistently, and pin more checks

- Makefile
Remove time command when running e2e and ginkgo cli instead of go test
> 🐛 Use gingko cli and timeout

- OWNERS
Add Tuomo to the reviewers list.
Contribution https://github.com/metal3-io/cluster-api-provider-metal3/pulls?q=is%3Apr+author%3Atuminoid+is%3Aclosed
> 🌱 Add tuminoid as a reviewer

- README.md
This PR will add the trigger phrases to keep VM for e2e job
> 🌱Add trigger phrases in the doc to keep VM for e2e CI jobs

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- baremetal/mocks/zz_generated.metal3machine_manager.go
- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_test.go
> 🐛 Remove bmhID arg from SetNodeProviderID call

- Makefile
- hack/build.sh
- hack/gofmt.sh
- test/e2e/e2e_suite_test.go
- test/e2e/live_iso_test.go
- test/e2e/upgrade_management_cluster_test.go
This PR is also adding the useful build-api and build e2e phonies which was added in main branch Makefile a while ago.
> 🐛 Fix Makefile command chaining

- controllers/metal3cluster_controller.go
- controllers/metal3data_controller.go
- controllers/metal3datatemplate_controller.go
- controllers/metal3labelsync_controller.go
- controllers/metal3machine_controller.go
- controllers/metal3machinetemplate_controller.go
- controllers/metal3remediation_controller.go
- main.go
> ✨Enable concurrency in metal3 controllers

- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- baremetal/mocks/zz_generated.metal3machine_manager.go
- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_test.go
> 🐛Remove bmhID arg from SetNodeProviderID call

- api/v1beta1/condition_consts.go
- controllers/metal3machine_controller.go
- controllers/metal3machine_controller_integration_test.go
- controllers/metal3machine_controller_test.go
This PR adds granular condition reasons to metal3machine object.
> 🌱 Add new condition reasons to m3machine

- scripts/environment.sh
- test/e2e/data/infrastructure-metal3/bases/ubuntu-kubeadm-config/ubuntu-kubeadm-config.yaml
Backporting MACAddressPolicy changes from this PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/823
> Changing MACAddressPolicy to none

- OWNERS
OWNERS has fallen out of sync, take it from main.
> 🌱 sync OWNERS from main

- hack/build.sh
- hack/codegen.sh
- hack/ensure-go.sh
- hack/ensure-golangci-lint.sh
- hack/ensure-kind.sh
- hack/ensure-kubectl.sh
- hack/ensure-kustomize.sh
- hack/gen_tilt_settings.sh
- hack/gofmt.sh
- hack/gomod.sh
- hack/gosec.sh
- hack/govet.sh
- hack/kind_with_registry.sh
- hack/kustomize-sub.sh
- hack/manifestlint.sh
- hack/markdownlint.sh
- hack/shellcheck.sh
- hack/unit.sh
- hack/verify-boilerplate.sh
Cleanup hack/*.sh formatting, mount dir generalization etc. No functional changes.
> 🌱 cleanup hack/ formatting

- scripts/fetch_target_logs.sh
- test/e2e/pivoting.go
Refactoring the log collection script as a follow up PR which will rename the kubeconfig variable for target log collection and also added improvement for the log collection script.
#922
> 🌱Refactor target  log collection script

- scripts/fetch_manifests.sh
- test/e2e/pivoting.go
It will add manifest collection for e2e test.
> 🌱Add manifest collection for e2e test

- scripts/fetch_manifests.sh
- test/e2e/pivoting.go
This PR will add manifest collection after re-pivot
> 🌱Add manifest collection after re-pivot

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
> 🌱Uplift IPAM release-1.2 tag v1.2.2

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
Bump IPAM to 1.3.1 for upcoming release.
> 🌱 bump IPAM to 1.3.1

- Tiltfile
- examples/generate.sh
- hack/gen_tilt_settings.sh
- test/e2e/config/e2e_conf.yaml
Follows: https://github.com/kubernetes-sigs/cluster-api/pull/8533
Fixes #928
> 🌱 Bump cert-manager to v1.11.1

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 bump IPAM to 1.4.0

- OWNERS
@Rozzii has 10 commits in the repo and has been doing great work.
> 🌱 Add Rozzii as reviewer

- Makefile
- README.md
Updates Makefile and README with release-1.4 branch and v1.4.0 mentions.
> 🌱 Add release-1.4 related changes

- README.md
Update build badges to point to correct release branch jobs.
> 🌱 update build badges to point to 1.2

- scripts/fetch_target_logs.sh
- test/e2e/pivoting.go
This is a manual backport of #922 and #924.
Fixes #
> 🌱 Backport e2e log improvements to release-1.3

- test/e2e/pivoting.go
- test/e2e/upgrade_management_cluster_test.go
This PR adds a wait function for deployment to become available after installing ironic or bmo
> 🌱 Add wait for ironic/bmo deployment becomes available

- baremetal/metal3machine_manager.go
- controllers/metal3machine_controller.go
> 🌱 Improve logging around ProviderID and BMHID formulation

- CONTRIBUTING.md
Document support and guarantee for api versions /releases.
> 📖 Add support and guarantees section in Contributing guide

- test/e2e/common.go
- test/e2e/node_reuse_test.go
This is fixing generation of sha256sum, it was not being formatted properly before which was resulting in wrong hash.
> :bug: Fixing sha256sum generation

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Uplift ipam to v1.3.2

- Makefile
- scripts/ci-e2e.sh
- scripts/environment.sh
- test/e2e/common.go
- test/e2e/e2e_suite_test.go
- test/e2e/ip_reuse.go
- test/e2e/ip_reuse_test.go
- test/go.mod
Add e2e test for IP reuse feature
> 🌱 Add IP reuse e2e tests

- test/e2e/live_iso_test.go
- test/e2e/pivoting_based_feature_test.go
- test/e2e/remediation_based_feature_test.go
Manual cherry-pick of  https://github.com/metal3-io/cluster-api-provider-metal3/pull/982
> 🌱 add features label for e2e feature tests for ginkgo focus

- baremetal/metal3remediation_manager_test.go
Improve unit test coverage:
HasFinalizer: 0% -> 100% coverage
> 🌱 Add UT to HasFinalizer

- OWNERS
Adding @Sunnatillo to the reviewers list since he has [10 commits](https://github.com/metal3-io/cluster-api-provider-metal3/commits?author=Sunnatillo) in the repo and helps with reviews consistently.
> 📖 Add Sunnat as a reviewer

- .github/dependabot.yml
- .github/workflows/dependabot.yml
This PR adds the dependabot config and workflow which will handle go module updates and other bumps.
> 🌱 Add dependabot config and workflow

- test/e2e/pivoting.go
- test/e2e/upgrade_management_cluster_test.go
This commit was implemented on main by https://github.com/metal3-io/cluster-api-provider-metal3/pull/936/
> :bug: backport "wait for ironic/bmo deployment becomes available"

- Dockerfile
Fix the way nonroot is part of the image pinning.
> 🌱 fix distroless:nonroot pinning

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 bump IPAM to 1.4.1

- main.go
We found out that TLS 1.0 and TLS 1.1 are enabled despite being insecure. These changes are backported to release-1.3 branch, but without the configuration flags. Min version is set to TLS12 and Max version set to TLS13, with no config to change those.
> :bug: Disable TLS 1.0 and TLS 1.1

- .github/ISSUE_TEMPLATE/failing-test.yaml
- .github/ISSUE_TEMPLATE/flaking-test.yaml
Adding templates to report CI failures
> ✨ Add test failing and flaking issue templates

- .github/ISSUE_TEMPLATE/flaking-test.yaml
> 🐛 Fix flaking test template

- scripts/ci-e2e.sh
- test/e2e/config/e2e_conf.yaml
> 🐛Manual back port enabling mariadb instead of SQLite for release-1.4

- scripts/ci-e2e.sh
- test/e2e/config/e2e_conf.yaml
Reverts metal3-io/cluster-api-provider-metal3#1093
> Revert "🐛Manual back port enabling mariadb instead of SQLite for release-1.4"

- scripts/environment.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/upgrade_kubernetes_test.go
- test/e2e/upgrade_management_cluster_test.go
Manual backport of #982, #963, #751
> Manual Backport of Kubernetes upgrade test related changes to release-1.3

- test/e2e/inspection.go
- test/e2e/integration_test.go
- test/e2e/live_iso_test.go
- test/e2e/metal3remediation.go
- test/e2e/node_reuse.go
- test/e2e/pivoting.go
- test/e2e/pivoting_based_feature_test.go
- test/e2e/remediation.go
- test/e2e/remediation_based_feature_test.go
- test/e2e/upgrade_baremetal_operator.go
- test/e2e/upgrade_ironic.go
- test/e2e/upgrade_kubernetes_test.go
Add human readable description of e2e tests
> 🌱 Add high level description to e2e tests

- README.md
Update testing section of the readme
> 🌱 Add basic tests to the Readme

- test/e2e/common.go
- test/go.mod
This PR adds log collection via ssh connection to the machine to the LogCollector.
> 🌱 Add the ssh log collection to logcollector

- scripts/ci-e2e.sh
Point m3 dev env branch to main after metal3 dev env repo CAPI bump merged
> Point m3 dev env branch back to main

- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 bump IPAM to 1.3.3

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 bump IPAM to 1.4.2

- .github/workflows/golangci-lint.yml
- hack/ensure-golangci-lint.sh
> 🌱 Bump golangci-lint to v1.54.2

- Tiltfile
- examples/generate.sh
- hack/gen_tilt_settings.sh
- test/e2e/config/e2e_conf.yaml
Uplifts cert-manager to v1.12.3
> 🌱 Bump cert-manager to v1.12.3

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
Uplift CAPI to latest v1.4 patch release
>  🌱 Bump CAPI to v1.4.6

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
Bump IPAM to newly released v1.5.0.
> 🌱 bump IPAM to v1.5.0

- hack/tools/release/notes.go
Fix typo in release note generator.
> 📖 fix typo in release note generator

- hack/tools/release/notes.go
> 📖 improve release note generator

- hack/tools/release/notes.go
> 📖 improve release notes generator

- scripts/ci-e2e.sh
- scripts/environment.sh
Pass thru KUBECTL_SHA256 from JJB for upgrade e2e tests.
Manual cherry-pick of #1178 adapted to release-1.5
> 🌱 add KUBECTL_SHA256 passthru

- Makefile
The phonys which are removed are unused and unmaintained for a while now and as a result broken. For local development we encourage to use Tilt environment.
> 🌱 Remove unused and unmaintained phonys from Makefile

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Uplift ipam to v1.3.4

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱Uplift ipam to v1.4.3

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
Uplift IPMA patch release v1.5.1
> 🌱Uplift IPAM to v1.5.1

- CONTRIBUTING.md
Update the version table after v1.5.0 is out.
> 📖 update contributing.md

- hack/tools/release/notes.go
Fix typo in release note generator.
> 🌱 fix typo in release note generator

- docs/releasing.md
Added prior art links to release documentation.
> :book: Added prior art links to release documentation.

- hack/verify-release.sh
Manual cherry-pick of #1238 without releasing.md parts.
> 🌱 add hack/verify-release.sh

- hack/verify-release.sh
Using GLOBIGNORE makes the code simpler, and allows us to ignore the hack/tools/go.mod for sed as well, not just in grep. This fixes issue that module versions are reported as incorrect, if hack/tools/go.mod is the one with wrong version, yet the output then does now show the hack/tools/go.mod as culprit.
> 🌱 use GLOBIGNORE to ignore hack/tools/go.mod in verify-release.sh

- Makefile
This allows to select a specific go version if multiple go versions are installed on a system.
The assumption that the `go` executable refers to a go version suitable for compiling is not always valid; with having the `go` executable parametrized it is possible to choose a suitable executable from a set of local go installations.
> :seedling: Configurable go executable

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump CAPI to v1.5.3

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump CAPI to v1.4.8

- api/go.mod
- api/go.sum
- hack/tools/go.mod
- hack/tools/go.sum
Dependabot missed dependency in api, and while at it, bump in hack/tools to match.
> 🌱 bump onsi/gomega v1.29.0

- .github/workflows/pr-verifier.yaml
- .gitignore
Adding PR title verifier. This uses https://github.com/kubernetes-sigs/kubebuilder-release-tools and makes sure that the title has an icon added. This will make the release process easier.
> 🌱 Adding PR title verifier

- baremetal/metal3data_manager.go
- baremetal/metal3data_manager_test.go
This is a manual cherry-pick of https://github.com/metal3-io/cluster-api-provider-metal3/pull/1361
It is manual since the original PR didn't have the DCO...
> [release-1.5] 🐛 Fix race condition getting IPAddress for Metal3Data

- README.md
- scripts/ci-e2e.sh
Remove release 1.3 related documentation and code paths.
> 🌱 remove release-1.3

- scripts/ci-e2e.sh
> 🐛 Fix for v1.6 clusterctl upgrade.

- Makefile
> 🌱 Bump envtest to v1.29.x

- Makefile
we can now do `make ginkgo` to make the ginkgo binary and use it locally
> 🌱 Add ginkgo phony in Makefile

- Makefile
Fixes https://github.com/metal3-io/cluster-api-provider-metal3/issues/1413
> 🐛 Install ginkgo directly instead of building it using go-modules

- Dockerfile
- Makefile
> 🌱 Bump golang to v1.20.14

- test/e2e/pivoting.go
> 🌱 Remove ironic-inspector from container list for ubuntu e2e tests

- .github/workflows/build-images-action.yml
Image build action is needed in each release branch too.
> 🌱 add build images action for release-1.6

- .github/workflows/build-images-action.yml
This reverts commit 98ae522003b8091bf85234caea7c8403aa4e3ff1. It wasn't the issue, so revert it to make it consistent with the rest.
> 🌱 Revert "try fix GH workflow for build images"

- .github/workflows/build-images-action.yml
Workflow file needs to be present in the branch its targeting.
> 🌱 add build images action to release-1.5

- test/e2e/basic_integration_test.go
- test/e2e/integration_test.go
- test/e2e/ip_reuse_test.go
- test/e2e/live_iso_test.go
- test/e2e/pivoting_based_feature_test.go
- test/e2e/remediation_based_feature_test.go
- test/e2e/upgrade_clusterctl_test.go
- test/e2e/upgrade_kubernetes_test.go
> :seedling: Add labels on e2e tests

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump CAPI to v1.6.3

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump CAPI to v1.5.7

- README.md
Update basic e2e trigger after migrating to prow
> 🌱 Update basic e2e trigger on README.md

- test/e2e/common.go
> [release-1.5] 🐛 e2e: Specify ip address pool for retreiving ip for ssh ing node

- test/e2e/pivoting.go
- test/go.mod
- test/go.sum
> 🌱 Bump docker go module to v26.0.0

- scripts/environment.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/upgrade_clusterctl_test.go
Simplifying and updating clusterctl upgrade tests. 
Fixes #
> :seedling:Simplifying and updating clusterctl upgrade tests

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱Uplift ipam 1.7.0-beta.0 release

- Tiltfile
- examples/generate.sh
- test/e2e/config/e2e_conf.yaml
Bump cert-manager version v1.13.0 -> v1.14.0
Fixes #1548
> :seedling: Bump cert-manager version v1.13.0 -> v1.14.0

- docs/e2e-test.md
Update e2e docs to add more detail about clusterctl upgrade tests and k8s upgrade tests.
Fixes #
> 📖 Update e2e docs

- Makefile
- Add auto fix golang lint via make target
Fixes #1546
> 🌱 Add lint-fix as make target

- scripts/environment.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/upgrade_clusterctl_test.go
Simplifying and updating clusterctl upgrade tests
Fixes #
> 🌱 Simplifying and updating clusterctl upgrade tests

- Dockerfile
- Makefile
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump golang.org/x/net to v0.23.0 and golang to v1.21.9

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump CAPI to v1.7.0-rc.1

- scripts/environment.sh
- test/e2e/upgrade_clusterctl_test.go
> 🌱 Use PostNamespaceCreated hook to apply bmh in clusterctl upgrade

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱  BUMP CAPI to v1.5.8

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump CAPI to v1.7.0

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱  Bump CAPI  to v1.6.4

- README.md
Update triggers after migrated to prow
> 🌱 Update e2e triggers for release-1.6

- README.md
This PR:
Update build status badges
Update compatibility table
Update test triggers
> 🌱 Update README on job triggers in release-1.7

- hack/verify-release.sh
Few improvements from previous minor release cycle:
- change artefact to artifact for more common spelling
- match container image detection from release notes to match the earlier change in the release tooling
- rename some of the titles to be more descriptive
- mutate go.mod files for osv-scanner so it can accurately report vulnerablities in golang stdlib (ie. mutate "go 1.21" directive to "go 1.21.9" with patch version read off from main Dockerfile
- check version of osv-scanner, <1.5.0 give weird warnings now
- make docker pull gcrane and osv-scanner images always, so it uses the newest versions
Same as/adapted [BMO #1691](https://github.com/metal3-io/baremetal-operator/pull/1691)
> 🌱 improve hack/verify-release.sh

- CONTRIBUTING.md
- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 bump CAPI to v1.7.1

- scripts/ci-e2e.sh
- test/e2e/config/e2e_conf.yaml
> 🌱 Remove deprecated/unused vars from e2e config

- CONTRIBUTING.md
- Makefile
- README.md
- docs/e2e-test.md
- hack/verify-release.sh
- scripts/ci-e2e.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/upgrade_clusterctl_test.go
Added a test and configurations for release-1.7. Also some minor changes to comments and documentation.
Fixes #1621
> :seedling: Release-1.7 related changes

- OWNERS
I can't commit to being an approver in this repo, so I am moving myself to emeritus approvers.
> 🌱 Move furkatgofurov7 to emeritus approvers

- OWNERS
This PR adds the following people as approvers
- @adilGhaffarDev
- @smoshiur1237
- @Sunnatillo
- @tuminoid
also adds @dtantsur as a reviewer. Thanks a lot folks for your contributions.
> 🌱 Add Adil, Moshiur, Sunnat and Tuomo as approvers and Dmitry as a reviewer

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump CAPI v1.6.5

- README.md
- api/go.mod
- api/go.sum
- docs/e2e-test.md
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump CAPI to v1.7.2

- baremetal/metal3machine_manager_test.go
Add unit tests for method duplicateProviderIDsExist (metal3machine_manager.go). 
A problem was detected and fixed in https://github.com/metal3-io/cluster-api-provider-metal3/pull/675. These unit tests will prevent errors hopefully. 
Fixes #
> :seedling: Add unit tests for duplicateProviderIDsExist

- README.md
- api/go.mod
- api/go.sum
- test/go.mod
- test/go.sum
Bump CAPI to 1.6.6 in api and test folders
> 🌱 Bump CAPI to 1.6.6 in api and test folders

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
Bump IPAM to latest minor release v1.6.3
> :seedling: Bump IPAM to v1.6.3

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
Bump IPAM to latest minor release v1.7.1
> :seedling: Bump IPAM to v1.7.1

- Dockerfile
- Makefile
> 🌱 bump golang to 1.22.5

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump CAPI to v1.6.7 

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump CAPI to v1.7.4

- README.md
This will update the feature tests triggers on the PR to run them independently.
> 📖 Update triggers for feature tests

- README.md
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱  Bump CAPI to v1.8.0

- Dockerfile
- Makefile
> 🌱 bump golang to 1.22.6

- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 bump CAPI to v1.6.8

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> :seedling: Bump IPAM to v1.7.2

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> :seedling: Bump IPAM to v1.6.4

- .github/dependabot.yml
Add dependabot config for release-1.8.
> 🌱 add dependabot config for release-1.8

- clusterctl-settings.json
- test/e2e/config/e2e_conf.yaml
- test/e2e/data/infrastructure-metal3/main/metadata.yaml
Adding contracts in configs for tests
Fixes #
> 🌱 Adding contracts in configs for tests

- go.mod
- go.sum
- test/go.mod
- test/go.sum
> :seedling: Uplift BMO to v0.5.2

- go.mod
- go.sum
- test/go.mod
- test/go.sum
> :seedling: Uplift BMO to v0.6.2

- README.md
This PR fixes minor issues in test link, test label and test name.
> 📖 Fix issues in test links and triggers

- test/e2e/cert_rotation.go
This PR fixes the cert rotation tests changing workflow of the test. 
Previously we checked ironic containers restart when we delete the certificate secret.
With new workflow ironic is updating secret mount without restarting the containers. Now in cert rotation tests we just check if the all ironic pod containers are running for certain period of time without any issue. 
TODO. As a next step we can implement checking querying ironic endpoint with new certificate to confirm  it is working.
> 🐛 Fix cert rotation tests

- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Uplifts CAPI v1.7.6

- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Uplift CAPI to v1.8.3

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> :seedling: Bump IPAM to v1.8.1

- Dockerfile
- Makefile
> 🌱 bump golang to 1.22.8

- Makefile
> 🌱 Backport fix for test timeout

- api/go.mod
- api/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump CAPI to v1.8.5

- baremetal/metal3cluster_manager.go
- baremetal/metal3data_manager.go
- baremetal/metal3datatemplate_manager.go
- baremetal/metal3machine_manager.go
- baremetal/utils.go
- baremetal/utils_test.go
Using controllerutils to add and remove finalizers. Using controllerutil is thread safe, handles race conditions and has few other advantegous.
> 🌱 Use controllerutils to add/remove finalizers

- .github/workflows/osv-scanner-scan.yml
Add scheduled osv-scanner workflow.
> :seedling: add scheduled osv-scanner workflow

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
**What this PR does / why we need it**: Bump IPAM from v1.8.1 to v1.8.2
> :seedling: Bump IPAM to v1.8.2

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
**What this PR does / why we need it**: Bump IPAM from v1.7.2 to v1.7.3
> :seedling: Bump IPAM to v1.7.3

- api/go.mod
- api/go.sum
- go.mod
- go.sum
- hack/fake-apiserver/go.mod
- hack/fake-apiserver/go.sum
- test/go.mod
- test/go.sum
**What this PR does / why we need it**: Bump CAPI from v1.9.0-rc.0 to v1.9.0-rc.1
> :seedling: Bump CAPI to v1.9.0-rc.1

- api/go.mod
- api/go.sum
- go.mod
- go.sum
- hack/fake-apiserver/go.mod
- hack/fake-apiserver/go.sum
- test/go.mod
- test/go.sum
> :seedling: Bump CAPI to v1.9.0

- .github/dependabot.yml
Drop release-1.7 and add release-1.9.
> :seedling: update dependabot config for release-1.9

- scripts/environment.sh
Fix FROM_K8S_VERSION variable v1.30.0 -> v1.31.2
Fixes #
> 🌱 Fix FROM_K8S_VERSION variable v1.30.0 -> v1.31.2

- docs/e2e-test.md
Improve documentation regarding running e2e tests.
Fixes #
> 📖 Improve e2e documentation

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
**What this PR does / why we need it**: Bump IPAM to 1.8.3
> :seedling: Bump IPAM to 1.8.3

- .github/workflows/release.yaml
This workflow does an automatic tag, build and push images for a custom release when the note of that release is merged into the main branch.
> :seedling: Take the new release workflow into use

- releasenotes/v1.8.4.md
**What this PR does / why we need it**:  Release v1.8.4
> :rocket: Release v1.8.4

- test/e2e/config/e2e_conf.yaml
- test/e2e/node_reuse.go
- test/e2e/pivoting_based_feature_test.go
manual backport of https://github.com/metal3-io/cluster-api-provider-metal3/pull/2212
Fixes #
> 🌱 Fix e2e pivoting(node_reuse) test

- OWNERS_ALIASES
Both Peppi-lotta and Huy has reached the required number of commits and also helped in the review process recently. Thanks a lot folks for your contributions.
> 🌱 Add Peppi-lotta and Huy as reviewers

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
**What this PR does / why we need it**: Bump Ip-Address-Manager to 1.8.4
> :seedling: Bump IPAM to 1.8.4

- releasenotes/v1.9.2.md
**What this PR does / why we need it**: Release v1.9.2
> :rocket: Release v1.9.2

- releasenotes/v1.8.5.md
**What this PR does / why we need it**: Release v1.8.5
> :rocket: Release v1.8.5

- hack/tools/release/notes.go
Add miriadb image tag in release notes
Fixes #
> 🌱 Add miriadb image tag in release notes

- api/go.mod
- api/go.sum
- go.mod
- go.sum
- hack/fake-apiserver/go.mod
- hack/fake-apiserver/go.sum
- test/e2e/scalability_test.go
- test/go.mod
- test/go.sum
manual cherry-pick of https://github.com/metal3-io/cluster-api-provider-metal3/pull/2343 
Fixes #
> 🌱 Bump CAPI to 1.9.5

- api/v1beta1/metal3data_types.go
- api/v1beta1/metal3datatemplate_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
**What this PR does / why we need it**: Add deprecation notice to M3d templateReference field
Related PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/2265
> :warning:  Deprecate Metal3data templateReference

- api/go.mod
- api/go.sum
- config/ipam/image_patch.yaml
- config/ipam/kustomization.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
**What this PR does / why we need it**: Bump IPAM to 1.8.5
> :seedling: Bump IPAM to 1.8.5

- docs/releasing.md
**What this PR does / why we need it**: Change IPAM links to pass link check. These wiles no longer exist in main but are relevant for release branch.
> :book: Fix broken IPAM kustomization links in releasing.md

- releasenotes/v1.9.3.md
**What this PR does / why we need it**: :rocket: Release v1.9.3
> :rocket: Release v1.9.3

- releasenotes/v1.8.6.md
**What this PR does / why we need it**: :rocket: Release v1.8.6
> :rocket: Release v1.8.6

- Tiltfile
- examples/generate.sh
- test/e2e/config/e2e_conf.yaml
> 🌱 Bump cert-manager to v1.17.1

- go.mod
- go.sum
- test/go.mod
- test/go.sum
> :seedling: bump BMO to v0.8.1

- OWNERS
- OWNERS_ALIASES
@mquhuy is not active as a reviewer in this project anymore. Thanks Huy for all your contributions.
> 🌱 Move @mquhuy to emeritus reviewers

- .github/workflows/release.yaml
Set GITHUB_TOKEN in env release wf
Fixes #
> 🌱 Set GITHUB_TOKEN in env release wf

- .golangci.yaml
- baremetal/utils.go
- controllers/metal3cluster_controller.go
- test/e2e/upgrade_clusterctl_test.go
**What this PR does / why we need it**: Enabled forcetypeassert linter
Fixes #2443
> :seedling: Enabled forcetypeassert linter

- .golangci.yaml
- baremetal/metal3datatemplate_manager.go
- test/e2e/node_reuse.go
- test/e2e/upgrade_clusterctl_test.go
- test/e2e/upgrade_kubernetes_test.go
**What this PR does / why we need it**: Enabled intrange linter
Fixes #2444
> :seedling: Enabled intrange linter

- .golangci.yaml
**What this PR does / why we need it**: Enabled tagliatelle linter
Fixes #2448
> :seedling: Enabled tagliatelle linter

- .golangci.yaml
- baremetal/metal3data_manager.go
**What this PR does / why we need it**: Enabled dupl linter
Fixes #2438
> :seedling: Enabled dupl linter

- api/go.mod
- api/go.sum
- go.mod
- go.sum
- hack/fake-apiserver/go.mod
- hack/fake-apiserver/go.sum
- test/go.mod
- test/go.sum
**What this PR does / why we need it**: Bump CAPI to 1.10.1
> :seedling: Bump CAPI to 1.10.1

- README.md
**What this PR does / why we need it**: Update build badges and triggers in README.md
> :book: Update build badges and triggers in README.md

- CONTRIBUTING.md
- README.md
- docs/e2e-test.md
**What this PR does / why we need it**: Update docs for release 1.10
> :book: Update docs for release 1.10

- .golangci.yaml
- baremetal/metal3machine_manager.go
**What this PR does / why we need it**:  Enabled exhaustive linter
Fixes #2441
> :seedling: Enable exhaustive linter

- baremetal/metal3machine_manager.go
- test/e2e/config/e2e_conf.yaml
- test/e2e/data/ipam-metal3/v1.10/metadata.yaml
- test/e2e/upgrade_clusterctl_test.go
Fix ipam deploy in clusterctl tests
Fixes #
> 🌱 Fix ipam deploy in clusterctl tests

- scripts/ci-e2e.sh
- test/e2e/common.go
- test/e2e/config/e2e_conf.yaml
- test/e2e/data/infrastructure-metal3/v1.10/metadata.yaml
- test/e2e/upgrade_clusterctl_test.go
Updating main branch clusterctl tests
Fixes #
> 🌱 Updating main branch clusterctl tests

- scripts/environment.sh
Fix CONTROL_PLANE_MACHINE_COUNT and WORKER_MACHINE_COUNT for k8s upgrade test
Fixes #
> 🌱 Fix CONTROL_PLANE_MACHINE_COUNT and WORKER_MACHINE_COUNT for k8s upgrade and remediation test

- test/e2e/common.go
Fixing remediation tests.
Always get BMH before changing, so we make sure it is not an outdated or stale object.
Fixes #
> 🌱 Fixing remediation tests

- controllers/metal3data_controller.go
**What this PR does / why we need it**: When upgrading it was seen that there is persistently a 30s delay between register end and provision start. Around same time patching Metal3Data fails and it happens because we try to patch Metal3Data after it is already deleted. So, add check for the situation that Metal3Data is deleted and can't be patched. 
Added also (temporary) logging to investigate if the delay could be also caused by re-queuing on a situation where Metal3DataClaim still exists. `requeueAfter` is set to 30s.
> :bug: Fix trying to patch Metal3Data if it is deleted

- controllers/metal3data_controller.go
**What this PR does / why we need it**: What this PR does / why we need it: When upgrading it was seen that there is persistently a 30s delay between register end and provision start. Around same time patching Metal3Data fails and it happens because we try to patch Metal3Data after it is already deleted. So, add check for the situation that Metal3Data is deleted and can't be patched.
Added also (temporary) logging to investigate if the delay could be also caused by re-queuing on a situation where Metal3DataClaim still exists. requeueAfter is set to **30s.**
> :seedling: Fix trying to patch Metal3Data if it is deleted

- .golangci.yaml
- baremetal/metal3data_manager.go
- baremetal/metal3datatemplate_manager.go
- baremetal/metal3machine_manager.go
- baremetal/metal3machine_manager_test.go
- baremetal/utils.go
- baremetal/utils_test.go
- controllers/metal3cluster_controller.go
- controllers/metal3data_controller.go
- controllers/metal3datatemplate_controller.go
- controllers/metal3labelsync_controller.go
- controllers/metal3labelsync_controller_test.go
- controllers/metal3machine_controller.go
- controllers/metal3machinetemplate_controller.go
- controllers/metal3remediation_controller.go
- main.go
- test/e2e/common.go
- test/e2e/e2e_suite_test.go
- test/e2e/ip_reuse_test.go
- test/e2e/k8s_conformance_test.go
- test/e2e/logcollector.go
- test/e2e/md_remediations_test.go
- test/e2e/md_rollout_test.go
- test/e2e/md_scale_test.go
- test/e2e/pivoting.go
- test/e2e/pivoting_based_feature_test.go
- test/e2e/remediation.go
- test/e2e/remediation_based_feature_test.go
- test/e2e/scalability_test.go
- test/e2e/upgrade_kubernetes_test.go
> 🌱 Enable govet shadow variables

- test/e2e/data/ironic-deployment/overlays/release-25.0/ironic_bmo_configmap.env
- test/e2e/data/ironic-deployment/overlays/release-26.0/ironic_bmo_configmap.env
- test/e2e/data/ironic-deployment/overlays/release-latest/ironic_bmo_configmap.env
> 🌱 Add IPA_BASEURI in ironic config to fix IPA download for release-1.9

- test/e2e/data/ironic-deployment/overlays/pr-test/ironic_bmo_configmap.env
- test/e2e/data/ironic-deployment/overlays/release-26.0/ironic_bmo_configmap.env
- test/e2e/data/ironic-deployment/overlays/release-27.0/ironic_bmo_configmap.env
- test/e2e/data/ironic-deployment/overlays/release-latest/ironic_bmo_configmap.env
> 🌱Add IPA_BASEURI in ironic config to fix IPA download for release-1.10

- api/go.mod
- api/go.sum
- go.mod
- go.sum
- hack/fake-apiserver/go.mod
- hack/fake-apiserver/go.sum
- test/go.mod
- test/go.sum
Bumping CAPI to latest v1.10.x release
> 🌱 Bump CAPI to v1.10.6

- README.md
This commit:
- Updates GH comment based build trigger docs
- Updates build badges
- Updates support matrix doc
- Removes irrelevant triggers from documentation
> :book: Update trigger doc, build badges, support matrix

- baremetal/metal3data_manager.go
**What this PR does / why we need it**: Add logging to releaseAddressFromM3Pool function to help debugging
> :seedling: Add logging to releaseAddressFromM3Pool function

- scripts/ci-e2e.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/data/ironic-deployment/overlays/release-32.0/ironic_bmo_configmap.env
- test/e2e/data/ironic-deployment/overlays/release-32.0/keepalived_patch.yaml
- test/e2e/data/ironic-deployment/overlays/release-32.0/kustomization.yaml
- test/e2e/upgrade_clusterctl_test.go
Adding kustomization for ironic release-0.32
> 🌱Add kustomization for new ironic release-32.0

- examples/templates/clusterclass.yaml
- scripts/ci-e2e.sh
- test/e2e/config/e2e_conf.yaml
- test/e2e/data/infrastructure-metal3/main/bases/clusterclass/clusterclass.yaml
- test/e2e/data/infrastructure-metal3/main/clusterclass-metal3/clusterclass-metal3.yaml
- test/e2e/scalability_test.go
This is fixing scalability test.
Fixes #
> 🌱 Fix scalability tests
